//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIObject.h"

@class NSString;

@interface Context : DIObject
{
    NSString *_title;
    NSString *_groupBy;
}

@property(retain, nonatomic) NSString *groupBy; // @synthesize groupBy=_groupBy;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)reloadPosition;
- (id)description;
- (id)toDictionary;
- (id)initWithDictionay:(id)arg1;
- (_Bool)isEditable;
- (_Bool)isMatchObj:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isContext;
- (_Bool)isBelongTo:(id)arg1;

@end

