//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIBizTag : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)deleteTag:(id)arg1;
- (_Bool)saveTag:(id)arg1;

@end

