//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIBizNotice : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)deleteNotice:(id)arg1;
- (_Bool)readNotice:(id)arg1;
- (_Bool)rejectInvite:(id)arg1;
- (_Bool)passInvite:(id)arg1;
- (_Bool)saveToLocal:(id)arg1;

@end

