//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIBizContact : NSObject
{
}

+ (id)sharedInstance;
- (id)contactWithEmail:(id)arg1;
- (id)contactsHasPassed;
- (id)contacts;
- (_Bool)deleteContact:(id)arg1;
- (_Bool)saveContact:(id)arg1;
- (_Bool)saveToFrequentContact:(id)arg1;

@end

