//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskListViewController.h"

#import "DIGrowingTextViewDelegate.h"

@class DIGrowingTextView, NSString, UIView;

@interface DIContextViewController : DITaskListViewController <DIGrowingTextViewDelegate>
{
    DIGrowingTextView *_titleTextView;
    UIView *_contextView;
    _Bool _editingContextTitle;
}

- (void).cxx_destruct;
- (void)refresh;
- (void)actor:(id)arg1 didEditContext:(id)arg2 editType:(int)arg3;
- (void)close;
- (void)hideKeyboard:(id)arg1;
- (void)save:(id)arg1;
- (void)cancel:(id)arg1;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (_Bool)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextView:(id)arg1 willChangeHeightTo:(float)arg2;
- (void)growingTextViewDidBeginEditing:(id)arg1;
- (_Bool)growingTextViewShouldBeginEditing:(id)arg1;
- (void)cancelEditingContextTitle;
- (void)setEditingContextTitleBarButtonItems;
- (id)titleAttributes;
- (void)updateTitle;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadTableContent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

