//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIDailyReviewController.h"

@interface DIDailyReviewController (Private)
- (id)p_tabBarItemsForTask:(id)arg1;
- (void)p_updateTitle;
- (void)p_setNavigationBarForDoneView;
- (void)p_setNavigationBarForTaskView;
- (id)p_controllerAtIndex:(long long)arg1;
- (void)p_reloadDataOnDay:(id)arg1;
- (id)p_viewControllerForReview:(id)arg1;
@end

