//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIDBTask.h"

@interface DIDBTask (FindTaskOnDay)
- (id)planedTaskOnDay:(id)arg1;
- (id)sentTasksOnDay:(id)arg1;
- (id)completedTasksOnDay:(id)arg1;
@end

