//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIDBGuideTip : NSObject
{
}

- (id)findAllTitles;
- (id)findById:(id)arg1;
- (id)findAll;
- (id)queryGuideTips:(id)arg1 args:(id)arg2;
- (_Bool)destroy:(id)arg1;
- (_Bool)save:(id)arg1 fromServer:(_Bool)arg2;
- (_Bool)isIdExisted:(id)arg1;
- (id)sqlParametersDictionaryOfGuideTip:(id)arg1 fromServer:(_Bool)arg2;

@end

