//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIDBTag : NSObject
{
}

+ (id)findTag:(id)arg1 inDB1_0:(id)arg2;
- (id)findByName:(id)arg1;
- (id)findById:(id)arg1;
- (id)findAll;
- (id)findAllNames;
- (_Bool)isNameExisted:(id)arg1;
- (_Bool)updateId:(id)arg1 newId:(id)arg2;
- (_Bool)destroy:(id)arg1;
- (_Bool)save:(id)arg1 fromServer:(_Bool)arg2;
- (id)sqlParametersDictionaryOfTag:(id)arg1 fromServer:(_Bool)arg2;
- (_Bool)isIdExisted:(id)arg1;
- (id)queryStringArray:(id)arg1 args:(id)arg2;
- (id)queryTags:(id)arg1 args:(id)arg2;

@end

