//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface DIGlobalData : NSObject
{
    _Bool _isTomorrowHidden;
    NSDictionary *_boxes;
    NSArray *_dynamicBoxes;
    NSArray *_filters;
    NSArray *_contacts;
    NSArray *_projectsName;
    NSArray *_contextsName;
    NSArray *_tagsName;
    NSArray *_goalsName;
    NSArray *_contexts;
    NSDictionary *_projectsDic;
    NSArray *_projects;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isTomorrowHidden; // @synthesize isTomorrowHidden=_isTomorrowHidden;
@property(readonly, nonatomic) NSArray *projects; // @synthesize projects=_projects;
@property(readonly, nonatomic) NSDictionary *projectsDic; // @synthesize projectsDic=_projectsDic;
@property(readonly, nonatomic) NSArray *contexts; // @synthesize contexts=_contexts;
@property(readonly, nonatomic) NSArray *goalsName; // @synthesize goalsName=_goalsName;
@property(readonly, nonatomic) NSArray *tagsName; // @synthesize tagsName=_tagsName;
@property(readonly, nonatomic) NSArray *contextsName; // @synthesize contextsName=_contextsName;
@property(readonly, nonatomic) NSArray *projectsName; // @synthesize projectsName=_projectsName;
@property(readonly, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(readonly, nonatomic) NSArray *filters; // @synthesize filters=_filters;
@property(readonly, nonatomic) NSArray *dynamicBoxes; // @synthesize dynamicBoxes=_dynamicBoxes;
@property(readonly, nonatomic) NSDictionary *boxes; // @synthesize boxes=_boxes;
- (void).cxx_destruct;
- (id)timeZones;
- (id)startOfScheduled;
- (id)boxWithType:(int)arg1;
- (void)reloadGoalsName;
- (void)reloadTagsName;
- (void)reloadContexts;
- (void)reloadProjects;
- (void)reloadFilters;
- (void)reloadBoxes;
- (void)reloadContacts;
- (void)reloadData;

@end

