//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskInfoSection.h"

@class UITableView, UIView;

@interface DIHeaderSection : DITaskInfoSection
{
    UIView *_sectionHeader;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *sectionHeader; // @synthesize sectionHeader=_sectionHeader;
- (void).cxx_destruct;
- (void)cleanDataDirty;
- (_Bool)isDataDirty;
- (id)sectionHeaderInTableView:(id)arg1;
- (double)sectionHeaderHeightInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRow:(long long)arg2;
- (void)registerInTableView:(id)arg1;

@end

