//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DIListBox, NSString;

@protocol DIListBoxDelegate <NSObject>

@optional
- (void)listBox:(DIListBox *)arg1 didAddNewItem:(NSString *)arg2;
- (_Bool)listBox:(DIListBox *)arg1 willAddNewItem:(NSString *)arg2;
- (void)listBox:(DIListBox *)arg1 didSelectItem:(NSString *)arg2;
- (_Bool)listBox:(DIListBox *)arg1 willSelectItem:(NSString *)arg2;
@end

