//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UITableView;

@interface DIMultiSelectionController : SIViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    CDUnknownBlockType _SelectionCount;
    CDUnknownBlockType _SelectionString;
    CDUnknownBlockType _SelecionBlock;
    CDUnknownBlockType _ShowCheckmark;
}

@property(copy, nonatomic) CDUnknownBlockType ShowCheckmark; // @synthesize ShowCheckmark=_ShowCheckmark;
@property(copy, nonatomic) CDUnknownBlockType SelecionBlock; // @synthesize SelecionBlock=_SelecionBlock;
@property(copy, nonatomic) CDUnknownBlockType SelectionString; // @synthesize SelectionString=_SelectionString;
@property(copy, nonatomic) CDUnknownBlockType SelectionCount; // @synthesize SelectionCount=_SelectionCount;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)reloadData;
- (void)viewWillLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

