//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface DIOperation : NSObject
{
    int _opType;
    int _itemType;
    NSDate *_created;
    NSString *_uuid;
    NSString *_extraId;
    NSString *_relatedData;
    long long _localId;
}

+ (_Bool)appendOpLogToDB1_0:(id)arg1 db:(id)arg2;
+ (id)findOperationsFromPk:(long long)arg1 maxCount:(long long)arg2 inDB1_0:(id)arg3;
+ (_Bool)onUpgradeOperationsDBBefore327:(id)arg1;
+ (id)findOperationsLogsBefore327:(id)arg1 db:(id)arg2;
+ (_Bool)updateOpLogUUID:(id)arg1 newId:(id)arg2;
+ (_Bool)clearOpLogWith:(id)arg1 andExtraId:(id)arg2;
+ (id)getTopOperation;
+ (id)getCreateOperation;
+ (id)findOperations;
+ (_Bool)removeOpLogOfDailyReview:(id)arg1;
+ (_Bool)removeOpLogOfContact:(id)arg1;
+ (_Bool)removeOpLogOfAvatar:(id)arg1;
+ (_Bool)removeOpLogOfGuideTip:(id)arg1;
+ (_Bool)removeOpLogOfSubTask:(id)arg1;
+ (_Bool)removeOpLogOfGoal:(id)arg1;
+ (_Bool)removeOpLogOfAudio:(id)arg1;
+ (_Bool)removeOpLogOfNotice:(id)arg1;
+ (_Bool)removeOpLogOfFilter:(id)arg1;
+ (_Bool)removeOpLogOfBox:(id)arg1;
+ (_Bool)removeOpLogOfTag:(id)arg1;
+ (_Bool)removeOpLogOfContext:(id)arg1;
+ (_Bool)removeOpLogOfProject:(id)arg1;
+ (_Bool)removeOpLogOfTask:(id)arg1;
+ (void)revertTaskConvertProject:(id)arg1;
+ (_Bool)removeOpLogWithItemId:(id)arg1 extraId:(id)arg2;
+ (_Bool)removeOpLogByLocalId:(long long)arg1;
+ (_Bool)removeOpLog:(id)arg1;
+ (_Bool)appendOpLog:(id)arg1 triggerSync:(_Bool)arg2;
+ (_Bool)appendOpLog:(id)arg1;
+ (id)operationOfPull;
+ (_Bool)appendOpOfDownloadData;
+ (_Bool)appendOpOfFindProjectConfirm:(id)arg1;
+ (_Bool)appendOpOfFindTaskConfirm:(id)arg1;
+ (_Bool)appendOpOfGetUserInfo;
+ (_Bool)appendOpOfUpdateAccount;
+ (_Bool)removeBatchOpLog:(id)arg1;
+ (_Bool)appendBatchTaskOperation:(int)arg1 relatedData:(id)arg2;
+ (_Bool)appendOpOfDailyReview:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfAvatar:(id)arg1 opType:(int)arg2;
+ (_Bool)isOpExist:(id)arg1 itemType:(int)arg2 opType:(int)arg3;
+ (_Bool)appendOpOfAudio:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfSubTask:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfGoal:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfComment:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfNotice:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfContact:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfFilter:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfBox:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfTag:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfGuideTip:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfContext:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfProject:(id)arg1 opType:(int)arg2;
+ (_Bool)appendOpOfTask:(id)arg1 opType:(int)arg2;
@property(nonatomic) long long localId; // @synthesize localId=_localId;
@property(copy, nonatomic) NSString *relatedData; // @synthesize relatedData=_relatedData;
@property(nonatomic) int itemType; // @synthesize itemType=_itemType;
@property(copy, nonatomic) NSString *extraId; // @synthesize extraId=_extraId;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) int opType; // @synthesize opType=_opType;
@property(copy, nonatomic) NSDate *created; // @synthesize created=_created;
- (void).cxx_destruct;
- (id)init;
- (id)description;

@end

