//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "KKGestureLockViewDelegate.h"

@class DIAvatarImageView, KKGestureLockView, NSString, UIButton, UIImageView, UILabel;

@interface DIPasscodeViewController : SIViewController <KKGestureLockViewDelegate>
{
    _Bool _matchSavedPasscode;
    int _passcodeViewType;
    UIButton *_cancelButton;
    UILabel *_tipLabel;
    DIAvatarImageView *_avatarImageView;
    KKGestureLockView *_gestureLockView;
    NSString *_firstInputPasscode;
    UIImageView *_bkView;
}

@property(retain, nonatomic) UIImageView *bkView; // @synthesize bkView=_bkView;
@property(nonatomic) _Bool matchSavedPasscode; // @synthesize matchSavedPasscode=_matchSavedPasscode;
@property(retain, nonatomic) NSString *firstInputPasscode; // @synthesize firstInputPasscode=_firstInputPasscode;
@property(retain, nonatomic) KKGestureLockView *gestureLockView; // @synthesize gestureLockView=_gestureLockView;
@property(retain, nonatomic) DIAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) int passcodeViewType; // @synthesize passcodeViewType=_passcodeViewType;
- (void).cxx_destruct;
- (void)cancel:(id)arg1;
- (void)close;
- (void)gestureLockView:(id)arg1 didCanceledWithPasscode:(id)arg2;
- (void)gestureLockView:(id)arg1 didEndWithPasscode:(id)arg2;
- (id)newLockView;
- (id)newTipLabel;
- (id)newAvatarImageView;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

