//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIPieChart.h"

@interface DIPieChart (Private)
- (id)p_newCircleLayerWithBorderWidth:(double)arg1 fillColor:(id)arg2 borderColor:(id)arg3 startPercentage:(double)arg4 endPercentage:(double)arg5;
- (void)p_reloadCycleLayers;
@end

