//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskListViewController.h"

#import "DIEvernoteViewCellDelegate.h"

@class DIEvernoteViewCell, NSString, UIButton, UIImageView, UILabel;

@interface DIProjectViewController : DITaskListViewController <DIEvernoteViewCellDelegate>
{
    UILabel *_titleLabel;
    UIButton *_checkBox;
    DIEvernoteViewCell *_evernoteView;
    UILabel *_contextLabel;
    UILabel *_goalLabel;
    UIImageView *_goalIcon;
}

@property(retain, nonatomic) UIImageView *goalIcon; // @synthesize goalIcon=_goalIcon;
@property(retain, nonatomic) UILabel *goalLabel; // @synthesize goalLabel=_goalLabel;
@property(retain, nonatomic) UILabel *contextLabel; // @synthesize contextLabel=_contextLabel;
@property(retain, nonatomic) DIEvernoteViewCell *evernoteView; // @synthesize evernoteView=_evernoteView;
@property(retain, nonatomic) UIButton *checkBox; // @synthesize checkBox=_checkBox;
- (void).cxx_destruct;
- (void)evernoteViewCell:(id)arg1 pressedOnIndex:(long long)arg2;
- (void)refresh;
- (void)actor:(id)arg1 didEditProject:(id)arg2 editType:(int)arg3;
- (void)checkBoxClicked:(id)arg1;
- (void)headerViewTapped:(id)arg1;
- (void)loadCheckBox;
- (id)titleAttributes;
- (void)viewDidLoad;
- (void)p_updateSubTitles;
- (void)p_updateHeaderViewForEvernote;
- (void)updateTitle;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

