//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIRepeatPolicy.h"

@interface DIRepeatMonthlyPolicy : DIRepeatPolicy
{
    int _option;
    long long _weekOfMonth;
    long long _dayOfWeek;
    long long _dayOfMonth;
}

@property(nonatomic) long long dayOfMonth; // @synthesize dayOfMonth=_dayOfMonth;
@property(nonatomic) long long dayOfWeek; // @synthesize dayOfWeek=_dayOfWeek;
@property(nonatomic) long long weekOfMonth; // @synthesize weekOfMonth=_weekOfMonth;
@property(nonatomic) int option; // @synthesize option=_option;
- (id)description;

@end

