//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "DIRelativeReminderCellDelegate.h"
#import "DIScheduledViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSNumber, NSString, Task, UITableView;

@interface DIReminderViewController : SIViewController <UITableViewDataSource, UITableViewDelegate, DIRelativeReminderCellDelegate, DIScheduledViewControllerDelegate>
{
    UITableView *_tableView;
    _Bool _relativeReminderEditable;
    id <DIReminderViewControllerDelegate> _controllerDelegate;
    Task *_task;
    NSMutableArray *_reminders;
    NSMutableArray *_absoluteReminders;
    NSMutableArray *_relativeReminders;
    NSMutableArray *_switchButtons;
    NSNumber *_editingRelativeReminder;
}

@property(retain, nonatomic) NSNumber *editingRelativeReminder; // @synthesize editingRelativeReminder=_editingRelativeReminder;
@property(nonatomic) _Bool relativeReminderEditable; // @synthesize relativeReminderEditable=_relativeReminderEditable;
@property(retain, nonatomic) NSMutableArray *switchButtons; // @synthesize switchButtons=_switchButtons;
@property(retain, nonatomic) NSMutableArray *relativeReminders; // @synthesize relativeReminders=_relativeReminders;
@property(retain, nonatomic) NSMutableArray *absoluteReminders; // @synthesize absoluteReminders=_absoluteReminders;
@property(retain, nonatomic) NSMutableArray *reminders; // @synthesize reminders=_reminders;
@property(retain, nonatomic) Task *task; // @synthesize task=_task;
@property(nonatomic) id <DIReminderViewControllerDelegate> controllerDelegate; // @synthesize controllerDelegate=_controllerDelegate;
- (void).cxx_destruct;
- (void)OK:(id)arg1;
- (void)cancel:(id)arg1;
- (void)addAbsoluteReminder:(id)arg1;
- (void)switchReminder:(id)arg1;
- (void)relativeReminderCell:(id)arg1 didChangeToInterval:(id)arg2;
- (void)scheduledViewController:(id)arg1 didSelectDate:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initSwitchButtons;
- (void)initRelativeReminders;
- (void)initAbsoluteReminders;
- (void)setNavigationBarStyle;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

