//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIRepeatPolicy.h"

@interface DIRepeatYearlyPolicy : DIRepeatPolicy
{
    long long _monthOfYear;
    long long _dayOfMonth;
}

@property(nonatomic) long long dayOfMonth; // @synthesize dayOfMonth=_dayOfMonth;
@property(nonatomic) long long monthOfYear; // @synthesize monthOfYear=_monthOfYear;
- (id)description;

@end

