//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "DIGrowingTextViewDelegate.h"

@class DIGrowingTextView, NSString, UIButton;

@interface DISubTaskEditCell : UITableViewCell <DIGrowingTextViewDelegate>
{
    UIButton *_checkBox;
    DIGrowingTextView *_subTaskTextView;
    id <DISubTaskEditCellDelegate> _delegate;
}

+ (double)cellHeightForSubTask:(id)arg1 cellWidth:(double)arg2 isEditing:(_Bool)arg3;
+ (id)subTaskTextView;
+ (id)completedSubtaskTitleAttributs;
+ (id)subtaskTitleAttributs;
@property(nonatomic) __weak id <DISubTaskEditCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)growingTextViewDidChange:(id)arg1;
- (void)growingTextView:(id)arg1 didChangeHeightTo:(float)arg2;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (_Bool)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextViewDidBeginEditing:(id)arg1;
- (_Bool)growingTextViewShouldBeginEditing:(id)arg1;
- (void)on_delete:(id)arg1;
- (void)on_checkBox:(id)arg1;
- (void)reloadSubTask:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

