//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DISubtaskCell, SubTask;

@protocol DISubtaskCellDelegate <NSObject>

@optional
- (void)subtaskCell:(DISubtaskCell *)arg1 deleteSubtask:(SubTask *)arg2;
- (void)subtaskCell:(DISubtaskCell *)arg1 completeSubtask:(SubTask *)arg2;
- (void)subtaskCell:(DISubtaskCell *)arg1 didEndEditSubtask:(SubTask *)arg2;
- (void)subtaskCell:(DISubtaskCell *)arg1 didChangeHeight:(float)arg2;
- (void)subtaskCell:(DISubtaskCell *)arg1 didBeginEditSubtask:(SubTask *)arg2;
- (_Bool)subtaskCell:(DISubtaskCell *)arg1 shouldBeginEditSubtask:(SubTask *)arg2;
@end

