//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SITableViewCell.h"

#import "DIGrowingTextViewDelegate.h"

@class DIGrowingTextView, NSString, SubTask, UIButton;

@interface DISubtaskCell : SITableViewCell <DIGrowingTextViewDelegate>
{
    _Bool _newSubtask;
    float _maxHeightInEditing;
    id <DISubtaskCellDelegate> _cellDelegate;
    SubTask *_subtask;
    UIButton *_checkBox;
    DIGrowingTextView *_titleTextView;
}

+ (float)heightOfSubtask:(id)arg1 withCellWidth:(float)arg2;
+ (id)completedSubtaskTitleAttributs;
+ (id)subtaskTitleAttributs;
+ (id)reuseIdentifier;
@property(retain, nonatomic) DIGrowingTextView *titleTextView; // @synthesize titleTextView=_titleTextView;
@property(retain, nonatomic) UIButton *checkBox; // @synthesize checkBox=_checkBox;
@property(nonatomic) float maxHeightInEditing; // @synthesize maxHeightInEditing=_maxHeightInEditing;
@property(nonatomic) _Bool newSubtask; // @synthesize newSubtask=_newSubtask;
@property(retain, nonatomic) SubTask *subtask; // @synthesize subtask=_subtask;
@property(nonatomic) id <DISubtaskCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void).cxx_destruct;
- (void)delete:(id)arg1;
- (void)checkBoxClicked:(id)arg1;
- (void)growingTextView:(id)arg1 didChangeHeightTo:(float)arg2;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (_Bool)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextViewDidBeginEditing:(id)arg1;
- (_Bool)growingTextViewShouldBeginEditing:(id)arg1;
- (void)hideKeyboard:(id)arg1;
- (_Bool)isFirstResponder;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

