//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DISyncResult : NSObject
{
    _Bool _tasksUpdated;
    _Bool _projectsUpdated;
    _Bool _contextsUpdated;
    _Bool _goalsUpdated;
    _Bool _subTasksUpdated;
    _Bool _boxesUpdated;
    _Bool _filtersUpdated;
    _Bool _contactsUpdated;
    _Bool _tagsUpdated;
    _Bool _commentsUpdated;
    _Bool _noticesUpdated;
    _Bool _guideTipUpdated;
    _Bool _dailyReviewUpdated;
    _Bool _hasExceptionLog;
    long long _statusCode;
    unsigned long long _maxUsn;
}

+ (id)syncResultWithCode:(long long)arg1;
@property(nonatomic) _Bool hasExceptionLog; // @synthesize hasExceptionLog=_hasExceptionLog;
@property(nonatomic) _Bool dailyReviewUpdated; // @synthesize dailyReviewUpdated=_dailyReviewUpdated;
@property(nonatomic) _Bool guideTipUpdated; // @synthesize guideTipUpdated=_guideTipUpdated;
@property(nonatomic) _Bool noticesUpdated; // @synthesize noticesUpdated=_noticesUpdated;
@property(nonatomic) _Bool commentsUpdated; // @synthesize commentsUpdated=_commentsUpdated;
@property(nonatomic) _Bool tagsUpdated; // @synthesize tagsUpdated=_tagsUpdated;
@property(nonatomic) _Bool contactsUpdated; // @synthesize contactsUpdated=_contactsUpdated;
@property(nonatomic) _Bool filtersUpdated; // @synthesize filtersUpdated=_filtersUpdated;
@property(nonatomic) _Bool boxesUpdated; // @synthesize boxesUpdated=_boxesUpdated;
@property(nonatomic) _Bool subTasksUpdated; // @synthesize subTasksUpdated=_subTasksUpdated;
@property(nonatomic) _Bool goalsUpdated; // @synthesize goalsUpdated=_goalsUpdated;
@property(nonatomic) _Bool contextsUpdated; // @synthesize contextsUpdated=_contextsUpdated;
@property(nonatomic) _Bool projectsUpdated; // @synthesize projectsUpdated=_projectsUpdated;
@property(nonatomic) _Bool tasksUpdated; // @synthesize tasksUpdated=_tasksUpdated;
@property(nonatomic) unsigned long long maxUsn; // @synthesize maxUsn=_maxUsn;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
- (id)description;
- (void)reset;
- (_Bool)hasUpdateFromSync;

@end

