//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DIUserAccountObserver.h"
#import "UIAlertViewDelegate.h"

@class NSMutableArray, NSString;

@interface DITaskRemindersManager : NSObject <UIAlertViewDelegate, DIUserAccountObserver>
{
    int _nQueuedReminders;
    NSMutableArray *_snoozeScheduleInfos;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)userAccountAttributeHasChanged:(id)arg1 keyPath:(id)arg2;
- (void)p_scheduleDailyReviewReminder;
- (void)p_scheduleDailyPlanReminder;
- (void)p_addDailyReviewReminderSinceToday:(unsigned long long)arg1;
- (void)p_addDailyReviewReminderAtDate:(id)arg1;
- (void)p_addDailyPlanReminderSinceToday:(unsigned long long)arg1;
- (void)p_addDailyPlanReminderAtDate:(id)arg1;
- (id)p_localNotificationWithAlertBody:(id)arg1 alertAction:(id)arg2 fireDate:(id)arg3;
- (int)p_min:(id)arg1;
- (int)p_hour:(id)arg1;
- (void)p_cancelReminder:(int)arg1;
- (void)addReminderType:(int)arg1 atDate:(id)arg2;
- (void)cancelReminderType:(int)arg1 atDay:(id)arg2;
- (void)checkDailyReviewReminder;
- (void)checkDailyPlanReminder;
- (void)p_removeSnoozeReminderWithTaskID:(id)arg1 repeatNO:(id)arg2;
- (void)p_scheduleSnoozeTaskReminders;
- (void)snoozeTask:(id)arg1 fireDate:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showReminderAlertWhileActive:(id)arg1 alertBody:(id)arg2;
- (void)handleReminderNotification:(id)arg1;
- (void)reminderOnce;
- (void)updateReminders;
- (void)cancelSingle:(id)arg1;
- (void)updateSingle:(id)arg1;
- (void)scheduleSingle:(id)arg1;
- (void)scheduleReminers:(id)arg1;
- (id)scheduleInfo2LocalNotif:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

