//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "DIGrowingTextViewDelegate.h"

@class DIGrowingTextView, NSString, Task, UIButton;

@interface DITaskTitleDescCell : UITableViewCell <DIGrowingTextViewDelegate>
{
    UIButton *_checkBoxButton;
    UIButton *_hideKeyboardButton;
    DIGrowingTextView *_titleTextView;
    DIGrowingTextView *_descTextView;
    id <DITaskTitleDescCellDelegate> _delegate;
    Task *_task;
}

+ (double)cellHeightForTask:(id)arg1 cellWidth:(double)arg2;
+ (id)descTextView;
+ (id)titleTextView;
+ (double)p_textViewLeftPadding:(id)arg1;
@property(retain, nonatomic) Task *task; // @synthesize task=_task;
@property(nonatomic) __weak id <DITaskTitleDescCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) DIGrowingTextView *titleTextView; // @synthesize titleTextView=_titleTextView;
- (void).cxx_destruct;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (void)growingTextViewDidChange:(id)arg1;
- (_Bool)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextView:(id)arg1 didChangeHeightTo:(float)arg2;
- (void)on_hideKeyboard:(id)arg1;
- (void)on_CheckBox:(id)arg1;
- (void)reloadTask:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

