//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskInfoSection.h"

#import "DIAddNewSubTaskCellDelegate.h"
#import "DIEvernoteViewCellDelegate.h"
#import "DISubTaskEditCellDelegate.h"
#import "DITaskTitleDescCellDelegate.h"

@class DITaskAssignCard, NSMutableArray, NSString, SubTask, UITableView;

@interface DITaskMainInfoSection : DITaskInfoSection <DITaskTitleDescCellDelegate, DISubTaskEditCellDelegate, DIAddNewSubTaskCellDelegate, DIEvernoteViewCellDelegate>
{
    NSMutableArray *_subTasks;
    DITaskAssignCard *_assignCard;
    _Bool _isDataDirty;
    id <DITaskMainInfoSectionDelegate> _delegate;
    UITableView *_tableView;
    SubTask *_editingSubTask;
    NSString *_subTaskTitleBeforeEditing;
    NSMutableArray *_deleteSubTasks;
    NSString *_addSubTaskTitle;
    NSString *_taskTitleBeforeEditing;
}

@property(copy, nonatomic) NSString *taskTitleBeforeEditing; // @synthesize taskTitleBeforeEditing=_taskTitleBeforeEditing;
@property(copy, nonatomic) NSString *addSubTaskTitle; // @synthesize addSubTaskTitle=_addSubTaskTitle;
@property(retain, nonatomic) NSMutableArray *deleteSubTasks; // @synthesize deleteSubTasks=_deleteSubTasks;
@property(copy, nonatomic) NSString *subTaskTitleBeforeEditing; // @synthesize subTaskTitleBeforeEditing=_subTaskTitleBeforeEditing;
@property(retain, nonatomic) SubTask *editingSubTask; // @synthesize editingSubTask=_editingSubTask;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isDataDirty; // @synthesize isDataDirty=_isDataDirty;
@property(nonatomic) __weak id <DITaskMainInfoSectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)p_isSubTaskEditable;
- (long long)p_indexOfAddSubTaskCell;
- (long long)p_indexOfSubTaskCell;
- (long long)p_indexOfEvernoteCell;
- (long long)p_indexOfTitle;
- (void)evernoteViewCell:(id)arg1 pressedDeleteOnIndex:(long long)arg2;
- (void)evernoteViewCell:(id)arg1 pressedOnIndex:(long long)arg2;
- (void)evernoteViewCellPressedOnAdd:(id)arg1;
- (void)addNewSubTaskCell:(id)arg1 didChangeBounds:(id)arg2;
- (void)addNewSubTaskCell:(id)arg1 didEndEditing:(id)arg2;
- (void)addNewSubTaskCell:(id)arg1 didReturn:(id)arg2;
- (_Bool)addNewSubTaskCell:(id)arg1 shouldBeginEdit:(id)arg2;
- (void)subTaskEditCell:(id)arg1 didChangeBounds:(id)arg2;
- (void)subTaskEditCell:(id)arg1 didEndEditing:(id)arg2;
- (void)subTaskEditCell:(id)arg1 didChange:(id)arg2;
- (void)subTaskEditCell:(id)arg1 didReturn:(id)arg2;
- (void)subTaskEditCell:(id)arg1 didBeginEditing:(id)arg2;
- (_Bool)subTaskEditCellShouldBeginEditing:(id)arg1;
- (void)subTaskEditCell:(id)arg1 pressedOnDelete:(id)arg2;
- (void)subTaskEditCell:(id)arg1 pressedOnCheckBox:(id)arg2;
- (void)taskTitleDescCell:(id)arg1 titleEndEdit:(id)arg2;
- (void)taskTitleDescCell:(id)arg1 titleChanged:(id)arg2;
- (void)taskTitleDescCell:(id)arg1 descChanged:(id)arg2;
- (void)taskTitleDescCellTextViewBoundsChange:(id)arg1;
- (void)taskTitleDescCell:(id)arg1 pressedOnCheckBox:(id)arg2;
- (id)titleView;
- (id)sectionHeaderInTableView:(id)arg1;
- (double)sectionHeaderHeightInTableView:(id)arg1;
- (long long)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndex:(long long)arg2 toProposedIndex:(long long)arg3;
- (void)tableView:(id)arg1 moveRowAtIndex:(long long)arg2 toIndex:(long long)arg3;
- (_Bool)tableView:(id)arg1 canMoveRow:(long long)arg2;
- (id)tableView:(id)arg1 cellForRow:(long long)arg2;
- (double)tableView:(id)arg1 heightForRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)registerInTableView:(id)arg1;
- (void)cleanDataDirty;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setTask:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

