//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

@class DITaskCommentSection, NSMutableArray, Task, UITableView, UITextView, UIView;

@interface DITaskDetailViewController : SIViewController
{
    NSMutableArray *_infoSections;
    UITableView *_tableView;
    UIView *_editMoreView;
    struct {
        unsigned int isMainInfoVisible:1;
        unsigned int isPriorityVisible:1;
        unsigned int isTimeVisible:1;
        unsigned int isOrganizerVisible:1;
        unsigned int isRepeaterReminderVisible:1;
        unsigned int isEditMoreVisible:1;
        unsigned int isCommentVisible:1;
    } _sectionsVisible;
    DITaskCommentSection *_commentSection;
    _Bool _needsLayout;
    _Bool _autoSave;
    _Bool _titleBecomeFirstResponderWhenEmpty;
    Task *_task;
    UITextView *_editingView;
    struct CGRect _editingViewBounds;
}

@property(nonatomic) struct CGRect editingViewBounds; // @synthesize editingViewBounds=_editingViewBounds;
@property(retain, nonatomic) UITextView *editingView; // @synthesize editingView=_editingView;
@property(nonatomic) _Bool titleBecomeFirstResponderWhenEmpty; // @synthesize titleBecomeFirstResponderWhenEmpty=_titleBecomeFirstResponderWhenEmpty;
@property(retain, nonatomic) Task *task; // @synthesize task=_task;
@property(nonatomic) _Bool autoSave; // @synthesize autoSave=_autoSave;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)setNeedsLayout;
- (void)addTaskComment:(id)arg1;
- (void)saveAnyChanges;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)didReceiveMemoryWarning;
- (void)viewWillLayoutSubviews;
- (void)dealloc;
- (void)viewDidUnload;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)setView:(id)arg1;
- (id)initWithTask:(id)arg1;
- (void)setParent:(id)arg1;

@end

