//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DIGrowingTextView, DITaskTitleDescCell, NSString, UIButton;

@protocol DITaskTitleDescCellDelegate <NSObject>
- (void)taskTitleDescCellTextViewBoundsChange:(DITaskTitleDescCell *)arg1;
- (void)taskTitleDescCell:(DITaskTitleDescCell *)arg1 titleEndEdit:(DIGrowingTextView *)arg2;
- (void)taskTitleDescCell:(DITaskTitleDescCell *)arg1 descChanged:(NSString *)arg2;
- (void)taskTitleDescCell:(DITaskTitleDescCell *)arg1 titleChanged:(NSString *)arg2;
- (void)taskTitleDescCell:(DITaskTitleDescCell *)arg1 pressedOnCheckBox:(UIButton *)arg2;
@end

