//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskSendToViewController.h"

@interface DITaskSendToViewController (Actions)
- (void)on_keyboardWillHide:(id)arg1;
- (void)on_keyboardWillShow:(id)arg1;
- (void)on_searchTextChanged:(id)arg1;
@end

