//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskInfoSection.h"

#import "DIReminderViewControllerDelegate.h"

@class NSString, UITableView;

@interface DITaskRepeatRemindSection : DITaskInfoSection <DIReminderViewControllerDelegate>
{
    struct {
        unsigned int isRepeatShown:1;
        unsigned int isRemindShown:1;
    } _shownFlag;
    _Bool _onlyShowExits;
    _Bool _isDataDirty;
    UITableView *_tableView;
}

+ (long long)cellCountForTask:(id)arg1;
@property(nonatomic) _Bool isDataDirty; // @synthesize isDataDirty=_isDataDirty;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool onlyShowExits; // @synthesize onlyShowExits=_onlyShowExits;
- (void).cxx_destruct;
- (void)p_selectOnRepeaterInController:(id)arg1;
- (void)p_repeater_selectOnYearly:(id)arg1;
- (void)p_repeater_selectOnMonthly:(id)arg1;
- (void)p_repeater_selectOnWeekly:(id)arg1;
- (void)p_repeater_selectOnDaily:(id)arg1;
- (void)p_repeater_setTaskRepeater:(id)arg1;
- (void)p_selectOnReminderInController:(id)arg1;
- (void)p_reloadReminderRow;
- (void)p_reloadRepeaterRow;
- (long long)p_indexOfReminder;
- (long long)p_indexOfRepeater;
- (void)reminderController:(id)arg1 didAddReminders:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)tableView:(id)arg1 didSelectRow:(long long)arg2 inController:(id)arg3;
- (_Bool)tableView:(id)arg1 shouldHighlightRow:(long long)arg2;
- (id)tableView:(id)arg1 cellForRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRow:(long long)arg2;
- (void)registerInTableView:(id)arg1;
- (void)cleanDataDirty;
- (void)setTask:(id)arg1;
- (void)dealloc;
- (_Bool)willEveryRowShow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

