//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskDetailViewController.h"

@interface DITaskDetailViewController (Private)
- (void)p_scroll2View:(id)arg1;
- (void)p_loadOverViewInfoSections;
- (void)p_initEditMoreView;
- (void)p_resetSections;
@end

