//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DITaskGroupProtocol.h"

@class NSArray, NSMutableArray, NSString;

@interface DITaskGroup : NSObject <DITaskGroupProtocol>
{
    NSMutableArray *_tasks;
    NSString *_groupName;
    CDUnknownBlockType _taskValidBlock;
    CDUnknownBlockType _taskComparisonBlock;
    NSArray *_sortDescriptors;
}

+ (id)nightGroup;
+ (id)afternoonGroup;
+ (id)morningGroup;
+ (id)beforeTodayGroup;
+ (id)allDayGroup;
+ (id)defaultGroup;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(copy, nonatomic) CDUnknownBlockType taskComparisonBlock; // @synthesize taskComparisonBlock=_taskComparisonBlock;
@property(copy, nonatomic) CDUnknownBlockType taskValidBlock; // @synthesize taskValidBlock=_taskValidBlock;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(retain, nonatomic) NSMutableArray *tasks; // @synthesize tasks=_tasks;
- (void).cxx_destruct;
- (_Bool)sort;
- (_Bool)addTask:(id)arg1;
- (_Bool)removeTask:(id)arg1;
- (_Bool)addTasks:(id)arg1;
- (_Bool)isTaskValid:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

