//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITabPageViewController.h"

@interface DITabPageViewController (Private)
- (long long)p_totalPage;
- (long long)p_indexOfviewController:(id)arg1;
- (id)p_viewControllerAtIndex:(long long)arg1;
@end

