//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Contact, DITaskSendToViewController;

@protocol DITaskSendToViewControllerDelegate <NSObject>
- (void)sendToController:(DITaskSendToViewController *)arg1 didSelectContact:(Contact *)arg2 autoCompleted:(_Bool)arg3;
@end

