//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DITableSectionInfo : NSObject
{
    _Bool open;
}

+ (id)sectionInfoWithStatus:(_Bool)arg1;
@property(nonatomic) _Bool open; // @synthesize open;

@end

