//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, UIButton, UILabel;

@interface DITimePicker : UIView
{
    id <DITimePickerDelegate> _pickderDelegate;
    NSDate *_date;
    UIView *_containView;
    UIButton *_prevHour;
    UIButton *_nextHour;
    UIButton *_prevMinute;
    UIButton *_nextMinute;
    UIButton *_ampm;
    UILabel *_timeLabel;
    long long _hour;
    long long _minute;
}

@property(nonatomic) long long minute; // @synthesize minute=_minute;
@property(nonatomic) long long hour; // @synthesize hour=_hour;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIButton *ampm; // @synthesize ampm=_ampm;
@property(retain, nonatomic) UIButton *nextMinute; // @synthesize nextMinute=_nextMinute;
@property(retain, nonatomic) UIButton *prevMinute; // @synthesize prevMinute=_prevMinute;
@property(retain, nonatomic) UIButton *nextHour; // @synthesize nextHour=_nextHour;
@property(retain, nonatomic) UIButton *prevHour; // @synthesize prevHour=_prevHour;
@property(retain, nonatomic) UIView *containView; // @synthesize containView=_containView;
@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) id <DITimePickerDelegate> pickderDelegate; // @synthesize pickderDelegate=_pickderDelegate;
- (void).cxx_destruct;
- (void)ampm:(id)arg1;
- (void)nextMinute:(id)arg1;
- (void)prevMinute:(id)arg1;
- (void)nextHour:(id)arg1;
- (void)preHour:(id)arg1;
- (void)loadTimeLabel;
- (void)loadButtons;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

