//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIUtils : NSObject
{
}

+ (id)helpDeskURL;
+ (id)dateFromStringWithHHmmFormat:(id)arg1;
+ (id)performanceFromReviewingItems:(id)arg1 atDate:(id)arg2;
+ (id)loadReviewingItemsAtToday;
+ (id)performanceDateString:(id)arg1;
+ (long long)durationOfDailyWork;
+ (void)setInboxFilled;
+ (void)setInboxEmpty;
+ (id)moveDueTasksToToday;
+ (long long)compareAppVersion:(id)arg1 toAnother:(id)arg2;
+ (id)startAtAndEndAtClause:(id)arg1 condition:(id)arg2;
+ (id)checkTimeZoneConsistent;
+ (id)limitsValidateDescription:(id)arg1;
+ (id)limitsValidateTitle:(id)arg1;
+ (id)formatCommetsForNotes:(id)arg1;
+ (id)getAvailableFilters:(id)arg1;
+ (id)emptyMessageForList:(int)arg1 andBox:(int)arg2;
+ (id)emptyTitleForList:(int)arg1 andBox:(int)arg2 everHasTask:(_Bool)arg3;
+ (id)formatDateWithDISettings:(id)arg1 allday:(_Bool)arg2;
+ (id)formatTimeInfoOfGoal:(id)arg1;
+ (id)formatTimeInfoOfProject:(id)arg1 inBox:(int)arg2;
+ (id)formatTimeInfoOfTask:(id)arg1 inBox:(int)arg2;
+ (id)formatEndDate:(id)arg1 withColor:(id *)arg2;
+ (id)formatStartDate:(id)arg1 withAllDay:(_Bool)arg2 withBoxType:(int)arg3 withGroup:(id)arg4 withColor:(id *)arg5 hasAssignment:(_Bool)arg6;
+ (id)formatProjectTimeInfo4PropertyViewOnPad:(id)arg1;
+ (id)formatTaskTimeInfo4PropertyViewOnPad:(id)arg1;
+ (id)formatEndAt:(id)arg1 allday:(_Bool)arg2;
+ (id)formatStartAt:(id)arg1 allday:(_Bool)arg2;
+ (id)formatStartEnd:(id)arg1;
+ (id)formatRepeater:(id)arg1 withEndsOn:(_Bool)arg2;
+ (id)setWeekdayByDay:(id)arg1 andDate:(id)arg2;
+ (long long)getDayOfMonthByWeek:(long long)arg1 weekday:(long long)arg2 andRefDate:(id)arg3;
+ (long long)getDayByWeek:(id)arg1 andDate:(id)arg2;
+ (id)doitDayOrdinalFormatter:(long long)arg1;
+ (id)computeReminderTime:(id)arg1 andAddIntervalMinute:(long long)arg2;
+ (id)computeDeadline:(id)arg1;
+ (id)computeStartTime:(id)arg1;
+ (void)moveProject:(id)arg1 toNonScheduledBox:(int)arg2;
+ (void)moveTask:(id)arg1 toNonScheduledBox:(int)arg2;

@end

