//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "DIScheduledViewControllerDelegate.h"

@class NSString, RepeaterV4, Task, UIButton, UILabel, UIScrollView;

@interface DIYearlyRepeaterViewController : SIViewController <DIScheduledViewControllerDelegate>
{
    Task *_task;
    CDUnknownBlockType _repeaterEditCompletion;
    id <DIYearlyRepeaterViewControllerDelegate> _controllerDelegate;
    UILabel *_everyTextLabel;
    UILabel *_yearTextLabel;
    UILabel *_yearLabel;
    UIButton *_next;
    UIButton *_prev;
    UIButton *_until;
    UIButton *_clearUntil;
    RepeaterV4 *_repeater;
    long long _maxDayOfMonth;
    UIScrollView *_contentView;
}

@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long maxDayOfMonth; // @synthesize maxDayOfMonth=_maxDayOfMonth;
@property(retain, nonatomic) RepeaterV4 *repeater; // @synthesize repeater=_repeater;
@property(retain, nonatomic) UIButton *clearUntil; // @synthesize clearUntil=_clearUntil;
@property(retain, nonatomic) UIButton *until; // @synthesize until=_until;
@property(retain, nonatomic) UIButton *prev; // @synthesize prev=_prev;
@property(retain, nonatomic) UIButton *next; // @synthesize next=_next;
@property(retain, nonatomic) UILabel *yearLabel; // @synthesize yearLabel=_yearLabel;
@property(retain, nonatomic) UILabel *yearTextLabel; // @synthesize yearTextLabel=_yearTextLabel;
@property(retain, nonatomic) UILabel *everyTextLabel; // @synthesize everyTextLabel=_everyTextLabel;
@property(nonatomic) id <DIYearlyRepeaterViewControllerDelegate> controllerDelegate; // @synthesize controllerDelegate=_controllerDelegate;
@property(copy, nonatomic) CDUnknownBlockType repeaterEditCompletion; // @synthesize repeaterEditCompletion=_repeaterEditCompletion;
@property(retain, nonatomic) Task *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (void)scheduledViewController:(id)arg1 didSelectDate:(id)arg2;
- (void)OK:(id)arg1;
- (void)clearUntil:(id)arg1;
- (void)until:(id)arg1;
- (void)prev:(id)arg1;
- (void)next:(id)arg1;
- (void)loadButtons;
- (void)loadLabels;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

