//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView;

@interface ENNotebookPickerButton : UIButton
{
    _Bool _isBusinessNotebook;
    _Bool _shouldHideDisclosureIndicator;
    UIImageView *_discloureIndicator;
}

@property(retain, nonatomic) UIImageView *discloureIndicator; // @synthesize discloureIndicator=_discloureIndicator;
@property(nonatomic) _Bool shouldHideDisclosureIndicator; // @synthesize shouldHideDisclosureIndicator=_shouldHideDisclosureIndicator;
@property(nonatomic) _Bool isBusinessNotebook; // @synthesize isBusinessNotebook=_isBusinessNotebook;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

