//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface ENStoreClient : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
}

+ (long long)sanitizedErrorCodeFromEDAMErrorCode:(int)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)handleException:(id)arg1 withFailureBlock:(CDUnknownBlockType)arg2;
- (id)errorFromException:(id)arg1;
- (void)invokeAsyncVoidBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncIdBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncInt32Block:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncBoolBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)init;

@end

