//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSException.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface FATException : NSException <NSCoding, NSCopying>
{
}

+ (id)structFields;
+ (id)structName;
+ (void)initialize;
- (id)init;

@end

