//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIObject.h"

@class NSArray, NSDate, NSString;

@interface Notice : DIObject
{
    _Bool _forcePopup;
    _Bool _poppedup;
    _Bool _targetLost;
    NSString *_title;
    NSString *_body;
    NSString *_type;
    NSDate *_read;
    NSString *_senderId;
    NSString *_senderMail;
    NSString *_senderNickname;
    NSString *_commentId;
    NSString *_targetId;
    NSString *_taskRepeatno;
    NSString *_result;
    NSString *_bodyTitle;
    NSString *_bodySection;
    NSArray *_bodyContents;
}

@property(nonatomic, getter=isTargetLost) _Bool targetLost; // @synthesize targetLost=_targetLost;
@property(copy, nonatomic) NSArray *bodyContents; // @synthesize bodyContents=_bodyContents;
@property(copy, nonatomic) NSString *bodySection; // @synthesize bodySection=_bodySection;
@property(copy, nonatomic) NSString *bodyTitle; // @synthesize bodyTitle=_bodyTitle;
@property(nonatomic) _Bool poppedup; // @synthesize poppedup=_poppedup;
@property(copy, nonatomic) NSString *result; // @synthesize result=_result;
@property(copy, nonatomic) NSString *taskRepeatno; // @synthesize taskRepeatno=_taskRepeatno;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(copy, nonatomic) NSString *commentId; // @synthesize commentId=_commentId;
@property(copy, nonatomic) NSString *senderNickname; // @synthesize senderNickname=_senderNickname;
@property(copy, nonatomic) NSString *senderMail; // @synthesize senderMail=_senderMail;
@property(copy, nonatomic) NSString *senderId; // @synthesize senderId=_senderId;
@property(nonatomic) _Bool forcePopup; // @synthesize forcePopup=_forcePopup;
@property(copy, nonatomic) NSDate *read; // @synthesize read=_read;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)description;
- (id)jsonStringForContents:(id)arg1;
- (id)bodyContentByType:(id)arg1 targetId:(id)arg2;
- (id)bodySectionByType:(id)arg1 commentId:(id)arg2;
- (id)bodyTitleByType:(id)arg1 targetId:(id)arg2 repeatNo:(id)arg3;
- (id)senderEmail:(id)arg1;
- (id)senderNickname:(id)arg1;
- (id)toDictionary;
- (id)initWithDictionay:(id)arg1;
- (id)unescape:(id)arg1;
- (_Bool)isType:(id)arg1;
- (_Bool)isNotice;

@end

