//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (SOExtendedStringDrawing)
- (struct CGSize)multiLineSizeWithSize:(struct CGSize)arg1 attributes:(id)arg2;
- (struct CGRect)multiLineBoundingRectWithSize:(struct CGSize)arg1 attributes:(id)arg2;
- (void)multiLineDrawWithRect:(struct CGRect)arg1 attributes:(id)arg2;
@end

