//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface SIViewController : UIViewController
{
    _Bool _isModal;
    id _parent;
}

@property(nonatomic) __weak id parent; // @synthesize parent=_parent;
@property(nonatomic) _Bool isModal; // @synthesize isModal=_isModal;
- (void).cxx_destruct;
- (void)presentModalNavigactionControllerWith:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)disablesAutomaticKeyboardDismissal;
- (void)resizeWithSize:(struct CGSize)arg1;
- (struct CGSize)contentSize;
- (void)forcePopoverSize;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

