//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

#import "UIAlertViewDelegate.h"

@class NSDictionary, NSString;

@interface SOAlertView : UIAlertView <UIAlertViewDelegate>
{
    id _alertDelegate;
    long long _modalReturnCode;
    _Bool _isModal;
    NSDictionary *_userData;
}

@property(retain, nonatomic) NSDictionary *userData; // @synthesize userData=_userData;
- (void).cxx_destruct;
- (long long)showModal;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

