//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SOObject : NSObject
{
    _Bool _editable;
}

@property(nonatomic, getter=isEditable) _Bool editable; // @synthesize editable=_editable;

@end

