//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface StartTimeValue : NSObject
{
    _Bool _allDay;
    NSDate *_date;
    long long _attrORstatus;
}

+ (id)timeOfProject:(id)arg1 ifMovetoBox:(int)arg2;
+ (id)timeOfTask:(id)arg1 ifMovetoBox:(int)arg2;
+ (id)timeValueOfProject:(id)arg1;
+ (id)timeValueOfTask:(id)arg1;
+ (id)timeValueOfObject:(id)arg1;
+ (id)timeValue;
@property(nonatomic) long long attrORstatus; // @synthesize attrORstatus=_attrORstatus;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) _Bool allDay; // @synthesize allDay=_allDay;
- (void).cxx_destruct;
- (void)applyToProject:(id)arg1;
- (void)applyToTask:(id)arg1;
- (void)applyToObject:(id)arg1;

@end

