//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class DISmartAddActivityIndicator;

@interface UIScrollView (UzysInteractiveIndicator)
@property(nonatomic) _Bool showPullToRefresh; // @dynamic showPullToRefresh;
@property(readonly, nonatomic) DISmartAddActivityIndicator *pullToRefreshView; // @dynamic pullToRefreshView;
- (void)setPullToRefreshView:(id)arg1;
- (void)stopRefreshAnimation;
- (void)addSmartAddActionHandler:(CDUnknownBlockType)arg1;
@end

