//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "DIScheduledViewControllerDelegate.h"
#import "DISelectionViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class DIScheduledViewController, DISelectionViewController, NSMutableArray, NSString, UITableView;

@interface DIAccountViewController : SIViewController <UITableViewDataSource, UITableViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIActionSheetDelegate, DISelectionViewControllerDelegate, DIScheduledViewControllerDelegate>
{
    UITableView *_tableView;
    NSMutableArray *_rowTags;
    NSMutableArray *_rowNumberInSections;
    DISelectionViewController *_selectionController;
    DIScheduledViewController *_schedulePicker;
}

@property(retain, nonatomic) DIScheduledViewController *schedulePicker; // @synthesize schedulePicker=_schedulePicker;
@property(retain, nonatomic) DISelectionViewController *selectionController; // @synthesize selectionController=_selectionController;
@property(retain, nonatomic) NSMutableArray *rowNumberInSections; // @synthesize rowNumberInSections=_rowNumberInSections;
@property(retain, nonatomic) NSMutableArray *rowTags; // @synthesize rowTags=_rowTags;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)scheduledViewController:(id)arg1 didSelectDate:(id)arg2;
- (void)selection:(id)arg1 didSelectItemWithTitle:(id)arg2 atIndex:(long long)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)logout;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingImage:(id)arg2 editingInfo:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)showGenderSelection;
- (void)showLogoutAlertView;
- (id)cellOfLogout;
- (id)cellOfUpgradeToPro;
- (id)cellOfRenew;
- (id)cellOfProExipres;
- (id)cellOfServer;
- (id)cellOfEmail;
- (id)cellOfUsername;
- (id)cellOfBirthday;
- (id)cellOfGender;
- (id)cellOfNickname;
- (id)cellOfPhoto;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadSectionInfos;
- (id)indexPathOfRowTag:(id)arg1;
- (id)tagForRowAtIndexPath:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

