//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol DIBottomToolBarDelegate <NSObject>

@optional
- (void)pickPriority:(id)arg1;
- (void)pickGoal:(id)arg1;
- (void)pickContext:(id)arg1;
- (void)pickProject:(id)arg1;
- (void)unsetDoitNow:(id)arg1;
- (void)setDoitNow:(id)arg1;
- (void)deactivateProject:(id)arg1;
- (void)activateProject:(id)arg1;
- (void)convertToProject:(id)arg1;
- (void)moveItem:(id)arg1;
- (void)unTrashItem:(id)arg1;
- (void)trashItem:(id)arg1;
- (void)bottomToolbarDidChangeHeight:(double)arg1;
@end

