//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DIWidgetDataProtocol.h"

@class NSString;

@interface DIBoxWidgetData : NSObject <DIWidgetDataProtocol>
{
    NSString *_title;
    unsigned long long _taskCount;
    unsigned long long _boxType;
}

@property(nonatomic) unsigned long long boxType; // @synthesize boxType=_boxType;
@property(nonatomic) unsigned long long taskCount; // @synthesize taskCount=_taskCount;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
- (void)updateWithDictionary:(id)arg1;
- (id)dictionary;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

