//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIContactListController.h"

@interface DIContactListController (Action)
- (void)on_personProfile;
- (void)on_showTaskList;
- (void)on_sendTask;
@end

