//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SITableViewCell.h"

@class Context, UILabel;

@interface DIContextCell : SITableViewCell
{
    Context *_context;
    UILabel *_titlelabel;
    double _titleMaxWidth;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (void)layoutSubviews;
- (void)resetTitleLabel;
- (void)setContext:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

