//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITabPageViewController.h"

#import "DICommentEditorViewControllerDelegate.h"
#import "DIDailyPlanTabBarDelegate.h"
#import "DIEvaluateControllerDelegate.h"
#import "DITaskSendToViewControllerDelegate.h"

@class DIEvaluateController, NSDate, NSMutableArray, NSString, Task, UIBarButtonItem;

@interface DIDailyReviewController : DITabPageViewController <DITaskSendToViewControllerDelegate, DICommentEditorViewControllerDelegate, DIDailyPlanTabBarDelegate, DIEvaluateControllerDelegate>
{
    Task *_currentTask;
    UIBarButtonItem *_saveItem;
    NSMutableArray *_tasks;
    NSMutableArray *_taskDetailViewControllers;
    DIEvaluateController *_reviewEvaluateController;
    NSDate *_reviewDay;
}

@property(retain, nonatomic) NSDate *reviewDay; // @synthesize reviewDay=_reviewDay;
@property(retain, nonatomic) DIEvaluateController *reviewEvaluateController; // @synthesize reviewEvaluateController=_reviewEvaluateController;
@property(retain, nonatomic) NSMutableArray *taskDetailViewControllers; // @synthesize taskDetailViewControllers=_taskDetailViewControllers;
@property(retain, nonatomic) NSMutableArray *tasks; // @synthesize tasks=_tasks;
- (void).cxx_destruct;
- (void)evaluateController:(id)arg1 selectStarChanged:(long long)arg2;
- (void)evaluateController:(id)arg1 textChanged:(id)arg2;
- (void)dailyPlanTabBar:(id)arg1 didSelectedAtIndex:(long long)arg2;
- (void)commentController:(id)arg1 postCommentText:(id)arg2;
- (void)sendToController:(id)arg1 didSelectContact:(id)arg2 autoCompleted:(_Bool)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)showStatistics;
- (void)setIsFinalControllerShown:(_Bool)arg1;
- (void)setCurrentIndex:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithReviewOnDay:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

