//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "DICalendarMonthViewDelegate.h"

@class DICalendarMonthView, NSDate, NSString, UIView;

@interface DIDaySelectionController : SIViewController <DICalendarMonthViewDelegate>
{
    DICalendarMonthView *_calendarView;
    CDUnknownBlockType _CancelBlock;
    CDUnknownBlockType _CompletionBlock;
    UIView *_naviBarBottomSeparatorLine;
    NSDate *_selectDate;
}

@property(retain, nonatomic) NSDate *selectDate; // @synthesize selectDate=_selectDate;
@property(retain, nonatomic) UIView *naviBarBottomSeparatorLine; // @synthesize naviBarBottomSeparatorLine=_naviBarBottomSeparatorLine;
@property(copy, nonatomic) CDUnknownBlockType CompletionBlock; // @synthesize CompletionBlock=_CompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType CancelBlock; // @synthesize CancelBlock=_CancelBlock;
- (void).cxx_destruct;
- (void)calendarView:(id)arg1 didSelectDate:(id)arg2;
- (void)on_OK:(id)arg1;
- (void)on_cancel:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithDate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

