//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIDailyReviewController.h"

#import "DITabPageViewControllerDatasource.h"

@class NSString;

@interface DIDailyReviewController (DITabPageViewControllerDatasource) <DITabPageViewControllerDatasource>
- (void)tabPageViewController:(id)arg1 didFinalControllerAppear:(_Bool)arg2;
- (id)tabPageViewController:(id)arg1 controllerAtIndex:(long long)arg2;
- (long long)totalPageInTabPageViewController:(id)arg1;
- (long long)tabPageViewController:(id)arg1 indexOfController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

