//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIDBAudio : NSObject
{
}

- (long long)counOfAudioInTask:(id)arg1 repeatNo:(id)arg2;
- (id)findByTaskId:(id)arg1 repeatNo:(id)arg2;
- (id)findById:(id)arg1;
- (long long)queryIntegerValue:(id)arg1 args:(id)arg2;
- (id)queryAudios:(id)arg1 args:(id)arg2;
- (_Bool)isExist:(id)arg1;
- (_Bool)destroy:(id)arg1;
- (_Bool)save:(id)arg1 fromServer:(_Bool)arg2;
- (id)sqlParametersDictionaryOfAudio:(id)arg1 fromServer:(_Bool)arg2;

@end

