//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIDBDailyReview : NSObject
{
}

- (id)findByDateString:(id)arg1;
- (_Bool)updateUSNColumn:(unsigned long long)arg1 withIdentifier:(id)arg2;
- (_Bool)save:(id)arg1 fromServer:(_Bool)arg2;
- (id)sqlParametersDictionaryOfDailyReview:(id)arg1 fromServer:(_Bool)arg2;
- (_Bool)isExist:(id)arg1;
- (id)queryDailyReviewes:(id)arg1 args:(id)arg2;

@end

