//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIDBTask : NSObject
{
}

+ (id)findTask:(id)arg1 repeatNo:(id)arg2 inDB1_0:(id)arg3;
+ (id)findRemindersByTaskPk:(long long)arg1 inDB1_0:(id)arg2;
+ (id)findRepeaterByPk:(long long)arg1 inDB1_0:(id)arg2;
+ (id)findAssignmentByPk:(long long)arg1 inDB1_0:(id)arg2;
+ (id)findItemsByAssignment:(long long)arg1 inDB1_0:(id)arg2;
- (_Bool)updateGoalId:(id)arg1 newId:(id)arg2;
- (_Bool)updateProjectId:(id)arg1 newId:(id)arg2;
- (_Bool)updateContextId:(id)arg1 newId:(id)arg2;
- (id)findRepeatInstancesById:(id)arg1 afterDate:(id)arg2;
- (id)destroyVirtualTask:(id)arg1;
- (id)findNonRepeatTasksWithRemindersAfterTime:(id)arg1;
- (id)findBySubTaskUUID:(id)arg1;
- (id)findByIdWithoutFilter:(id)arg1 andRepeatNo:(id)arg2;
- (id)findById:(id)arg1 andRepeatNo:(id)arg2;
- (id)findRepeatTasksWithReminders;
- (long long)positionForTask:(id)arg1 repeatNo:(id)arg2;
- (id)findTasksWithPositionBetweenMin:(long long)arg1 andMax:(long long)arg2;
- (long long)maxPosition;
- (long long)countOfTasksOverdueInHours:(long long)arg1;
- (long long)countOfTaskInContext:(id)arg1;
- (long long)countOfUnCompletedTasksInGoal:(id)arg1;
- (long long)countOfArchiveTasksInProject:(id)arg1;
- (long long)countOfUncompletedTasksInProject:(id)arg1;
- (long long)countOfCompletedTaskInProject:(id)arg1;
- (long long)countOfTaskInTrashedProject:(id)arg1;
- (long long)countOfAllTasksInProject:(id)arg1;
- (long long)countOfTasksInCompletedProject:(id)arg1;
- (long long)countOfTasksInProject:(id)arg1;
- (long long)countOfTasksInSomeday;
- (long long)countOfTasksInSchedule;
- (long long)countOfTasksInNext;
- (long long)countOfDueTasksInWaiting;
- (long long)countOfTasksInWaiting;
- (long long)countOfTasksInTomorrow;
- (long long)countOfDueTasksInToday;
- (long long)countOfTasksInToday;
- (long long)countOfTasksInInbox;
- (id)findSentAtToday;
- (id)findCompletedAtToday;
- (id)findInContextById:(id)arg1;
- (id)findTrashedInGoal:(id)arg1;
- (id)findCompletedInGoal:(id)arg1;
- (id)findInGoalById:(id)arg1 withArchived:(_Bool)arg2 withCompleted:(_Bool)arg3 withTrashed:(_Bool)arg4;
- (id)findScheduledInProjectById:(id)arg1;
- (id)findUncompletedWithoutTrashed:(id)arg1;
- (id)findInProjectById:(id)arg1 withInArchived:(_Bool)arg2 withInCompleted:(_Bool)arg3 withInTrashed:(_Bool)arg4;
- (id)findInProjectById:(id)arg1;
- (id)findNextInProject:(id)arg1;
- (id)findTrashedInProject:(id)arg1;
- (id)findStartOrEndAtTodayInProject:(id)arg1;
- (id)findDueTasksInSomeday;
- (id)findDueTasksInNext;
- (id)findDueTasksInInbox;
- (id)findTaskByKey:(id)arg1;
- (id)findInFilter:(id)arg1;
- (id)findInTrashed;
- (id)findInCompleted;
- (id)findInWaiting;
- (id)findInSomeday;
- (id)findInSchedule:(id)arg1;
- (id)findInTomorrow;
- (id)findInNext;
- (id)findInToday;
- (id)findInInbox;
- (_Bool)clearTrashed;
- (_Bool)archiveCompleted;
- (_Bool)destroy:(id)arg1;
- (_Bool)save:(id)arg1;
- (_Bool)save:(id)arg1 fromServer:(_Bool)arg2;
- (id)sqlParametersDictionaryOfTask:(id)arg1 fromServer:(_Bool)arg2;
- (_Bool)updateUSNColumn:(unsigned long long)arg1 withUUID:(id)arg2 repeatNo:(id)arg3;
- (_Bool)isExisted:(id)arg1 andRepeatNo:(id)arg2;
- (id)queryTasks:(id)arg1 args:(id)arg2;
- (id)queryStringValue:(id)arg1 args:(id)arg2;
- (long long)queryIntegerValue:(id)arg1 args:(id)arg2;
- (long long)queryLonglongValue:(id)arg1 args:(id)arg2;

@end

