//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SITableViewCell.h"

@class Goal, NSMutableArray, UIButton, UIImageView, UILabel;

@interface DIGoalCell : SITableViewCell
{
    Goal *_goal;
    NSMutableArray *_bottomViewsMarginRight;
    NSMutableArray *_iconsMarginTitle;
    UIButton *_checkBox;
    UIImageView *_goalImageView;
    UILabel *_completedLabel;
    UILabel *_titlelabel;
    UIImageView *_noteView;
    double _titleMaxWidth;
    long long _groupby;
    _Bool _showGoalImageView;
    _Bool _titleAlignCenter;
    id <DIGoalCellDelegate> _cellDelegate;
}

+ (id)reuseIdentifier;
@property(nonatomic) id <DIGoalCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void).cxx_destruct;
- (void)checkBoxClicked:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setGoal:(id)arg1 boxType:(int)arg2 withGroupby:(long long)arg3;
- (void)rearrangeViews;
- (void)resetIconsMarginTitle;
- (void)resetTitleLabel;
- (void)resetViewsMarginRight;
- (void)resetNoteView;
- (void)resetCompletedLabel;
- (void)resetGoalImageView;
- (void)resetCheckBox;
- (void)awakeFromNib;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

