//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DIHttpResult : NSObject
{
    long long _status;
    NSString *_DIErrorCode;
}

@property(copy, nonatomic) NSString *DIErrorCode; // @synthesize DIErrorCode=_DIErrorCode;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)description;

@end

