//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

@class DIDNSBreaker;

@interface DIHttpClient : AFHTTPRequestOperationManager
{
    id <DIHttpClientDelegate> _delegate;
    DIDNSBreaker *_dnsBreaker;
}

+ (id)sharedInstance;
@property(retain, nonatomic) DIDNSBreaker *dnsBreaker; // @synthesize dnsBreaker=_dnsBreaker;
@property(nonatomic) id <DIHttpClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)enqueueGravatorRequest:(id)arg1;
- (void)postDidFailMessageToDelegate:(id)arg1;
- (void)postDidFinishMessageToDelegate:(id)arg1;
- (_Bool)downloadFile:(id)arg1 operation:(id)arg2 saveWithName:(id)arg3 isBlocking:(_Bool)arg4;
- (_Bool)deregisterPushForIOSDevice:(id)arg1;
- (_Bool)registerPushForIOSDevice:(id)arg1;
- (id)startRequest:(id)arg1 relativePath:(id)arg2 parameters:(id)arg3;
- (void)enqueueBlockingDIOperation:(id)arg1 method:(id)arg2 relativePath:(id)arg3 parameters:(id)arg4;
- (void)enqueueDIOperation:(id)arg1 method:(id)arg2 relativePath:(id)arg3 param:(id)arg4;
- (_Bool)enqueueUploadingDIOperation:(id)arg1 parameters:(id)arg2 data:(id)arg3 relativePath:(id)arg4 mimeType:(id)arg5 waitUntilDone:(_Bool)arg6;
- (id)makeHttpRequestOpeartionWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)makeURLRequest:(id)arg1 relativePath:(id)arg2 parameters:(id)arg3;
- (void)startRequestDIOperation:(id)arg1 method:(id)arg2 relativePath:(id)arg3 parameters:(id)arg4 waitUntilDone:(_Bool)arg5;
- (_Bool)postDoitSyncOperation:(id)arg1 relativePath:(id)arg2 parameters:(id)arg3 operation:(id)arg4 isBlocking:(_Bool)arg5;
- (void)udpateAuthorizationInfo;
- (id)initWithBaseURL:(id)arg1;
@property(readonly, nonatomic) long long networkReachabilityStatus;
- (void)reset;

@end

