//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIIntroductionView.h"

@class UIImageView;

@interface DIImageIntroView : DIIntroductionView
{
    UIImageView *_introImageView;
}

@property(retain, nonatomic) UIImageView *introImageView; // @synthesize introImageView=_introImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

