//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface DIListBox : UIView <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate>
{
    _Bool _enableScroll;
    float _cellHeight;
    id <DIListBoxDelegate> _delegate;
    UITableView *_tableView;
    NSMutableArray *_sourceItems;
    long long _selectedItemIndex;
    NSString *_seletedItem;
}

@property(nonatomic) float cellHeight; // @synthesize cellHeight=_cellHeight;
@property(retain, nonatomic) NSString *seletedItem; // @synthesize seletedItem=_seletedItem;
@property(nonatomic) long long selectedItemIndex; // @synthesize selectedItemIndex=_selectedItemIndex;
@property(retain, nonatomic) NSMutableArray *sourceItems; // @synthesize sourceItems=_sourceItems;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool enableScroll; // @synthesize enableScroll=_enableScroll;
@property(nonatomic) id <DIListBoxDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSelectItem:(id)arg1;
- (_Bool)willAddItem:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setItemHeight:(float)arg1;
- (float)getContentHeight;
- (void)resize:(struct CGSize)arg1;
- (void)addItems:(id)arg1 withSelectedItem:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

