//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "DIBottomToolBarDelegate.h"
#import "DIGroupSectionViewDelegate.h"
#import "DIItemEditDelegate.h"
#import "DIScheduledViewControllerDelegate.h"
#import "DISelectionViewControllerDelegate.h"
#import "DISmartAddViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITableViewLongPressDelegate.h"

@class DIBottomToolBar, DIObject, DISelectionViewController, DISmartAddView, DITableData, NSArray, NSMutableArray, NSString, UITableView, UIView;

@interface DIObjectListViewController : SIViewController <DISmartAddViewDelegate, DIBottomToolBarDelegate, DIItemEditDelegate, UITableViewLongPressDelegate, DISelectionViewControllerDelegate, DIGroupSectionViewDelegate, DIScheduledViewControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UIView *_headerView;
    DITableData *_tableData;
    UITableView *_objectsTableView;
    _Bool _editingSelection;
    NSString *_editingTitle;
    NSMutableArray *_selectedIndexPaths;
    UIView *_editingNaviBarBottomSeparatorLine;
    NSArray *_naviBarLeftButtonItems;
    NSArray *_naviBarRightButtonItems;
    DISelectionViewController *_groupbySelection;
    DISelectionViewController *_contextSelection;
    DISelectionViewController *_prioritySelection;
    DISelectionViewController *_goalSelection;
    DISelectionViewController *_projectSelection;
    DISelectionViewController *_movetoSelection;
    _Bool _disabelSmartAdd;
    _Bool _disabelEmptyTip;
    _Bool _showHeaderView;
    _Bool _inEditing;
    UIView *_whiteboardView;
    DIObject *_ownerObject;
    NSString *_emptyTip;
    NSString *_emptySubTip;
    DISmartAddView *_smartAddView;
    DIBottomToolBar *_bottomToolbar;
}

@property(retain, nonatomic) DIBottomToolBar *bottomToolbar; // @synthesize bottomToolbar=_bottomToolbar;
@property(nonatomic) _Bool inEditing; // @synthesize inEditing=_inEditing;
@property(retain, nonatomic) DISmartAddView *smartAddView; // @synthesize smartAddView=_smartAddView;
@property(retain, nonatomic) NSString *emptySubTip; // @synthesize emptySubTip=_emptySubTip;
@property(retain, nonatomic) NSString *emptyTip; // @synthesize emptyTip=_emptyTip;
@property(retain, nonatomic) DIObject *ownerObject; // @synthesize ownerObject=_ownerObject;
@property(nonatomic) _Bool showHeaderView; // @synthesize showHeaderView=_showHeaderView;
@property(retain, nonatomic) UIView *whiteboardView; // @synthesize whiteboardView=_whiteboardView;
@property(readonly, nonatomic) UITableView *objectsTableView; // @synthesize objectsTableView=_objectsTableView;
- (void).cxx_destruct;
- (void)listDidFilled;
- (void)listDidBecomeEmpty;
- (void)removeItem:(id)arg1;
- (id)updateItem:(id)arg1;
- (id)addItem:(id)arg1;
- (void)tryAddVirtualTasks:(id)arg1;
- (void)tryAddItemsInGoal:(id)arg1;
- (void)tryRemoveItemsInGoal:(id)arg1;
- (void)tryAddItemsInProject:(id)arg1;
- (void)tryRemoveItemsInProject:(id)arg1;
- (_Bool)isInEditing;
- (void)menuDidHide;
- (void)menuDidShow;
- (void)smartAddView:(id)arg1 didAddTask:(id)arg2;
- (void)smartAddViewDidClickCancel;
- (void)showSmartAdd;
- (void)search:(id)arg1;
- (void)scheduledViewController:(id)arg1 didSelectDate:(id)arg2;
- (void)selection:(id)arg1 didSelectItemWithTitle:(id)arg2 atIndex:(long long)arg3;
- (id)calendarViewForMoveItems:(id)arg1;
- (void)setGoalId:(id)arg1 goalTitle:(id)arg2 toObjects:(id)arg3;
- (void)setContextId:(id)arg1 contextTitle:(id)arg2 toObjects:(id)arg3;
- (void)setProject:(id)arg1 toTasks:(id)arg2;
- (void)setPriority:(long long)arg1 toTasks:(id)arg2;
- (void)moveProject:(id)arg1 toNonScheduledBox:(int)arg2;
- (void)moveTask:(id)arg1 toNonScheduledBox:(int)arg2;
- (void)moveProjectToScheduled:(id)arg1 date:(id)arg2;
- (void)moveTaskToScheduled:(id)arg1 date:(id)arg2 specificTime:(_Bool)arg3;
- (void)pickPriority:(id)arg1;
- (void)pickGoal:(id)arg1;
- (void)pickContext:(id)arg1;
- (void)pickProject:(id)arg1;
- (void)moveItem:(id)arg1;
- (void)unsetDoitNow:(id)arg1;
- (void)setDoitNow:(id)arg1;
- (id)_boxSelectionOptionsOfDIObjects:(id)arg1;
- (void)groupSectionDidClose:(id)arg1;
- (void)groupSectionDidOpen:(id)arg1;
- (void)refresh;
- (void)headerViewTapped:(id)arg1;
- (void)bottomToolbarDidChangeHeight:(double)arg1;
- (void)updateBottomToolbar;
- (id)selectedObjects;
- (void)cancelMultiSelectionEditing:(id)arg1;
- (void)setMultiSelectionEditingBarButtonItems;
- (void)setNormalNaviBarButtonItems;
- (void)loadTableContent;
- (void)updateTitle;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didRecognizeLongPressOnRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

