//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskGroup.h"

@class NSString, Project;

@interface DIProjectTaskGroup : DITaskGroup
{
    NSString *_projectName;
    NSString *_projectID;
    Project *_project;
}

+ (id)projectGroup:(id)arg1;
@property(retain, nonatomic) Project *project; // @synthesize project=_project;
@property(copy, nonatomic) NSString *projectID; // @synthesize projectID=_projectID;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (id)projectName;

@end

