//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SIViewController.h"

#import "UIActionSheetDelegate.h"

@class DIButton, DIReviewBarChartPage, DIReviewPieChartPage, NSArray, NSString, UIScrollView, UIView;

@interface DIReviewChartController : SIViewController <UIActionSheetDelegate>
{
    UIScrollView *_mainView;
    DIReviewPieChartPage *_pieChartPage;
    UIView *_sepLine;
    DIReviewBarChartPage *_barChartPage;
    DIButton *_shareButton;
    NSArray *_shareItems;
    CDUnknownBlockType _saveBlock;
    NSArray *_taskReviewInfos;
}

@property(retain, nonatomic) NSArray *taskReviewInfos; // @synthesize taskReviewInfos=_taskReviewInfos;
@property(copy, nonatomic) CDUnknownBlockType saveBlock; // @synthesize saveBlock=_saveBlock;
- (void).cxx_destruct;
- (void)on_close:(id)arg1;
- (id)p_produceImage;
- (id)p_fakeNavigationBarForImage;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)on_pressedShare:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithTaskReviewInfos:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

