//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIRootViewController.h"

@interface DIRootViewController (Private)
- (void)p_cancelRefreshTimer;
- (void)on_refreshTimerFired;
- (void)p_startRefreshTimerAtDate:(id)arg1;
@end

