//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSortDescriptor.h"

@interface DISingleProjectSortDescriptor : NSSortDescriptor
{
}

+ (id)sortDescriptor;
- (long long)compareObject:(id)arg1 toObject:(id)arg2;
- (long long)completedCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)repeatCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)positionForTaskInRepeatGroup:(id)arg1;
- (long long)waitingCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)somedayCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)scheduleCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)tomorrowCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)nextCompareTask:(id)arg1 toTask:(id)arg2;
- (long long)todayCompareTask:(id)arg1 toTask:(id)arg2;

@end

