//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UITableView, UITextView;

@interface DISmartAddView : UIView <UITableViewDelegate, UITableViewDataSource, UITextViewDelegate, UITextFieldDelegate>
{
    UILabel *_maskView;
    UIView *_inputBar;
    UIView *_buttonView;
    UIButton *_dateButton;
    UIButton *_contextButton;
    UIButton *_projectButton;
    UIButton *_priorityButton;
    UIButton *_tagButton;
    UITableView *_contentTable;
    NSMutableArray *_contents;
    NSMutableArray *_contentsSource;
    UITextView *_inputTextView;
    UIButton *_clearButton;
    unsigned short _sectionType;
    NSString *_dateMatch;
    NSString *_contextMatch;
    NSString *_projectMatch;
    NSString *_priorityMatch;
    float _maxHeight;
    id <DISmartAddViewDelegate> _smartAddDelegate;
    NSString *_smartAddTip;
}

@property(retain, nonatomic) NSString *smartAddTip; // @synthesize smartAddTip=_smartAddTip;
@property(nonatomic) id <DISmartAddViewDelegate> smartAddDelegate; // @synthesize smartAddDelegate=_smartAddDelegate;
- (void).cxx_destruct;
- (void)keyboardDidShow:(id)arg1;
- (void)clearText:(id)arg1;
- (void)maskViewClicked:(id)arg1;
- (_Bool)saveTags:(id)arg1 toTask:(id)arg2;
- (void)saveNewTag:(id)arg1;
- (void)showTagContent:(id)arg1;
- (void)showPriorityContent:(id)arg1;
- (void)showProjectContent:(id)arg1;
- (void)showContextContent:(id)arg1;
- (void)showDateContent:(id)arg1;
- (void)hideContentTable;
- (void)showContentTable;
- (void)appendContentSeperator:(unsigned short)arg1;
- (void)setUpTagContentSource;
- (void)setUpPriorityContentSource;
- (void)setUpProjectContentSource;
- (void)setUpContextContentSource;
- (void)setUpDateContentSource;
- (void)updateContents:(unsigned short)arg1 key:(id)arg2;
- (id)getMatchedSectionString:(unsigned short)arg1;
- (void)updateMatchedSectionString:(unsigned short)arg1 matchString:(id)arg2;
- (void)appendTextToTextField:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)textViewTextDidChangeNotification:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)parserTask;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initMaskView;
- (void)initContentView;
- (void)initButtons;
- (void)initInputBar;
- (void)didDisappear;
- (void)willDisappear;
- (void)didAppear;
- (void)willAppear;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 maxHeight:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

