//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DITaskCommonDetailViewController.h"

#import "DIDailyPlanTabBarDelegate.h"

@class DIDailyPlanTabBar, NSString;

@interface DITaskSnoozeViewController : DITaskCommonDetailViewController <DIDailyPlanTabBarDelegate>
{
    DIDailyPlanTabBar *_tabBar;
    CDUnknownBlockType _CloseBlock;
}

@property(copy, nonatomic) CDUnknownBlockType CloseBlock; // @synthesize CloseBlock=_CloseBlock;
- (void).cxx_destruct;
- (void)dailyPlanTabBar:(id)arg1 didSelectedAtIndex:(long long)arg2;
- (void)on_cancel:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setTask:(id)arg1;
- (void)dealloc;
- (id)initWithTask:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

