//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Task, UITableView, UITableViewCell, UIView, UIViewController;

@protocol DITaskInfoSectionProtocol <NSObject>
@property(retain, nonatomic) Task *task;
@property(nonatomic) long long section;
@property(nonatomic) __weak id parent;
- (void)cleanDataDirty;
- (_Bool)isDataDirty;
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForRow:(long long)arg2;
- (double)tableView:(UITableView *)arg1 heightForRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(UITableView *)arg1;
- (void)registerInTableView:(UITableView *)arg1;
- (id)initWithTask:(Task *)arg1;

@optional
- (_Bool)tableView:(UITableView *)arg1 didSelectRow:(long long)arg2 inController:(UIViewController *)arg3;
- (_Bool)tableView:(UITableView *)arg1 shouldHighlightRow:(long long)arg2;
- (UIView *)sectionHeaderInTableView:(UITableView *)arg1;
- (double)sectionHeaderHeightInTableView:(UITableView *)arg1;
- (long long)tableView:(UITableView *)arg1 targetIndexPathForMoveFromRowAtIndex:(long long)arg2 toProposedIndex:(long long)arg3;
- (void)tableView:(UITableView *)arg1 moveRowAtIndex:(long long)arg2 toIndex:(long long)arg3;
- (_Bool)tableView:(UITableView *)arg1 canMoveRow:(long long)arg2;
@end

