//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class DIAvatarImageView, UILabel, UITextView;

@interface DITaskCommentCell : UITableViewCell
{
    DIAvatarImageView *_avatarView;
    UILabel *_nameLabel;
    UITextView *_commentView;
}

+ (double)cellHeightForComment:(id)arg1 width:(double)arg2;
+ (id)commentView;
- (void).cxx_destruct;
- (id)formatCommentTime:(id)arg1;
- (void)reloadTaskComment:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

