//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIV2LocalDataMigrate : NSObject
{
}

+ (_Bool)migrateModifiedDataToV4;
+ (_Bool)upgradeTransactions;
+ (void)upgradeSubTask:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeTaskComment:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeTag:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeTask:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeProject:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeContext:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeGoal:(id)arg1 fromDB:(id)arg2;
+ (void)upgradeFilter:(id)arg1 fromDB:(id)arg2;
+ (id)db1_0;
+ (_Bool)isDB1_0Validate;
+ (_Bool)migrateSyncInfo;
+ (_Bool)migrateSettings;
+ (id)upgradingUserEmail;
+ (id)upgradingUserId;
+ (_Bool)setUpgraded;
+ (_Bool)isUpgraded;
+ (_Bool)updateAppInfomation;

@end

