//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DIWidgetURLSerialization : NSObject
{
}

+ (id)taskRpeatNOFromURL:(id)arg1;
+ (id)taskUUIDFromURL:(id)arg1;
+ (id)openTaskURLWithTask:(id)arg1 repeatNO:(id)arg2;

@end

