//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Project.h"

@interface Project (Media)
- (void)removeMediaAtIndex:(unsigned long long)arg1 ofType:(int)arg2;
- (void)removeMedia:(id)arg1;
- (void)addMedia:(id)arg1;
- (id)mediasWithType:(int)arg1;
@end

