//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DIObject.h"

#import "NSCopying.h"

@class NSDate, NSString;

@interface Reminder : DIObject <NSCopying>
{
    _Bool _sent;
    NSString *_mode;
    NSString *_view;
    NSDate *_time;
    NSString *_representedTaskId;
}

@property(copy, nonatomic) NSString *representedTaskId; // @synthesize representedTaskId=_representedTaskId;
@property(nonatomic) _Bool sent; // @synthesize sent=_sent;
@property(retain, nonatomic) NSDate *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *view; // @synthesize view=_view;
@property(retain, nonatomic) NSString *mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (id)description;
- (id)toDictionary;
- (id)initWithDictionay:(id)arg1;
- (id)initWithDefault;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setRelativeReminder;
- (void)setAbsoluteReminder;
@property(readonly, nonatomic, getter=isEmailMode) _Bool emailMode;
@property(readonly, nonatomic, getter=isPopupMode) _Bool popupMode;
@property(readonly, nonatomic, getter=isAbsolute) _Bool absolute;
@property(readonly, nonatomic, getter=isRelative) _Bool relative;
- (_Bool)isReminder;

@end

