//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface SOColor : UIColor
{
}

+ (id)colorWithPatternImageFile:(id)arg1;
+ (id)x333333;
+ (id)x888888;
+ (id)xffffffWithAlpha:(float)arg1;
+ (id)x000000WithAlpha:(float)arg1;
+ (id)xffffff;
+ (id)x000000;
+ (id)blackColorWithAlpha:(float)arg1;
+ (id)whiteColorWithAlpha:(float)arg1;
+ (id)colorFromRGBA:(unsigned long long)arg1 alpha:(float)arg2;
+ (id)colorFromRGB:(unsigned long long)arg1;

@end

