//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface Transaction : NSObject
{
    long long _pk;
    NSString *_transactionID;
    NSString *_username;
    NSString *_userId;
    NSString *_receiptData;
    NSDate *_transactionDate;
}

@property(retain, nonatomic) NSDate *transactionDate; // @synthesize transactionDate=_transactionDate;
@property(retain, nonatomic) NSString *receiptData; // @synthesize receiptData=_receiptData;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *transactionID; // @synthesize transactionID=_transactionID;
@property(nonatomic) long long pk; // @synthesize pk=_pk;
- (void).cxx_destruct;
- (id)toDictionary;

@end

