//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableData, NSString, NSURLConnection, UIActivityIndicatorView, UIImageView;

@interface AsyncImageView : UIView
{
    _Bool isLoaded;
    NSString *notificationName;
    UIImageView *imageView;
    NSURLConnection *connection;
    NSMutableData *data;
    UIActivityIndicatorView *indicatorView;
    NSString *imageSavePath;
    NSString *failLoadImageNameString;
    id <AsyncImageViewDelegate> delegate;
    long long touchTag;
    _Bool isAcceptTouch;
    NSString *downLoadURL;
    NSString *_touchURL;
}

@property(retain, nonatomic) NSString *touchURL; // @synthesize touchURL=_touchURL;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data;
@property(retain, nonatomic) NSString *downLoadURL; // @synthesize downLoadURL;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection;
@property(nonatomic) long long touchTag; // @synthesize touchTag;
@property(nonatomic) id <AsyncImageViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *failLoadImageNameString; // @synthesize failLoadImageNameString;
@property(retain, nonatomic) NSString *imageSavePath; // @synthesize imageSavePath;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(retain, nonatomic) NSString *notificationName; // @synthesize notificationName;
@property(nonatomic) _Bool isAcceptTouch; // @synthesize isAcceptTouch;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded;
- (id)image;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)loadImageFromLocalPath:(id)arg1;
- (void)loadImageFromURLString:(id)arg1 andPath:(id)arg2;
- (void)loadImageLocalPathString:(id)arg1;
- (void)loadImageFromURLString:(id)arg1;
- (void)reloadImage;
- (void)loadImageFromURL:(id)arg1;
- (void)setDefaultImageNameString:(id)arg1;
- (void)remindMeWithNotificationName:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

