//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AVGLImage : NSObject
{
    int _imageWidth;
    int _imageHeight;
    int _angle;
    char *_imageData;
    _Bool _isFullScreenShow;
    int _viewStatus;
    int _dataFormat;
}

@property(nonatomic) int dataFormat; // @synthesize dataFormat=_dataFormat;
@property(nonatomic) int viewStatus; // @synthesize viewStatus=_viewStatus;
@property(nonatomic) _Bool isFullScreenShow; // @synthesize isFullScreenShow=_isFullScreenShow;
@property(nonatomic) int angle; // @synthesize angle=_angle;
@property(nonatomic) char *data; // @synthesize data=_imageData;
@property(nonatomic) int height; // @synthesize height=_imageHeight;
@property(nonatomic) int width; // @synthesize width=_imageWidth;
- (void)dealloc;

@end

