//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVGLRenderView.h"

@interface AVGLCustomRenderView : AVGLRenderView
{
    long long _iLiveRotationType;
}

@property(nonatomic) long long iLiveRotationType; // @synthesize iLiveRotationType=_iLiveRotationType;
- (void)updateVertexs2;
- (void)updateVertexs;
- (void)updateTexCoord2;
- (void)updateTexCoord;
- (id)initWithFrame:(struct CGRect)arg1;

@end

