//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduPanoOverlay.h"

@class NSURL, UIImage;

@interface BaiduPanoImageOverlay : BaiduPanoOverlay
{
    NSURL *_url;
    UIImage *_image;
    struct CGSize _size;
}

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)init;

@end

