//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BaiduPanoOverlay : NSObject
{
    NSString *_overlayKey;
    unsigned long long _type;
    double _height;
    CDStruct_2c43369c _coordinate;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *overlayKey; // @synthesize overlayKey=_overlayKey;
- (void).cxx_destruct;
- (id)init;

@end

