//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BaiduPanoDataFetcher : NSObject
{
}

+ (id)requestPanoramaInfoWithLon:(double)arg1 Lat:(double)arg2;
+ (id)requestPanoramaInfoWithX:(double)arg1 Y:(double)arg2;
+ (id)requestPanoramaInfoWithUid:(id)arg1;
+ (id)requestPanoramaRecommendationServiceDataWithPid:(id)arg1;
+ (id)requestPanoramaIndoorDataWithIid:(id)arg1;

@end

