//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ChannelInfo : NSObject
{
    NSString *_channelName;
    NSString *_channelDesc;
    NSString *_channelPassword;
}

@property(copy, nonatomic) NSString *channelPassword; // @synthesize channelPassword=_channelPassword;
@property(copy, nonatomic) NSString *channelDesc; // @synthesize channelDesc=_channelDesc;
@property(copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
- (void).cxx_destruct;

@end

