//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface CompanySectionItem : NSObject
{
    NSString *_typeCode;
    NSString *_title;
    NSString *_number;
    NSArray *_itemsArray;
}

@property(retain, nonatomic) NSArray *itemsArray; // @synthesize itemsArray=_itemsArray;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *typeCode; // @synthesize typeCode=_typeCode;
- (void).cxx_destruct;
- (id)initWithDictionay:(id)arg1;

@end

