//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString, UIImageView, UIPanGestureRecognizer, UIView;

@interface DrawNavigationController : UINavigationController <UIGestureRecognizerDelegate>
{
    double startBackViewX;
    struct CGPoint startTouchPoint;
    UIImageView *lastScreenShotView;
    UIView *blackMask;
    _Bool _canDrawBack;
    _Bool _isMoving;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UIView *_backgroundView;
    NSMutableArray *_screenShotsList;
}

@property(nonatomic) _Bool isMoving; // @synthesize isMoving=_isMoving;
@property(retain, nonatomic) NSMutableArray *screenShotsList; // @synthesize screenShotsList=_screenShotsList;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) _Bool canDrawBack; // @synthesize canDrawBack=_canDrawBack;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)captureScreen;
- (id)customPopToViewController:(id)arg1 level:(long long)arg2 animated:(_Bool)arg3;
- (void)customPopViewControllerWithLevel:(long long)arg1 animated:(_Bool)arg2;
- (id)customPopToRootViewController:(_Bool)arg1;
- (void)customPushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)moveViewWithX:(float)arg1;
- (void)paningGestureReceive:(id)arg1;
- (void)setDrawEnable:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

