//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSAnnoFreePen.h"

@interface GSAnnoFreePenEx : GSAnnoFreePen
{
    unsigned char _stepType;
}

@property(nonatomic) unsigned char stepType; // @synthesize stepType=_stepType;

// Remaining properties
@property(nonatomic) _Bool isHighlight;

@end

