//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSAnnoBase : NSObject
{
    unsigned int _pageID;
    unsigned int _docID;
    long long _type;
    long long _annoID;
}

@property(nonatomic) unsigned int docID; // @synthesize docID=_docID;
@property(nonatomic) unsigned int pageID; // @synthesize pageID=_pageID;
@property(nonatomic) long long annoID; // @synthesize annoID=_annoID;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

