//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSAnnoBase.h"

@class NSMutableArray, UIColor;

@interface GSAnnoFreePen : GSAnnoBase
{
    unsigned char _lineSize;
    _Bool _isHighlight;
    NSMutableArray *_points;
    UIColor *_lineColor;
}

@property(nonatomic) _Bool isHighlight; // @synthesize isHighlight=_isHighlight;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) unsigned char lineSize; // @synthesize lineSize=_lineSize;
@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
- (void).cxx_destruct;

@end

