//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GSBroadcastManager, GSUserInfo, NSString;

@protocol GSBroadcastDelegate <NSObject>
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceiveBroadcastConnectResult:(unsigned long long)arg2;

@optional
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSetupCustomBitRate:(struct OpaqueVTCompressionSession *)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 lotteryActionType:(long long)arg2 userNames:(NSString *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 networkStatus:(unsigned char)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 upgradedAppDownLoadUrl:(NSString *)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 saveSettingsInfoKey:(NSString *)arg2 numberValue:(int)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 saveSettingsInfoKey:(NSString *)arg2 strValue:(NSString *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 querySettingsInfoKey:(NSString *)arg2 numberValue:(int *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 querySettingsInfoKey:(NSString *)arg2 strValue:(id *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 handDownUser:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 handUpUser:(long long)arg2 extraData:(NSString *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 checkinRequestResponsedUser:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 checkinRequestCountingDownFrom:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 broadcastMessage:(NSString *)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didUpdateUserInfo:(GSUserInfo *)arg2 updateFlag:(long long)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didLoseOtherUser:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceiveOtherUser:(GSUserInfo *)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceiveBroadcastInfoKey:(NSString *)arg2 value:(long long)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSetRecordingStatus:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSetStatus:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSetLocked:(_Bool)arg2;
- (void)broadcastManagerWillStartReconnect:(GSBroadcastManager *)arg1;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSelfLeaveBroadcastFor:(long long)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceiveBroadcastJoinResult:(long long)arg2 selfUserID:(long long)arg3 rootSeverRebooted:(_Bool)arg4;
@end

