//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSCardAnswerInfo : NSObject
{
    _Bool _isRigth;
    int _choosedNum;
}

@property(nonatomic) _Bool isRigth; // @synthesize isRigth=_isRigth;
@property(nonatomic) int choosedNum; // @synthesize choosedNum=_choosedNum;

@end

