//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GSChatMessage : NSObject
{
    NSString *_richText;
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *richText; // @synthesize richText=_richText;
- (void).cxx_destruct;
- (id)escapedString:(id)arg1;

@end

