//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class GSDocPageDrawingView, NSString;

@interface GSDocView : UIScrollView <UIScrollViewDelegate>
{
    _Bool _zoomEnabled;
    _Bool _fullMode;
    unsigned long long _limitTextureCount;
    GSDocPageDrawingView *_pageDrawingView;
}

@property(retain, nonatomic) GSDocPageDrawingView *pageDrawingView; // @synthesize pageDrawingView=_pageDrawingView;
@property(nonatomic) unsigned long long limitTextureCount; // @synthesize limitTextureCount=_limitTextureCount;
@property(nonatomic) _Bool fullMode; // @synthesize fullMode=_fullMode;
@property(nonatomic) _Bool zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
- (void).cxx_destruct;
- (int)docViewGetCurrentDocAnnoStepCount;
- (void)docViewFreeRender;
- (void)docViewInitRender;
- (void)docViewReOpenFile;
- (void)scrollViewDidZoom:(id)arg1;
- (void)setGlkBackgroundColor:(int)arg1 green:(int)arg2 blue:(int)arg3;
- (void)setPageDrawingViewCanHide:(_Bool)arg1;
- (void)clearPageAndAnno;
- (void)reSetDocView;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)goToAnimationStep:(int)arg1;
- (void)drawAnno:(id)arg1 onPage:(id)arg2;
- (void)drawPage:(id)arg1 docID:(unsigned int)arg2;
- (void)drawPage:(id)arg1 step:(int)arg2 docID:(unsigned int)arg3;
- (void)setFrame:(struct CGRect)arg1;
- (void)doSomeInitJob;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

