//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GSGrabInfo : NSObject
{
    _Bool _bBest;
    unsigned int _money;
    long long _llUserID;
    NSString *_username;
    long long _grabTime;
}

@property(nonatomic) _Bool bBest; // @synthesize bBest=_bBest;
@property(nonatomic) unsigned int money; // @synthesize money=_money;
@property(nonatomic) long long grabTime; // @synthesize grabTime=_grabTime;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) long long llUserID; // @synthesize llUserID=_llUserID;
- (void).cxx_destruct;

@end

