//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GSIDCInfo : NSObject
{
    _Bool _isCurrentIDC;
    NSString *_ID;
    NSString *_Name;
}

@property(nonatomic) _Bool isCurrentIDC; // @synthesize isCurrentIDC=_isCurrentIDC;
@property(copy, nonatomic) NSString *Name; // @synthesize Name=_Name;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

