//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GSLodItem : NSObject
{
    int _type;
    int _playtimes;
    unsigned int _totalTime;
    unsigned int _currentime;
    NSString *_lodID;
    NSString *_lodName;
}

@property(nonatomic) unsigned int currentime; // @synthesize currentime=_currentime;
@property(nonatomic) unsigned int totalTime; // @synthesize totalTime=_totalTime;
@property(nonatomic) int playtimes; // @synthesize playtimes=_playtimes;
@property(copy, nonatomic) NSString *lodName; // @synthesize lodName=_lodName;
@property(copy, nonatomic) NSString *lodID; // @synthesize lodID=_lodID;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

