//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GSOs : NSObject
{
    NSString *_type;
    NSString *_version;
    NSString *_apilevel;
}

@property(copy, nonatomic) NSString *apilevel; // @synthesize apilevel=_apilevel;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

