//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVCaptureVideoPreviewLayer, AVSampleBufferDisplayLayer, GSMovieGLView, UIImageView;

@interface GSVideoView : UIView
{
    int _spsSize;
    int _ppsSize;
    unsigned long long _videoViewContentMode;
    GSMovieGLView *_movieGLView;
    UIImageView *_movieASImageView;
    AVCaptureVideoPreviewLayer *_previewLayer;
    AVSampleBufferDisplayLayer *_videoLayer;
    double _ratio;
    struct opaqueCMFormatDescription *_formatDesc;
    struct OpaqueVTDecompressionSession *_decompressionSession;
}

@property(nonatomic) int ppsSize; // @synthesize ppsSize=_ppsSize;
@property(nonatomic) int spsSize; // @synthesize spsSize=_spsSize;
@property(nonatomic) struct OpaqueVTDecompressionSession *decompressionSession; // @synthesize decompressionSession=_decompressionSession;
@property(nonatomic) struct opaqueCMFormatDescription *formatDesc; // @synthesize formatDesc=_formatDesc;
@property(nonatomic) double ratio; // @synthesize ratio=_ratio;
@property(retain, nonatomic) AVSampleBufferDisplayLayer *videoLayer; // @synthesize videoLayer=_videoLayer;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) UIImageView *movieASImageView; // @synthesize movieASImageView=_movieASImageView;
@property(retain, nonatomic) GSMovieGLView *movieGLView; // @synthesize movieGLView=_movieGLView;
@property(nonatomic) unsigned long long videoViewContentMode; // @synthesize videoViewContentMode=_videoViewContentMode;
- (void).cxx_destruct;
- (void)dealloc;
- (void)reMovePreviewLayer;
- (void)setUpPreviewLayer;
- (id)getDecimalTwo:(double)arg1;
- (void)renderAsVideoByImage:(id)arg1;
- (void)renderVideoFrame:(id)arg1;
- (struct CGRect)adjustMovieGLView:(double)arg1;
- (void)render:(struct opaqueCMSampleBuffer *)arg1;
- (void)receivedRawVideoFrame:(char *)arg1 withSize:(unsigned int)arg2;
- (void)createDecompSession;
- (void)hardwareAccelerateRender:(void *)arg1 size:(int)arg2;
- (struct CGRect)adjustMovieGLViewToRatioFill:(double)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)DidEnterBackground;
- (void)DidBecomeActive;
- (id)initWithFrame:(struct CGRect)arg1;

@end

