//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString, UIColor, UIImage, UILabel;

@interface IFTweetLabel : UIView
{
    UIColor *normalColor;
    UIColor *highlightColor;
    UIImage *normalImage;
    UIImage *highlightImage;
    UILabel *label;
    _Bool linksEnabled;
    NSMutableArray *_my_expressions;
    NSString *_html_string;
    NSMutableArray *_my_url;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *my_expressions; // @synthesize my_expressions=_my_expressions;
@property(nonatomic) _Bool linksEnabled; // @synthesize linksEnabled;
@property(retain, nonatomic) UILabel *label; // @synthesize label;
@property(retain, nonatomic) UIImage *highlightImage; // @synthesize highlightImage;
@property(retain, nonatomic) UIImage *normalImage; // @synthesize normalImage;
@property(retain, nonatomic) UIColor *highlightColor; // @synthesize highlightColor;
@property(retain, nonatomic) UIColor *normalColor; // @synthesize normalColor;
- (void).cxx_destruct;
- (void)praseNodeToExpression;
- (id)getBodyContent;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)removeButtons;
- (void)createButtons;
- (void)createButtonsWithText:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)createButtonWithText:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)handleButton:(id)arg1;

@end

