//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QAVChangeDelegate.h"
#import "QAVChangeRoleDelegate.h"
#import "QAVRoomDelegate.h"

@class ILiveGLBaseView, ILiveRoomOption, NSMutableDictionary, NSString, QAVContext;

@interface ILiveRoomAVManager : NSObject <QAVChangeDelegate, QAVChangeRoleDelegate, QAVRoomDelegate>
{
    QAVContext *_avContext;
    ILiveGLBaseView *_glBaseView;
    NSMutableDictionary *_memoMap;
    _Bool _isOpenCamera;
    _Bool _isOpenMic;
    _Bool _isOpenSpeaker;
    _Bool _isEarPhoneMode;
    int _relationId;
    ILiveRoomOption *_option;
    CDUnknownBlockType _changeAuthSuccBlock;
    CDUnknownBlockType _changeAuthFailBlock;
    CDUnknownBlockType _changeRoleSuccBlock;
    CDUnknownBlockType _changeRoleFailBlock;
    CDUnknownBlockType _enterAvRoomSuccBlock;
    CDUnknownBlockType _enterAvRoomFailBlock;
    CDUnknownBlockType _exitAvRoomCompleteBlock;
}

+ (id)getInstance;
@property(copy, nonatomic) CDUnknownBlockType exitAvRoomCompleteBlock; // @synthesize exitAvRoomCompleteBlock=_exitAvRoomCompleteBlock;
@property(copy, nonatomic) CDUnknownBlockType enterAvRoomFailBlock; // @synthesize enterAvRoomFailBlock=_enterAvRoomFailBlock;
@property(copy, nonatomic) CDUnknownBlockType enterAvRoomSuccBlock; // @synthesize enterAvRoomSuccBlock=_enterAvRoomSuccBlock;
@property(copy, nonatomic) CDUnknownBlockType changeRoleFailBlock; // @synthesize changeRoleFailBlock=_changeRoleFailBlock;
@property(copy, nonatomic) CDUnknownBlockType changeRoleSuccBlock; // @synthesize changeRoleSuccBlock=_changeRoleSuccBlock;
@property(copy, nonatomic) CDUnknownBlockType changeAuthFailBlock; // @synthesize changeAuthFailBlock=_changeAuthFailBlock;
@property(copy, nonatomic) CDUnknownBlockType changeAuthSuccBlock; // @synthesize changeAuthSuccBlock=_changeAuthSuccBlock;
@property(readonly, nonatomic) ILiveRoomOption *option; // @synthesize option=_option;
@property(readonly, nonatomic) _Bool isEarPhoneMode; // @synthesize isEarPhoneMode=_isEarPhoneMode;
@property(readonly, nonatomic) _Bool isOpenSpeaker; // @synthesize isOpenSpeaker=_isOpenSpeaker;
@property(readonly, nonatomic) _Bool isOpenMic; // @synthesize isOpenMic=_isOpenMic;
@property(readonly, nonatomic) _Bool isOpenCamera; // @synthesize isOpenCamera=_isOpenCamera;
@property(nonatomic) int relationId; // @synthesize relationId=_relationId;
- (void).cxx_destruct;
- (long long)hasAudioCount;
- (long long)maxMicCount;
- (long long)hasVideoCount;
- (long long)maxVideoCount;
- (id)createGLViewIn:(id)arg1 atRect:(struct CGRect)arg2;
- (id)createGLViewIn:(id)arg1;
- (void)bindGLView:(id)arg1;
- (id)glBaseView;
- (void)OnRoomEvent:(int)arg1 subtype:(int)arg2 data:(void *)arg3;
- (void)OnCameraSettingNotify:(int)arg1 Height:(int)arg2 Fps:(int)arg3;
- (id)autoRenderMemoMap;
- (void)handleSemiCameraVideoList:(id)arg1;
- (void)OnSemiAutoRecvCameraVideo:(id)arg1;
- (void)OnPrivilegeDiffNotify:(int)arg1;
- (void)onHandleEndpointsUpdateInfo:(long long)arg1 endpointlist:(id)arg2;
- (id)renderMemoOf:(id)arg1;
- (void)OnEndpointsUpdateInfo:(long long)arg1 endpointlist:(id)arg2;
- (id)eventTip:(long long)arg1;
- (void)autoRequestMemoMapView;
- (void)OnRoomDisconnect:(int)arg1;
- (void)OnExitRoomComplete;
- (void)OnEnterRoomComplete:(int)arg1;
- (void)OnChangeRoleDelegate:(int)arg1;
- (void)OnChangeAuthority:(int)arg1;
- (void)mainThreadFailBlock:(CDUnknownBlockType)arg1 module:(id)arg2 errId:(int)arg3 errMsg:(id)arg4;
- (void)mainThreadSuccBlock:(CDUnknownBlockType)arg1;
- (void)releaseSrc;
- (id)createRoomParam:(int)arg1 option:(id)arg2;
- (id)getQualityData;
- (long long)getCurAudioMode;
- (_Bool)getCurSpeakerState;
- (_Bool)getCurMicState;
- (_Bool)getCurCameraState;
- (long long)getCurCameraPos;
- (int)getRelationId;
- (void)setIsOpenSpeaker:(_Bool)arg1;
- (void)setAudioMode:(long long)arg1;
- (void)enableSpeaker:(_Bool)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)setIsOpenMic:(_Bool)arg1;
- (void)enableMic:(_Bool)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)realSwitchCamera:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)switchCamera:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)setIsOpenCamera:(_Bool)arg1;
- (void)realEnableCamera:(long long)arg1 enable:(_Bool)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)enableCamera:(long long)arg1 enable:(_Bool)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)changeRole:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)changeAuthority:(unsigned long long)arg1 authBuf:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)cancelAllView:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)cancelViewList:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)requestViewList:(id)arg1 srcTypeList:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)exitAVRoom:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)releaseGLResource;
- (void)enterAvRoom:(int)arg1 option:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (_Bool)isInvalidRoomOption:(id)arg1;
- (void)setOption:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

