//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TIMMessageListener.h"
#import "TLSPwdLoginListener.h"
#import "TLSStrAccountRegListener.h"

@class NSString;

@interface ILiveLoginManager : NSObject <TLSPwdLoginListener, TLSStrAccountRegListener, TIMMessageListener>
{
    CDUnknownBlockType _succBlock;
    CDUnknownBlockType _failBlock;
    NSString *_userSig;
    NSString *_loginId;
}

+ (id)getInstance;
@property(retain, nonatomic) NSString *loginId; // @synthesize loginId=_loginId;
@property(retain, nonatomic) NSString *userSig; // @synthesize userSig=_userSig;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType succBlock; // @synthesize succBlock=_succBlock;
- (void).cxx_destruct;
- (void)reportEvent:(long long)arg1 errCode:(int)arg2 errDesc:(id)arg3;
- (void)errorInMainThread:(CDUnknownBlockType)arg1 module:(id)arg2 code:(int)arg3 desc:(id)arg4;
- (void)succInMainThread:(CDUnknownBlockType)arg1;
- (void)releaseBlock;
- (void)OnStrAccountRegTimeout:(id)arg1;
- (void)OnStrAccountRegFail:(id)arg1;
- (void)OnStrAccountRegSuccess:(id)arg1;
- (void)OnPwdLoginNeedImgcode:(id)arg1 andErrInfo:(id)arg2;
- (void)OnPwdLoginReaskImgcodeSuccess:(id)arg1;
- (void)OnPwdLoginTimeout:(id)arg1;
- (void)OnPwdLoginFail:(id)arg1;
- (void)OnPwdLoginSuccess:(id)arg1;
- (void)tlsRegister:(id)arg1 pwd:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)tlsLogout:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)tlsLogin:(id)arg1 pwd:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)iLiveLogout:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)iLiveLogin:(id)arg1 sig:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (id)getLoginId;
- (id)getSig;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

