//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface ILiveRoomAVOption : NSObject
{
    _Bool _autoCamera;
    _Bool _autoMic;
    _Bool _autoSpeaker;
    _Bool _autoHdAudio;
    int _audioCategory;
    unsigned long long _authBits;
    NSData *_authBuffer;
    long long _cameraPos;
    long long _videoRecvMode;
}

+ (id)defaultAudioOption;
+ (id)defaultInteractUserLiveOption;
+ (id)defaultGuestLiveOption;
+ (id)defaultHostLiveOption;
@property(nonatomic) long long videoRecvMode; // @synthesize videoRecvMode=_videoRecvMode;
@property(nonatomic) _Bool autoHdAudio; // @synthesize autoHdAudio=_autoHdAudio;
@property(nonatomic) long long cameraPos; // @synthesize cameraPos=_cameraPos;
@property(nonatomic) _Bool autoSpeaker; // @synthesize autoSpeaker=_autoSpeaker;
@property(nonatomic) _Bool autoMic; // @synthesize autoMic=_autoMic;
@property(nonatomic) _Bool autoCamera; // @synthesize autoCamera=_autoCamera;
@property(retain, nonatomic) NSData *authBuffer; // @synthesize authBuffer=_authBuffer;
@property(nonatomic) unsigned long long authBits; // @synthesize authBits=_authBits;
@property(nonatomic) int audioCategory; // @synthesize audioCategory=_audioCategory;
- (void).cxx_destruct;

@end

