//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ILiveAVGLViewAble.h"
#import "QAVLocalVideoDelegate.h"
#import "QAVRemoteVideoDelegate.h"
#import "QAVScreenVideoDelegate.h"

@class AVGLBaseView, NSMutableArray, NSString, TCAVFrameDispatcher;

@interface ILiveGLBaseView : UIView <ILiveAVGLViewAble, QAVLocalVideoDelegate, QAVRemoteVideoDelegate, QAVScreenVideoDelegate>
{
    AVGLBaseView *_imageView;
    TCAVFrameDispatcher *_frameDispatcher;
    NSMutableArray *_renderViewMap;
    NSString *_currentUserID;
    long long _directionStyle;
}

+ (id)createRenderView:(struct CGRect)arg1 currentUserID:(id)arg2;
@property(nonatomic) long long directionStyle; // @synthesize directionStyle=_directionStyle;
@property(readonly, nonatomic) AVGLBaseView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)OnVideoPreview:(id)arg1;
- (void)OnLocalVideoRawSampleBuf:(struct opaqueCMSampleBuffer *)arg1 result:(struct opaqueCMSampleBuffer **)arg2;
- (void)OnLocalVideoPreProcess:(id)arg1;
- (void)OnLocalVideoPreview:(id)arg1;
- (void)onAVRecvVideoFrame:(id)arg1;
- (id)allRenderKeys;
- (void)startDisplay;
- (void)stopDisplay;
- (id)getRenderViewForKey:(id)arg1;
- (id)getAllRenderViews;
- (id)getRenderView:(id)arg1;
- (void)removeRenderViewForKey:(id)arg1;
- (_Bool)switchRenderViewOf:(id)arg1 withRender:(id)arg2;
- (void)removeRenderViewForKey:(id)arg1 onlyRemoveRender:(_Bool)arg2;
- (void)addSubview:(id)arg1 forKey:(id)arg2;
- (id)addRenderAt:(struct CGRect)arg1 forKey:(id)arg2;
- (void)addRenderView:(id)arg1 forKey:(id)arg2;
- (void)sendRenderViewToBack:(id)arg1;
- (void)bringRenderViewToFront:(id)arg1;
- (void)destroyRenderView;
- (void)layoutSubviews;
- (void)configDispatcher;
- (void)WillEnterForeground:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setCurrentUserID:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 currentUserID:(id)arg2;
- (void)dealloc;
- (id)findAvailableRenderView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

