//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol ILiveAVGLRenderViewAble <NSObject>
+ (id)createRenderView:(struct CGRect)arg1;
@property(nonatomic) long long rotationType;
@property(readonly, nonatomic) NSString *renderKey;
@property(nonatomic) struct CGRect renderFrame;
- (void)setNeedMirrorReverse:(_Bool)arg1;
@end

