//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface IMSRqdPriority : NSObject
{
    unsigned long long _priority;
    long long _channelName;
    NSArray *_conflictFrameworks;
    NSMutableArray *_existBuglys;
}

@property(retain, nonatomic) NSMutableArray *existBuglys; // @synthesize existBuglys=_existBuglys;
@property(retain, nonatomic) NSArray *conflictFrameworks; // @synthesize conflictFrameworks=_conflictFrameworks;
@property(nonatomic) long long channelName; // @synthesize channelName=_channelName;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
- (id)description;
- (id)disableInstructionOfChannelName:(long long)arg1;
- (id)infoPlistKeyForChannelName:(long long)arg1;
- (unsigned long long)priorityOfChannelName:(long long)arg1;
- (id)disableInstructionString;
- (_Bool)isGoodToInstall;
- (_Bool)isSelfDisabledByInfoPlistConfiguration;
- (id)oldSdkConflictInstruction;
- (_Bool)isOldVersionSdkExist;
- (_Bool)isPartnerDiabledWithKey:(id)arg1;
- (id)initWithPriorityChannelName:(long long)arg1;

@end

