//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIAlertViewDelegate.h"

@class NSString, SFCommandWordLiveViewController, UILabel;

@interface LiveCoverView : UIView <UIAlertViewDelegate>
{
    struct CGSize textSize;
    SFCommandWordLiveViewController *_cwlVC;
    UILabel *_numLab;
}

@property(retain, nonatomic) UILabel *numLab; // @synthesize numLab=_numLab;
@property(retain, nonatomic) SFCommandWordLiveViewController *cwlVC; // @synthesize cwlVC=_cwlVC;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)btnAct:(id)arg1;
- (void)scrollAnimatEnd:(id)arg1;
- (void)scrollAnimatBegen:(id)arg1;
- (void)showAnimation:(id)arg1;
- (void)scrollLabelAnimation:(id)arg1 rect:(struct CGRect)arg2;
- (struct CGSize)preperHeighWithLabel:(id)arg1;
- (void)creatStartButton;
- (void)creatUI;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

