//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MakeC2CCallViewDelegate.h"

@class MakeC2CCallView, NSString, TILC2CCall, UIView;

@interface MakeC2CCallViewController : UIViewController <MakeC2CCallViewDelegate>
{
    MakeC2CCallView *_callView;
    TILC2CCall *_call;
    _Bool _isMakeCall;
    long long _callType;
    NSString *_peerId;
    NSString *_peerName;
    NSString *_iconUrl;
    UIView *_renderView;
}

@property(retain, nonatomic) UIView *renderView; // @synthesize renderView=_renderView;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *peerName; // @synthesize peerName=_peerName;
@property(retain, nonatomic) NSString *peerId; // @synthesize peerId=_peerId;
@property(nonatomic) long long callType; // @synthesize callType=_callType;
- (void).cxx_destruct;
- (void)disMissVC;
- (void)onExitCall:(id)arg1;
- (struct CGRect)smallViewFrame;
- (void)makeCall;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)configLiveView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

