//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, UMTActivateMsg, UMTAppInfo, UMTClientStats, UMTDeviceInfo, UMTIdTracking, UMTMiscInfo, UMTUALogEntry;

@interface MobClickThrift : NSObject
{
    UMTUALogEntry *_UALogEntry;
    UMTDeviceInfo *_deviceInfo;
    UMTAppInfo *_appInfo;
    UMTMiscInfo *_miscInfo;
    UMTIdTracking *_idTracking;
    UMTActivateMsg *_activateMsg;
    UMTClientStats *_clientStats;
    NSMutableArray *_sessions;
    NSMutableArray *_instantMessages;
}

+ (id)imprintPropertyValueWithKey:(id)arg1;
+ (id)generateImprintChecksum:(id)arg1;
+ (_Bool)validateImprintChecksum:(id)arg1;
+ (id)sharedInstance;
- (void)dealloc;
- (void)buildDeviceInfo;
- (void)buildAppInfo;
- (void)buildMiscInfo;
- (void)clearControlPolicy;
- (void)buildControlPolicy;
- (void)buildLogEntry;
- (void)setActivateMsgFlag;
- (void)writeIdTracking;
- (void)buildActivateMsg;
- (void)buildClientStats;
- (id)fromData:(id)arg1;
- (id)entityData;
- (id)toData;
- (void)buildInstantMessageFromEvent:(id)arg1;
- (void)buildInstantMessageFromError:(id)arg1;
- (void)buildInstantMessageFromEkv:(id)arg1;
- (void)buildSessionFrom:(id)arg1;
- (void)buildSessionsFromMobClickInternal;
- (void)buildInstantMessages;
- (void)buildSessions;
- (void)buildSessionsAndInstantMessages;
- (void)updateImprint:(id)arg1;
- (_Bool)verifyResponseData:(id)arg1;
- (void)buildImprint;
- (void)saveIdTracking;
- (void)buildIdTracking;
- (void)buildActiveUser;
- (id)init;

@end

