//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSFNetTestWhiteList : NSObject
{
    _Bool _isIn;
    _Bool _isLoad;
}

+ (id)instance;
- (void)setInWhiteList:(id)arg1;
- (_Bool)isInWhiteList;
- (id)whileListFile;
- (id)init;

@end

