//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, OTPGenerator;

@interface OTPAuthURL : NSObject
{
    NSString *name_;
    NSData *keychainItemRef_;
    OTPGenerator *generator_;
    NSString *_type;
}

+ (id)encodeBase32:(id)arg1;
+ (id)base32Decode:(id)arg1;
+ (id)authURLWithKeychainDictionary:(id)arg1;
+ (id)authURLWithKeychainItemRef:(id)arg1;
+ (id)authURLWithURL:(id)arg1 secret:(id)arg2;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) OTPGenerator *generator; // @synthesize generator=generator_;
@property(retain, nonatomic) NSData *keychainItemRef; // @synthesize keychainItemRef=keychainItemRef_;
@property(copy, nonatomic) NSString *name; // @synthesize name=name_;
- (id)description;
@property(readonly, nonatomic) NSString *checkCode; // @dynamic checkCode;
- (void)generateNextOTPCode;
- (_Bool)isInKeychain;
- (_Bool)removeFromKeychain;
- (_Bool)saveToKeychain;
- (id)url;
- (void)dealloc;
- (id)init;
- (id)initWithOTPGenerator:(id)arg1 name:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) NSString *otpCode; // @dynamic otpCode;

@end

