//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer;

@interface OTPAuthBarClock : UIView
{
    NSTimer *timer_;
    double period_;
}

@property(nonatomic) double period; // @synthesize period=period_;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=timer_;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)startUpTimer;
- (void)invalidate;
- (void)drawRect:(struct CGRect)arg1;
- (void)redrawTimer:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 period:(double)arg2;

@end

