//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface OverLoadChecker : NSObject
{
    NSMutableArray *_overLoadCmdList;
    NSMutableArray *_overLoadSvrList;
}

+ (id)instance;
- (id)getErrTipsForCmd:(id)arg1;
- (_Bool)canSendCmd:(id)arg1;
- (id)init;

@end

