//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QAVUtil : NSObject
{
}

+ (_Bool)getPngInfo:(id)arg1 output:(CDStruct_9c718cc4 *)arg2;

@end

