//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QAVUserId : NSObject
{
    NSString *_userid;
    unsigned long long _tinyid;
    unsigned long long _uin;
}

@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(nonatomic) unsigned long long tinyid; // @synthesize tinyid=_tinyid;
@property(copy, nonatomic) NSString *userid; // @synthesize userid=_userid;
- (void)dealloc;

@end

