//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QAVFrameDesc;

@interface QAVVideoFrame : NSObject
{
    unsigned int _dataSize;
    QAVFrameDesc *_frameDesc;
    NSString *_identifier;
    char *_data;
    unsigned long long _roomID;
}

@property(nonatomic) unsigned long long roomID; // @synthesize roomID=_roomID;
@property(nonatomic) char *data; // @synthesize data=_data;
@property(nonatomic) unsigned int dataSize; // @synthesize dataSize=_dataSize;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) QAVFrameDesc *frameDesc; // @synthesize frameDesc=_frameDesc;
- (void)dealloc;

@end

