//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TILC2CCallStatusListener.h"
#import "TILCallNotificationListener.h"

@class CAGradientLayer, NSString, NSTimer, TILC2CCall, UIImageView, UILabel;

@interface RecvC2CCallView : UIView <TILCallNotificationListener, TILC2CCallStatusListener>
{
    UIImageView *_peerIcon;
    UILabel *_peerName;
    UILabel *_tips;
    UIImageView *_cancel;
    UIImageView *_accept;
    UIImageView *_refuse;
    UILabel *accepeLabel;
    UILabel *cancelLabel;
    UILabel *refuseLabel;
    CAGradientLayer *gradientLayer;
    CAGradientLayer *gradientLayer2;
    UIImageView *_micOn;
    UIImageView *_micOff;
    UILabel *micLabel;
    UIImageView *_speakerOn;
    UIImageView *_speakerOff;
    UILabel *speLabel;
    UIImageView *_cameraPos;
    UILabel *cameLabel;
    _Bool audioSpeak;
    struct CGRect _selfRect;
    struct CGRect _peerRect;
    TILC2CCall *_call;
    id <RecvC2CCallViewDelegate> _delegate;
    UIView *_renderView;
    NSTimer *_heartbeat;
    NSTimer *_timer;
    long long _seconds;
    NSString *_pName;
    NSString *_iconUrl;
}

@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *pName; // @synthesize pName=_pName;
- (void).cxx_destruct;
- (void)switchPos:(id)arg1;
- (void)switchSpeaker:(id)arg1;
- (void)switchVideo:(id)arg1;
- (void)switchMic:(id)arg1;
- (void)onHeartbeatMiss;
- (void)stopHeartBeatTimer;
- (void)startHeartBeatTimer;
- (void)onRecvNotification:(id)arg1;
- (void)onCallEnd:(long long)arg1;
- (void)onCallEstablish;
- (void)tapView:(id)arg1;
- (void)hangup:(id)arg1;
- (void)refuse:(id)arg1;
- (void)accept:(id)arg1;
- (void)recvCall;
- (void)stopAction;
- (void)runAction;
- (void)timeRunStart;
- (void)switchRenderView;
- (void)addRenderChatViews;
- (struct CGRect)smallViewFrame;
- (void)updateLivePanelVideo;
- (void)updateLivePanelAudio;
- (void)generateSubViews;
- (void)chatingBackViewgradient;
- (void)backViewgradient:(_Bool)arg1;
- (void)hideSubViews;
- (void)layoutVideo:(_Bool)arg1;
- (void)layoutAudio:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setRecvCallModel:(id)arg1 andDelegate:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

