//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RecvC2CCallViewDelegate.h"

@class NSString, RecvC2CCallView, TILC2CCall, TILC2CCallInvitation;

@interface RecvC2CCallViewController : UIViewController <RecvC2CCallViewDelegate>
{
    RecvC2CCallView *_recvView;
    TILC2CCall *_call;
    NSString *_peerId;
    long long _callType;
    TILC2CCallInvitation *_invite;
    NSString *_peerName;
    NSString *_iconUrl;
}

@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *peerName; // @synthesize peerName=_peerName;
@property(retain, nonatomic) TILC2CCallInvitation *invite; // @synthesize invite=_invite;
@property(nonatomic) long long callType; // @synthesize callType=_callType;
@property(retain, nonatomic) NSString *peerId; // @synthesize peerId=_peerId;
- (void).cxx_destruct;
- (void)onAcceptCall;
- (void)onExitCall:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)configLiveView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

