//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, RefreshTableView;

@interface RefreshTableViewController : BaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isRefresh;
    int _page;
    int _totalPage;
    RefreshTableView *_refreshTableView;
    NSMutableArray *_responseDataArray;
}

@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) int totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) int page; // @synthesize page=_page;
@property(retain, nonatomic) NSMutableArray *responseDataArray; // @synthesize responseDataArray=_responseDataArray;
@property(retain, nonatomic) RefreshTableView *refreshTableView; // @synthesize refreshTableView=_refreshTableView;
- (void).cxx_destruct;
- (void)hidenLoadMoreView:(_Bool)arg1;
- (void)loadMoreData;
- (void)refreshData;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestFail:(id)arg1;
- (void)requestSuccess:(id)arg1;
- (void)sendRequestToServer;
- (void)pullTableView;
- (void)pullToRequestNetData;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

