//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SFGlobalAlertViewDelegate.h"

@class NSString;

@interface RSASecurity : NSObject <SFGlobalAlertViewDelegate>
{
    struct __SecKey *_clientPrivateKey;
    struct __SecKey *_clientPublicKey;
    struct __SecKey *_serverPublicKey;
}

+ (id)sharedSecurity;
@property(nonatomic) struct __SecKey *serverPublicKey; // @synthesize serverPublicKey=_serverPublicKey;
@property(readonly, nonatomic) struct __SecKey *clientPublicKey; // @synthesize clientPublicKey=_clientPublicKey;
@property(readonly, nonatomic) struct __SecKey *clientPrivateKey; // @synthesize clientPrivateKey=_clientPrivateKey;
- (struct __SecKey *)getPublicKeyReference:(id)arg1;
- (void)addPeerPublicKey:(id)arg1 keyBits:(id)arg2;
- (struct __SecKey *)secKeyRefFromData:(id)arg1;
- (id)dataFromSecKeyRef:(struct __SecKey *)arg1;
- (void)setServerPublicKeyWithData:(id)arg1;
- (id)decryptCipherString:(id)arg1 withPrivateKey:(struct __SecKey *)arg2;
- (id)decryptCipherString:(id)arg1;
- (id)encryptPlainString:(id)arg1 withPublicKey:(struct __SecKey *)arg2;
- (void)globalAlertView:(id)arg1 clickedButtonIndex:(long long)arg2;
- (id)encryptPlainString:(id)arg1;
- (int)extractPublicKeyFromCertificateData:(id)arg1;
- (int)extractKeyFromPKCS12Data:(id)arg1 passphrase:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

