//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface ScanOverlayView : UIView
{
    struct CGRect _transparentArea;
}

@property(nonatomic) struct CGRect transparentArea; // @synthesize transparentArea=_transparentArea;
- (void)addWhiteRect:(struct CGContext *)arg1 rect:(struct CGRect)arg2;
- (void)addCenterClearRect:(struct CGContext *)arg1 rect:(struct CGRect)arg2;
- (void)addScreenFillRect:(struct CGContext *)arg1 rect:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

