//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSString, UIView;

@interface SFApplyViewController : BaseViewController
{
    NSString *_content;
    UIView *_noDataView;
}

@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)createNoDataView;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 Content:(id)arg2;

@end

