//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface SFAttendanceTableViewCell : UITableViewCell
{
    id <SFAttendanceTableViewCellDelegate> _delegate;
    UIView *_bgView;
    UIImageView *_iconImgView;
    UILabel *_attendanceTitleLabel;
    UILabel *_attendanceDescriptionLabel;
    UIButton *_attendanceBtn;
}

@property(retain, nonatomic) UIButton *attendanceBtn; // @synthesize attendanceBtn=_attendanceBtn;
@property(retain, nonatomic) UILabel *attendanceDescriptionLabel; // @synthesize attendanceDescriptionLabel=_attendanceDescriptionLabel;
@property(retain, nonatomic) UILabel *attendanceTitleLabel; // @synthesize attendanceTitleLabel=_attendanceTitleLabel;
@property(retain, nonatomic) UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak id <SFAttendanceTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)attendanceButtonEvent:(id)arg1;
- (void)setContentInfoWithDictionary:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;

@end

