//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, NSTimer, SFCustomTextField, UIButton, UIView;

@interface SFBindingOfAcountViewController : BaseViewController <UITextFieldDelegate>
{
    int _interval;
    int index;
    _Bool _isChange;
    UIView *_normalLoginView;
    UIView *_phoneLoginView;
    UIView *_redScrollView;
    UIButton *_getVerifyBt;
    UIButton *_forgetPasswordBt;
    UIButton *_bindingBt;
    UIButton *_selectPhoneLoginBt;
    UIButton *_selectNormalLoginBt;
    SFCustomTextField *_phoneNumberTextField;
    SFCustomTextField *_verifyNumberTextField;
    SFCustomTextField *_acountTextField;
    SFCustomTextField *_passwordTextField;
    NSString *_buttonTitle;
    NSString *_warningTitle;
    NSTimer *_countDownTimer;
}

@property(retain, nonatomic) NSTimer *countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(copy, nonatomic) NSString *warningTitle; // @synthesize warningTitle=_warningTitle;
@property(copy, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) SFCustomTextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) SFCustomTextField *acountTextField; // @synthesize acountTextField=_acountTextField;
@property(retain, nonatomic) SFCustomTextField *verifyNumberTextField; // @synthesize verifyNumberTextField=_verifyNumberTextField;
@property(retain, nonatomic) SFCustomTextField *phoneNumberTextField; // @synthesize phoneNumberTextField=_phoneNumberTextField;
@property(retain, nonatomic) UIButton *selectNormalLoginBt; // @synthesize selectNormalLoginBt=_selectNormalLoginBt;
@property(retain, nonatomic) UIButton *selectPhoneLoginBt; // @synthesize selectPhoneLoginBt=_selectPhoneLoginBt;
@property(retain, nonatomic) UIButton *bindingBt; // @synthesize bindingBt=_bindingBt;
@property(retain, nonatomic) UIButton *forgetPasswordBt; // @synthesize forgetPasswordBt=_forgetPasswordBt;
@property(retain, nonatomic) UIButton *getVerifyBt; // @synthesize getVerifyBt=_getVerifyBt;
@property(retain, nonatomic) UIView *redScrollView; // @synthesize redScrollView=_redScrollView;
@property(retain, nonatomic) UIView *phoneLoginView; // @synthesize phoneLoginView=_phoneLoginView;
@property(retain, nonatomic) UIView *normalLoginView; // @synthesize normalLoginView=_normalLoginView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)setBindingBtStateWithFirstFilledText:(id)arg1 secondWillFillText:(id)arg2 inputStr:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)timerCountdown:(id)arg1;
- (void)timerStop;
- (void)timerStart;
- (void)phoneLoginBindingFangFailWithResponseItem:(id)arg1;
- (void)phoneLoginBindingFangSuccessWithResponseItem:(id)arg1;
- (void)normalLoginBindingFangFailWithResponseItem:(id)arg1;
- (void)normalLoginBindingFangSuccessWithResponseItem:(id)arg1;
- (void)sentToGetUserInfoWithResponseItem:(id)arg1;
- (void)requestDataWithisChange:(_Bool)arg1 index:(int)arg2;
- (void)requestFangVerifyCodeFailWithResponseItem:(id)arg1;
- (void)requestFangVerifyCodeSuccessWithResponseItem:(id)arg1;
- (void)requestVerifyCode;
- (void)registerFangAcount;
- (void)createRegisterItem;
- (void)getVerifyNumber;
- (void)forgetPassword;
- (void)bingdingFangAcount;
- (void)chooseBindingWay:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)customUI;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 buttonTitle:(id)arg2 warningTitle:(id)arg3 isChange:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

