//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSCalendar, NSDateComponents, UIButton, UILabel, UITextField;

@interface SFCalendarView : UIView
{
    long long _year;
    long long _month;
    long long _day;
    UITextField *_responsTextfiled;
    id <SFCalendarDelegate> _delegate;
    UIView *_calBlackGroundView;
    UILabel *_timeLabel;
    UILabel *_yearLabel;
    UILabel *_monthLabel;
    UILabel *_dayLabel;
    UIButton *_yearAdd;
    UIButton *_yearSub;
    UIButton *_monthAdd;
    UIButton *_monthSub;
    UIButton *_dayAdd;
    UIButton *_daySub;
    UIView *_buttonBackgroundView;
    UIButton *_sureBt;
    UIButton *_cancelBt;
    UIButton *_clearBt;
    NSDateComponents *_dateComp;
    NSCalendar *_calendar;
}

@property(retain, nonatomic) NSCalendar *calendar; // @synthesize calendar=_calendar;
@property(retain, nonatomic) NSDateComponents *dateComp; // @synthesize dateComp=_dateComp;
@property(retain, nonatomic) UIButton *clearBt; // @synthesize clearBt=_clearBt;
@property(retain, nonatomic) UIButton *cancelBt; // @synthesize cancelBt=_cancelBt;
@property(retain, nonatomic) UIButton *sureBt; // @synthesize sureBt=_sureBt;
@property(retain, nonatomic) UIView *buttonBackgroundView; // @synthesize buttonBackgroundView=_buttonBackgroundView;
@property(retain, nonatomic) UIButton *daySub; // @synthesize daySub=_daySub;
@property(retain, nonatomic) UIButton *dayAdd; // @synthesize dayAdd=_dayAdd;
@property(retain, nonatomic) UIButton *monthSub; // @synthesize monthSub=_monthSub;
@property(retain, nonatomic) UIButton *monthAdd; // @synthesize monthAdd=_monthAdd;
@property(retain, nonatomic) UIButton *yearSub; // @synthesize yearSub=_yearSub;
@property(retain, nonatomic) UIButton *yearAdd; // @synthesize yearAdd=_yearAdd;
@property(retain, nonatomic) UILabel *dayLabel; // @synthesize dayLabel=_dayLabel;
@property(retain, nonatomic) UILabel *monthLabel; // @synthesize monthLabel=_monthLabel;
@property(retain, nonatomic) UILabel *yearLabel; // @synthesize yearLabel=_yearLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIView *calBlackGroundView; // @synthesize calBlackGroundView=_calBlackGroundView;
@property(nonatomic) __weak id <SFCalendarDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITextField *responsTextfiled; // @synthesize responsTextfiled=_responsTextfiled;
- (void).cxx_destruct;
- (void)bottomBtnAct:(id)arg1;
- (long long)numberOfDaysInMonth:(long long)arg1 withYear:(long long)arg2;
- (void)clickTimeChange:(id)arg1;
- (id)weekWithWeekIndex:(long long)arg1;
- (void)setLabelText:(long long)arg1 monthLabel:(long long)arg2 dayLabel:(long long)arg3 weekDay:(long long)arg4;
- (id)dateWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
- (void)refreshDateInfo:(id)arg1;
- (unsigned long long)unit;
- (void)addTapGestureRecognizer;
- (void)opacityToShow:(id)arg1 from:(id)arg2 to:(id)arg3;
- (void)remove;
- (void)showOn:(id)arg1;
- (void)shakeToShow:(id)arg1;
- (void)customUI;
- (id)initNibViewWithDay:(long long)arg1;

@end

