//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSString, UILabel;

@interface SFDrawCashResultViewController : BaseViewController
{
    NSString *_cardNum;
    NSString *_drawCashNum;
    NSString *_payType;
    UILabel *_gongzikaNumberLabel;
    UILabel *_tixianjineResultNumberLabel;
    UILabel *_gongzikaNameLabel;
}

@property(retain, nonatomic) UILabel *gongzikaNameLabel; // @synthesize gongzikaNameLabel=_gongzikaNameLabel;
@property(retain, nonatomic) UILabel *tixianjineResultNumberLabel; // @synthesize tixianjineResultNumberLabel=_tixianjineResultNumberLabel;
@property(retain, nonatomic) UILabel *gongzikaNumberLabel; // @synthesize gongzikaNumberLabel=_gongzikaNumberLabel;
@property(retain, nonatomic) NSString *payType; // @synthesize payType=_payType;
@property(retain, nonatomic) NSString *drawCashNum; // @synthesize drawCashNum=_drawCashNum;
@property(retain, nonatomic) NSString *cardNum; // @synthesize cardNum=_cardNum;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)wanchengActEvent:(id)arg1;
- (void)goBackAction;
- (void)createLeftNavigationBtn;
- (void)creatDrawResultView;
- (void)viewDidLoad;

@end

