//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SFGlobalAlertView;

@protocol SFGlobalAlertViewDelegate <NSObject>

@optional
- (void)didDismissGlobalAlertView:(SFGlobalAlertView *)arg1;
- (void)globalAlertView:(SFGlobalAlertView *)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)globalAlertView:(SFGlobalAlertView *)arg1 clickedButtonIndex:(long long)arg2;
@end

