//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RefreshTableViewController.h"

#import "SFSeniorSecondTableViewCellDelegate.h"

@class MainVC_ElementItem, NSMutableArray, NSString, UIView;

@interface SFGroupTodoViewController : RefreshTableViewController <SFSeniorSecondTableViewCellDelegate>
{
    NSMutableArray *_dataArray;
    MainVC_ElementItem *_currentItem;
    NSString *_status;
    UIView *_tapRefreshBackView;
}

@property(retain, nonatomic) UIView *tapRefreshBackView; // @synthesize tapRefreshBackView=_tapRefreshBackView;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) MainVC_ElementItem *currentItem; // @synthesize currentItem=_currentItem;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (void)seniorSecondTableViewCell:(id)arg1 didSelectedWithItem:(id)arg2;
- (void)tapToRefreshCurrentPage:(id)arg1;
- (void)removeTapRefreshViewFromContentView;
- (void)creatTapRefreshView;
- (void)tableHeaderButtonEvent:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)attributedStringWithString:(id)arg1 color:(id)arg2;
- (void)sendCompanyTodoContentInitRequestFailWithItem:(id)arg1;
- (void)sendCompanyTodoContentInitRequestSuccessWithItem:(id)arg1;
- (void)requestNetData;
- (void)sendRequestToServer;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithElementItem:(id)arg1 status:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

