//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "SFEmailViewDelegate.h"
#import "SFManagerContentViewControllerDelegate.h"
#import "SFNormalMainViewControllerDelegate.h"
#import "SFSeniorViewControllerDelegate.h"

@class DXPopover, NSMutableArray, NSString, SFEmailView, SFSeniorViewController, SFTabChangeViewController, UILabel, UIView;

@interface SFHomeViewController : BaseViewController <SFEmailViewDelegate, SFNormalMainViewControllerDelegate, SFSeniorViewControllerDelegate, SFManagerContentViewControllerDelegate>
{
    SFTabChangeViewController *_tabVC;
    SFSeniorViewController *_seniorVC;
    BaseViewController *_currentVC;
    NSMutableArray *_vcArray;
    UIView *_menuView0;
    UIView *_menuView;
    DXPopover *_menuPopover;
    long long _emailViewType;
    UIView *_leftItemBackgroundView;
    UILabel *_cycleDotLable;
    UILabel *_haveUnreadCycle;
    SFEmailView *_emailView;
    NSString *_leftButtonTitle;
    NSString *_rightButtonTitle;
    NSString *_emailAcount;
    NSString *_emailPwd;
    NSString *_unreadCount;
}

@property(copy, nonatomic) NSString *unreadCount; // @synthesize unreadCount=_unreadCount;
@property(copy, nonatomic) NSString *emailPwd; // @synthesize emailPwd=_emailPwd;
@property(copy, nonatomic) NSString *emailAcount; // @synthesize emailAcount=_emailAcount;
@property(copy, nonatomic) NSString *rightButtonTitle; // @synthesize rightButtonTitle=_rightButtonTitle;
@property(copy, nonatomic) NSString *leftButtonTitle; // @synthesize leftButtonTitle=_leftButtonTitle;
@property(retain, nonatomic) SFEmailView *emailView; // @synthesize emailView=_emailView;
@property(retain, nonatomic) UILabel *haveUnreadCycle; // @synthesize haveUnreadCycle=_haveUnreadCycle;
@property(retain, nonatomic) UILabel *cycleDotLable; // @synthesize cycleDotLable=_cycleDotLable;
@property(retain, nonatomic) UIView *leftItemBackgroundView; // @synthesize leftItemBackgroundView=_leftItemBackgroundView;
@property(nonatomic) long long emailViewType; // @synthesize emailViewType=_emailViewType;
@property(retain, nonatomic) DXPopover *menuPopover; // @synthesize menuPopover=_menuPopover;
@property(retain, nonatomic) UIView *menuView; // @synthesize menuView=_menuView;
@property(retain, nonatomic) UIView *menuView0; // @synthesize menuView0=_menuView0;
@property(retain, nonatomic) NSMutableArray *vcArray; // @synthesize vcArray=_vcArray;
@property(retain, nonatomic) BaseViewController *currentVC; // @synthesize currentVC=_currentVC;
@property(retain, nonatomic) SFSeniorViewController *seniorVC; // @synthesize seniorVC=_seniorVC;
@property(nonatomic) __weak SFTabChangeViewController *tabVC; // @synthesize tabVC=_tabVC;
- (void).cxx_destruct;
- (void)dealloc;
- (void)reloadEmailData;
- (void)emailView:(id)arg1 clickedWithEmailViewType:(long long)arg2;
- (void)changeBtnWithIndex:(long long)arg1;
- (void)openWorkflow;
- (void)getWorkflowIdFailWithItem:(id)arg1;
- (void)getWorkflowIdSucessWithItem:(id)arg1;
- (void)creatLeaveWorkFlow;
- (void)addApplyBtnAction:(id)arg1;
- (void)changeView;
- (long long)userLevel;
- (void)emailLogin;
- (void)oneOfMenuBeSelected:(id)arg1;
- (void)createMenu;
- (void)creatRightBtn;
- (void)createUI;
- (void)initData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)requestEmailLoginMessageFailWithResponseItem:(id)arg1;
- (void)requestEmailLoginMessageSuccessWithResponseItem:(id)arg1;
- (void)getEmailUnreadCount;
- (void)getWorkflowIdFail:(id)arg1;
- (void)getWorkflowIdSuccess:(id)arg1;
- (void)getWorkflowId;
- (void)viewWillAppear:(_Bool)arg1;
- (void)getEmailAccountChangeNotification:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

