//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SFLocationItem : NSObject
{
    NSString *_coordName;
    NSString *_distance;
    NSString *_longitude;
    NSString *_latitude;
    NSString *_companyId;
}

@property(retain, nonatomic) NSString *companyId; // @synthesize companyId=_companyId;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *coordName; // @synthesize coordName=_coordName;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

