//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SFNetworkinfHandleDelegate.h"

@class NSString;

@interface SFLoginMethod : NSObject <SFNetworkinfHandleDelegate>
{
    NSString *_checkCode;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSString *checkCode; // @synthesize checkCode=_checkCode;
- (void).cxx_destruct;
- (id)getAuthCodeWithURL:(id)arg1;
- (void)applicationOpenURL:(id)arg1 delegate:(id)arg2;
- (_Bool)automaticLoginWithAuthCode:(id)arg1 finishedBlock:(CDUnknownBlockType)arg2;
- (void)networkingHandleWithcheckCode:(id)arg1;
- (void)loadLoginPage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

