//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "SFLockScreenDelegate.h"
#import "SFPasswordVerifyAlertViewDelegate.h"

@class NSNumber, NSString, SFLockScreen, UIButton, UILabel, UIView;

@interface SFLockViewController : BaseViewController <SFLockScreenDelegate, SFPasswordVerifyAlertViewDelegate>
{
    UIView *_naviBarView;
    UIView *_contentView;
    UIButton *_backBtn;
    UILabel *_titleLabel;
    UIView *_lockBgView;
    UILabel *_promptLabel;
    UIButton *_resetButton;
    SFLockScreen *_lockView;
    long long _type;
    NSNumber *_patternNumber;
}

@property(retain, nonatomic) NSNumber *patternNumber; // @synthesize patternNumber=_patternNumber;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) SFLockScreen *lockView; // @synthesize lockView=_lockView;
@property(nonatomic) __weak UIButton *resetButton; // @synthesize resetButton=_resetButton;
@property(nonatomic) __weak UILabel *promptLabel; // @synthesize promptLabel=_promptLabel;
@property(nonatomic) __weak UIView *lockBgView; // @synthesize lockBgView=_lockBgView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *naviBarView; // @synthesize naviBarView=_naviBarView;
- (void).cxx_destruct;
- (void)lockScreen:(id)arg1 didEndWithPattern:(id)arg2;
- (void)sendVerifyPasswordRequestFailWithItem:(id)arg1;
- (void)sendVerifyPasswordRequestSuccessWithItem:(id)arg1;
- (void)pwVerifyAlertView:(id)arg1 inputText:(id)arg2;
- (void)resetPasswordEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)backAction:(id)arg1;
- (void)initContentView;
- (void)viewDidLoad;
- (id)initWithType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

