//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SFNetworkinfHandle : NSObject
{
    CDUnknownBlockType _block;
    CDUnknownBlockType _automaticLoginFailedBlock;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType automaticLoginFailedBlock; // @synthesize automaticLoginFailedBlock=_automaticLoginFailedBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)requestWithRequestBaseURLString:(id)arg1 paramString:(id)arg2;
- (void)requestLoginAgainWithURLString:(id)arg1 paramString:(id)arg2 finishedBlock:(CDUnknownBlockType)arg3;
- (void)requestCheckCodeWithBaseURLString:(id)arg1 paramString:(id)arg2 delegate:(id)arg3;

@end

