//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSData, NSString, SFTabChangeViewController, UILabel;

@interface SFOAScanResultViewController : BaseViewController
{
    long long retcode;
    long long groupNum;
    NSString *groupName;
    NSData *imgUrlData;
    UILabel *warnLabel;
    int _type;
    SFTabChangeViewController *_tabVC;
    NSString *_string;
    NSString *_URLstr;
    NSString *_sUUID;
    NSString *_GroupID;
    NSString *_CreaterIMUsername;
    NSString *_scanQRLoginType;
}

@property(retain, nonatomic) NSString *scanQRLoginType; // @synthesize scanQRLoginType=_scanQRLoginType;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *CreaterIMUsername; // @synthesize CreaterIMUsername=_CreaterIMUsername;
@property(retain, nonatomic) NSString *GroupID; // @synthesize GroupID=_GroupID;
@property(retain, nonatomic) NSString *sUUID; // @synthesize sUUID=_sUUID;
@property(retain, nonatomic) NSString *URLstr; // @synthesize URLstr=_URLstr;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
@property(retain, nonatomic) SFTabChangeViewController *tabVC; // @synthesize tabVC=_tabVC;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)joinGroupRet:(id)arg1;
- (void)joinGroupBtnClick:(id)arg1;
- (void)returnReadyGroupInfoFail:(id)arg1;
- (void)returnReadyGroupInfoSuccess:(id)arg1;
- (void)requestReadyJoinGroup:(id)arg1;
- (id)warnLabelText:(long long)arg1;
- (void)creatJoinButton;
- (void)returnLoginDataFail:(id)arg1;
- (void)returnLoginDataSuccess:(id)arg1;
- (void)requestLogin:(id)arg1;
- (void)loginbtnClick:(id)arg1;
- (void)creatLoginView;
- (void)returnInfoFail:(id)arg1;
- (void)returnInfoSuccess:(id)arg1;
- (void)requestLoginInfo:(id)arg1;
- (struct CGSize)preperHeighWithLabel:(id)arg1;
- (void)creatLabelView;
- (_Bool)dealWithScannedResultString:(id)arg1;
- (id)imgCIQRCodeZBar:(id)arg1;
- (id)imgCIQRCodeFeature:(id)arg1;
- (void)btnClickCancel:(id)arg1;
- (void)backForward;
- (void)createBackButton;
- (void)webViewAlertAction:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

