//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SFOrganizationModel : NSObject
{
    NSString *checked;
    NSString *_businessID;
    NSString *_name;
    NSString *_type;
    NSString *_hasSubOrg;
    NSString *_parentDepId;
    NSString *_parentSubId;
    NSString *_parentID;
    NSString *_uniqueID;
    NSString *_hierarchy;
    long long _state;
    NSString *_torder;
}

@property(copy, nonatomic) NSString *torder; // @synthesize torder=_torder;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *hierarchy; // @synthesize hierarchy=_hierarchy;
@property(copy, nonatomic) NSString *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(copy, nonatomic) NSString *parentID; // @synthesize parentID=_parentID;
@property(copy, nonatomic) NSString *parentSubId; // @synthesize parentSubId=_parentSubId;
@property(copy, nonatomic) NSString *parentDepId; // @synthesize parentDepId=_parentDepId;
@property(copy, nonatomic) NSString *hasSubOrg; // @synthesize hasSubOrg=_hasSubOrg;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *businessID; // @synthesize businessID=_businessID;
- (void).cxx_destruct;
- (id)configureWithOrganizationEntity:(id)arg1;
- (id)init;

@end

