//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "SFGlobalAlertViewDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, SFTabChangeViewController, UILabel, UITextView, UIView;

@interface SFPersonalProfileSignatureViewController : BaseViewController <UITextViewDelegate, SFGlobalAlertViewDelegate>
{
    _Bool isBlank;
    id <SFPersonalProfileSignatureViewControllerDelegate> _delegate;
    NSString *_profileSignature;
    SFTabChangeViewController *_tabVC;
    long long _existTextNum;
    UIView *_contentView;
    UITextView *_contentTextView;
    UILabel *_characterNumLabel;
    NSString *_uploadSignStr;
}

@property(retain, nonatomic) NSString *uploadSignStr; // @synthesize uploadSignStr=_uploadSignStr;
@property(retain, nonatomic) UILabel *characterNumLabel; // @synthesize characterNumLabel=_characterNumLabel;
@property(retain, nonatomic) UITextView *contentTextView; // @synthesize contentTextView=_contentTextView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long existTextNum; // @synthesize existTextNum=_existTextNum;
@property(nonatomic) __weak SFTabChangeViewController *tabVC; // @synthesize tabVC=_tabVC;
@property(retain, nonatomic) NSString *profileSignature; // @synthesize profileSignature=_profileSignature;
@property(nonatomic) __weak id <SFPersonalProfileSignatureViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)convertToInt:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)sendUserSinatureFail:(id)arg1;
- (void)goBackViewController;
- (void)sendUserSinatureSuccess:(id)arg1;
- (void)globalAlertView:(id)arg1 clickedButtonIndex:(long long)arg2;
- (void)saveButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)customUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

