//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, SFPersonalSuggestionViewController, UITableView;

@interface SFProductBottomListView : UIView <UITableViewDataSource, UITableViewDelegate>
{
    UIView *botmview;
    SFPersonalSuggestionViewController *_perSugVC;
    UITableView *_productTablewView;
}

@property(retain, nonatomic) UITableView *productTablewView; // @synthesize productTablewView=_productTablewView;
@property(retain, nonatomic) SFPersonalSuggestionViewController *perSugVC; // @synthesize perSugVC=_perSugVC;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)cellLineOn:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)cancelACtion:(id)arg1;
- (void)creatProductListTablewview;
- (void)creatUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

