//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class SFProcessDetailListItem, UIImageView, UILabel, UIView;

@interface SFProcessDetailsViewControllerCell : UITableViewCell
{
    _Bool _isFirst;
    _Bool _isLast;
    SFProcessDetailListItem *_processDetailListItem;
    UILabel *_titleLabel;
    UILabel *_remarkLabel;
    UILabel *_timeLabel;
    UIView *_leftLineView;
    UIView *_downLineView;
    UIImageView *_imgView;
    UILabel *_presentTitleLabel;
    UIView *_contentBackView;
    UILabel *_tipInfoLabel;
    UIImageView *_isMobileImageView;
}

@property(retain, nonatomic) UIImageView *isMobileImageView; // @synthesize isMobileImageView=_isMobileImageView;
@property(retain, nonatomic) UILabel *tipInfoLabel; // @synthesize tipInfoLabel=_tipInfoLabel;
@property(retain, nonatomic) UIView *contentBackView; // @synthesize contentBackView=_contentBackView;
@property(retain, nonatomic) UILabel *presentTitleLabel; // @synthesize presentTitleLabel=_presentTitleLabel;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) UIView *downLineView; // @synthesize downLineView=_downLineView;
@property(retain, nonatomic) UIView *leftLineView; // @synthesize leftLineView=_leftLineView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *remarkLabel; // @synthesize remarkLabel=_remarkLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) SFProcessDetailListItem *processDetailListItem; // @synthesize processDetailListItem=_processDetailListItem;
@property(nonatomic) _Bool isLast; // @synthesize isLast=_isLast;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
- (void).cxx_destruct;
- (double)getHeight:(id)arg1 SizeFont:(id)arg2 size:(struct CGSize)arg3;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

