//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MainVC_ElementItem, SFSeniorThirdTableViewCell;

@protocol SFSeniorThirdTableViewCellDelegate <NSObject>
- (void)seniorThirdTableViewCell:(SFSeniorThirdTableViewCell *)arg1 didSelectedWithItem:(MainVC_ElementItem *)arg2;
@end

