//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RefreshTableViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UITextField, UIView;

@interface SFSearchPlaceViewController : RefreshTableViewController <UITextFieldDelegate>
{
    id <SFSearchPlaceViewControllerDelegate> _delegate;
    UIView *_searchBarBgView;
    UITextField *_textField;
    NSString *_longitude;
    NSString *_latitude;
}

@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIView *searchBarBgView; // @synthesize searchBarBgView=_searchBarBgView;
@property(nonatomic) __weak id <SFSearchPlaceViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)textFieldTextDidChangeNotification:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)sendSearchAttendancePlaceRequestFailWithItem:(id)arg1;
- (void)sendSearchAttendancePlaceRequestSuccessWithItem:(id)arg1;
- (void)sendRequestToServer;
- (void)goBackEvent;
- (void)setupSearchView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithLongitude:(id)arg1 latitude:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

