//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RefreshTableViewController.h"

#import "SFSeniorSecondTableViewCellDelegate.h"
#import "SFSeniorThirdTableViewCellDelegate.h"

@class NSArray, NSString;

@interface SFSeniorContentViewController : RefreshTableViewController <SFSeniorSecondTableViewCellDelegate, SFSeniorThirdTableViewCellDelegate>
{
    NSArray *_dataArray;
    id <SFSeniorContentViewControllerDelegate> _delegate;
    NSString *_status;
    struct CGRect _frame;
}

@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) __weak id <SFSeniorContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (void)seniorThirdTableViewCell:(id)arg1 didSelectedWithItem:(id)arg2;
- (void)seniorSecondTableViewCell:(id)arg1 didSelectedWithItem:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)sendRequestToServer;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1 frame:(struct CGRect)arg2 status:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

