//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UISwitch;

@interface SFSetterTableViewCell : UITableViewCell
{
    id <SFSetterTableViewCellDelegate> _delegate;
    UILabel *_nameLabel;
    UIImageView *_rightArrowImageView;
    UISwitch *_cellSwitch;
    UILabel *_remindCycleLable;
}

@property(retain, nonatomic) UILabel *remindCycleLable; // @synthesize remindCycleLable=_remindCycleLable;
@property(retain, nonatomic) UISwitch *cellSwitch; // @synthesize cellSwitch=_cellSwitch;
@property(retain, nonatomic) UIImageView *rightArrowImageView; // @synthesize rightArrowImageView=_rightArrowImageView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak id <SFSetterTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)switchChanged:(id)arg1;
- (void)isHideRightArrowAndSetDetailTitle:(id)arg1;
- (void)didShowSwitch:(_Bool)arg1 withSwitchStatus:(_Bool)arg2 andRemindCycleLable:(_Bool)arg3;
- (void)setSetterCellTitle:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)creatContentView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;

@end

