//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSString, UITableView;

@interface SFTaxPlanResultViewController : BaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSString *_hrmsalarydetailidFromMoneyVC;
    UITableView *_salaryTableview;
    NSDictionary *_salaryDataDic;
}

@property(retain, nonatomic) NSDictionary *salaryDataDic; // @synthesize salaryDataDic=_salaryDataDic;
@property(retain, nonatomic) UITableView *salaryTableview; // @synthesize salaryTableview=_salaryTableview;
@property(copy, nonatomic) NSString *hrmsalarydetailidFromMoneyVC; // @synthesize hrmsalarydetailidFromMoneyVC=_hrmsalarydetailidFromMoneyVC;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)creatSalaryTableviewCell:(id)arg1 withLine:(_Bool)arg2 indexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)returnSalaryDataFail:(id)arg1;
- (void)returnSalaryDataSuccess:(id)arg1;
- (void)createUserInterface;
- (void)sendRequestToServer;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

