//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "SFCalendarDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, SFCalendarView, UIButton, UIScrollView, UITextField, UIView;

@interface SFTitleSearchViewController : BaseViewController <UITextFieldDelegate, SFCalendarDelegate>
{
    long long _type;
    id <SFTitleSearchViewControllerDelegate> _delegate;
    UIScrollView *_scrollView;
    UIView *_backGroundView;
    UIView *_topview;
    UITextField *_titleTxtFed;
    UITextField *_starTimeTxtFed;
    UITextField *_endTimeTxtFed;
    UIButton *_searchBtn;
    SFCalendarView *_calenView;
}

@property(retain, nonatomic) SFCalendarView *calenView; // @synthesize calenView=_calenView;
@property(retain, nonatomic) UIButton *searchBtn; // @synthesize searchBtn=_searchBtn;
@property(retain, nonatomic) UITextField *endTimeTxtFed; // @synthesize endTimeTxtFed=_endTimeTxtFed;
@property(retain, nonatomic) UITextField *starTimeTxtFed; // @synthesize starTimeTxtFed=_starTimeTxtFed;
@property(retain, nonatomic) UITextField *titleTxtFed; // @synthesize titleTxtFed=_titleTxtFed;
@property(retain, nonatomic) UIView *topview; // @synthesize topview=_topview;
@property(retain, nonatomic) UIView *backGroundView; // @synthesize backGroundView=_backGroundView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <SFTitleSearchViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)sendTimeString:(id)arg1 toTextField:(id)arg2;
- (void)textFieldBtnAct:(id)arg1;
- (void)searchBtnAction:(id)arg1;
- (void)BackFoward;
- (void)didReceiveMemoryWarning;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (id)currentTime:(long long)arg1;
- (void)creatScrollView;
- (void)tapAction;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

