//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface SlideTableViewCell : UITableViewCell <UIGestureRecognizerDelegate>
{
    struct CGPoint startTouchPoint;
    _Bool isOpen;
    _Bool _isMoving;
    id _observerTarget;
    id _observedTarget;
    NSString *_observedKey;
    UIView *_myContentView;
    UIView *_myBottomView;
    UIPanGestureRecognizer *_panRecognizer;
    UITapGestureRecognizer *_tapRecognizer;
}

@property(nonatomic) _Bool isMoving; // @synthesize isMoving=_isMoving;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(retain, nonatomic) UIView *myBottomView; // @synthesize myBottomView=_myBottomView;
@property(retain, nonatomic) UIView *myContentView; // @synthesize myContentView=_myContentView;
@property(retain, nonatomic) NSString *observedKey; // @synthesize observedKey=_observedKey;
@property(nonatomic) __weak id observedTarget; // @synthesize observedTarget=_observedTarget;
@property(nonatomic) __weak id observerTarget; // @synthesize observerTarget=_observerTarget;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)moveViewWithOffsetX:(double)arg1;
- (void)paningGestureReceive:(id)arg1;
- (void)setDrawEnable:(_Bool)arg1;
- (void)hidenBottomViewAnimation:(_Bool)arg1;
- (id)bottomViewWithContentView;
- (double)bottomViewTotalWidth;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithReuseIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

