//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class AsyncImageView, UIButton, UIImageView;

@interface SouFunIMTongZhiTopCollectionViewCell : UICollectionViewCell
{
    AsyncImageView *_portraitImageView;
    UIImageView *_imageView;
    UIButton *_nameTitleBtn;
}

@property(retain, nonatomic) UIButton *nameTitleBtn; // @synthesize nameTitleBtn=_nameTitleBtn;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) AsyncImageView *portraitImageView; // @synthesize portraitImageView=_portraitImageView;
- (void).cxx_destruct;
- (struct CGSize)calculateHeightAndWidth:(id)arg1 fontNumber:(float)arg2 maxHeight:(float)arg3 maxWidth:(float)arg4;
- (void)headImageView:(id)arg1 andTextString:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

