//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSTimer;

@interface SouFunIMPlayVoiceAnimationView : UIImageView
{
    _Bool isFromSelf;
    NSTimer *timer;
    long long count;
    double timeInterval;
}

@property(nonatomic) _Bool isFromSelf; // @synthesize isFromSelf;
@property(nonatomic) double timeInterval; // @synthesize timeInterval;
@property(nonatomic) long long count; // @synthesize count;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)beginPlay;
- (void)beginAnimation;
- (id)initWithFrame:(struct CGRect)arg1 andTimeInterval:(double)arg2 fromeSelf:(_Bool)arg3;

@end

