//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SouFunIMTongZhiShareValue : NSObject
{
    NSMutableArray *_tongZhiArray;
}

+ (id)shareManager;
@property(retain, nonatomic) NSMutableArray *tongZhiArray; // @synthesize tongZhiArray=_tongZhiArray;
- (void).cxx_destruct;
- (id)init;

@end

