//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SFImageCropperDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class AsyncImageView, MBProgressHUD, NSString, SouFunIMUpLoadImageView, UIActionSheet, UIImage, UIImageView;

@interface SouFunIMGroupImageViewController : UIViewController <UIActionSheetDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, SFImageCropperDelegate, UIGestureRecognizerDelegate>
{
    double lastScale;
    _Bool doupleTapClick;
    struct CGRect oldframe;
    _Bool _isGroupManager;
    _Bool _isGroupAdministrator;
    AsyncImageView *_groupImageView;
    NSString *_groupID;
    UIImageView *_imageView;
    UIActionSheet *_photoActionSheet;
    MBProgressHUD *_hud;
    SouFunIMUpLoadImageView *_uploadImage;
    UIImageView *_groupImage;
    UIImage *_selectImage;
}

@property(retain, nonatomic) UIImage *selectImage; // @synthesize selectImage=_selectImage;
@property(retain, nonatomic) UIImageView *groupImage; // @synthesize groupImage=_groupImage;
@property(retain, nonatomic) SouFunIMUpLoadImageView *uploadImage; // @synthesize uploadImage=_uploadImage;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
@property(retain, nonatomic) UIActionSheet *photoActionSheet; // @synthesize photoActionSheet=_photoActionSheet;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(nonatomic) _Bool isGroupAdministrator; // @synthesize isGroupAdministrator=_isGroupAdministrator;
@property(nonatomic) _Bool isGroupManager; // @synthesize isGroupManager=_isGroupManager;
@property(retain, nonatomic) AsyncImageView *groupImageView; // @synthesize groupImageView=_groupImageView;
- (void).cxx_destruct;
- (id)imageByScalingAndCroppingForSourceImage:(id)arg1 targetSize:(struct CGSize)arg2;
- (id)imageByScalingToMaxSize:(id)arg1;
- (_Bool)cameraSupportsMedia:(id)arg1 sourceType:(long long)arg2;
- (_Bool)canUserPickPhotosFromPhotoLibrary;
- (_Bool)canUserPickVideosFromPhotoLibrary;
- (_Bool)isPhotoLibraryAvailable;
- (_Bool)doesCameraSupportTakingPhotos;
- (_Bool)isFrontCameraAvailable;
- (_Bool)isRealCameraAvailable;
- (_Bool)isCameraAvailable;
- (void)imageCropperDidCancel:(id)arg1;
- (void)imageCropper:(id)arg1 didFinished:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)changeGroupPicture:(id)arg1;
- (void)imageSavedToPhotosAlbum:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)editPortrait;
- (void)moreActionSheet;
- (void)back;
- (void)createRinghtItems;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)panGesture:(id)arg1;
- (void)scaGesture:(id)arg1;
- (void)doubleTapRecognizer:(id)arg1;
- (void)createUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

