//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKLocationServiceDelegate.h"
#import "BMKMapViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class BMKGeoCodeSearch, BMKLocationService, BMKMapView, BMKPoiInfo, NSMutableArray, NSString, UIAlertView, UIButton, UILabel, UIView;

@interface SouFunIMMapSharePositionViewController : UIViewController <UIAlertViewDelegate, BMKMapViewDelegate, BMKLocationServiceDelegate, BMKGeoCodeSearchDelegate>
{
    UIView *_contentView;
    UIButton *_dingweiButton;
    UIAlertView *_alertView;
    UILabel *_positionLabel;
    UILabel *_addressLabel;
    BMKMapView *_mapView;
    BMKLocationService *_locService;
    BMKGeoCodeSearch *_geocodesearch;
    struct CLLocationCoordinate2D _currentPosition;
    CDStruct_951efa70 _currentSpan;
    _Bool _notRunOnceFlag;
    NSString *_netWorkStatus;
    NSMutableArray *_aroundPositionsArr;
    BMKPoiInfo *_sendPoi;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)authorizationStatus;
- (id)getImageWithFrame:(struct CGRect)arg1;
- (void)didReceiveMemoryWarning;
- (void)sendOrCancleBtnPress:(id)arg1;
- (void)createNavItemBtns;
- (void)createUI;
- (void)gotoCurrentPosition;
- (id)getAroundPositionSortArrayWithCoordinate:(struct CLLocationCoordinate2D)arg1;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)searchAroundPositionsWithCoordinate2D:(struct CLLocationCoordinate2D)arg1;
- (void)didFailToLocateUserWithError:(id)arg1;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)didUpdateUserHeading:(id)arg1;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)initMapService;
- (void)initMapView;
- (void)viewDidLoad;
- (void)netWorkChange:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)enterBackground;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

