//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSString;

@interface SouFunIMContactGroup : NSManagedObject
{
}

+ (void)updateContactGroupWithDic:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)selectContactGroupByTeamName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)deleteContactGroupByTeamName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)deleteDataAboutContactGroupByTeamName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)insertNewContactGroupWithDic:(id)arg1 inManagedObjectContext:(id)arg2;

// Remaining properties
@property(nonatomic) _Bool isDelete; // @dynamic isDelete;
@property(retain, nonatomic) NSString *myName; // @dynamic myName;
@property(retain, nonatomic) NSString *teamCount; // @dynamic teamCount;
@property(retain, nonatomic) NSString *teamName; // @dynamic teamName;

@end

