//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FPPopoverController, MBProgressHUD, NSMutableArray, NSString, SouFunIMChatListModel, SouFunIMNotificationListModel, SouFunIMPlayVoiceAnimationView, UIButton, UILabel, UITableView, UIView;

@interface SouFunIMNotificationListController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIAlertViewDelegate>
{
    int _tittleType;
    SouFunIMChatListModel *_chatListModel;
    UITableView *_mainTableView;
    UIButton *_selectButton;
    UIView *_noDataView;
    UIButton *_Morebutton;
    UIView *_CoverView;
    UIView *_DropDownView;
    UIButton *_addBtn;
    NSMutableArray *_dataArray;
    SouFunIMPlayVoiceAnimationView *_AnimationView;
    FPPopoverController *_rightPopoverController;
    UIView *_showMenueView;
    UILabel *_replyDownLabel;
    UIButton *_showMenueBtn;
    NSString *_playId;
    long long _offset;
    long long _selceTedNum;
    SouFunIMNotificationListModel *_listModel;
    UIButton *_changeButton;
    UIView *_changeBarTool;
    UIView *_redView;
    UIButton *_allBtn;
    UIButton *_receiveBtn;
    UIButton *_sendBtn;
    MBProgressHUD *_waitHudView;
    SouFunIMNotificationListModel *_notiRuleTransferModel;
}

@property(retain, nonatomic) SouFunIMNotificationListModel *notiRuleTransferModel; // @synthesize notiRuleTransferModel=_notiRuleTransferModel;
@property(retain, nonatomic) MBProgressHUD *waitHudView; // @synthesize waitHudView=_waitHudView;
@property(retain, nonatomic) UIButton *sendBtn; // @synthesize sendBtn=_sendBtn;
@property(retain, nonatomic) UIButton *receiveBtn; // @synthesize receiveBtn=_receiveBtn;
@property(retain, nonatomic) UIButton *allBtn; // @synthesize allBtn=_allBtn;
@property(retain, nonatomic) UIView *redView; // @synthesize redView=_redView;
@property(retain, nonatomic) UIView *changeBarTool; // @synthesize changeBarTool=_changeBarTool;
@property(retain, nonatomic) UIButton *changeButton; // @synthesize changeButton=_changeButton;
@property(retain, nonatomic) SouFunIMNotificationListModel *listModel; // @synthesize listModel=_listModel;
@property(nonatomic) int tittleType; // @synthesize tittleType=_tittleType;
@property(nonatomic) long long selceTedNum; // @synthesize selceTedNum=_selceTedNum;
@property(nonatomic) long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *playId; // @synthesize playId=_playId;
@property(retain, nonatomic) UIButton *showMenueBtn; // @synthesize showMenueBtn=_showMenueBtn;
@property(retain, nonatomic) UILabel *replyDownLabel; // @synthesize replyDownLabel=_replyDownLabel;
@property(retain, nonatomic) UIView *showMenueView; // @synthesize showMenueView=_showMenueView;
@property(retain, nonatomic) FPPopoverController *rightPopoverController; // @synthesize rightPopoverController=_rightPopoverController;
@property(retain, nonatomic) SouFunIMPlayVoiceAnimationView *AnimationView; // @synthesize AnimationView=_AnimationView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UIButton *addBtn; // @synthesize addBtn=_addBtn;
@property(retain, nonatomic) UIView *DropDownView; // @synthesize DropDownView=_DropDownView;
@property(retain, nonatomic) UIView *CoverView; // @synthesize CoverView=_CoverView;
@property(retain, nonatomic) UIButton *Morebutton; // @synthesize Morebutton=_Morebutton;
@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain, nonatomic) SouFunIMChatListModel *chatListModel; // @synthesize chatListModel=_chatListModel;
- (void).cxx_destruct;
- (void)reloadHaveReadCount:(id)arg1;
- (void)selectTongZhiModel:(id)arg1 andOffset:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)getRulesNotifcationStateFail:(id)arg1;
- (void)getRulesNotifcationStateSuccess:(id)arg1;
- (void)jumpToNotifcationDetailViewControllerWithModel:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (struct CGSize)getMessageSize:(id)arg1;
- (struct CGSize)getTitleSize:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)checkData;
- (void)refreshNotiList:(id)arg1;
- (void)playVoice:(id)arg1 LocalUrl:(id)arg2 PlayId:(id)arg3 andVoiceAnimationView:(id)arg4 projinfo:(id)arg5;
- (void)requestVoiceDatanetUrl:(id)arg1 localUrl:(id)arg2 AnimationView:(id)arg3 andPlayId:(id)arg4 projinfo:(id)arg5;
- (void)getVoiceData:(id)arg1 andResponse:(id)arg2 andError:(id)arg3 NetUrl:(id)arg4 AnimationView:(id)arg5 andPlayId:(id)arg6 projinfo:(id)arg7;
- (void)playVioce:(id)arg1 event:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)delete:(id)arg1 event:(id)arg2;
- (void)deleteRow:(id)arg1;
- (void)dropDown;
- (void)selectMore:(id)arg1;
- (void)coverTap:(id)arg1;
- (void)backForword;
- (void)select:(id)arg1;
- (void)showNODataHud;
- (void)footDropUp;
- (void)showMenueSelected:(id)arg1;
- (void)showNotificationCount;
- (void)showNewStatusCount:(int)arg1 replyType:(int)arg2;
- (void)gotoSearchVC:(id)arg1;
- (void)addBackGroundCoverView;
- (void)creatrightButtons;
- (void)creatChangestyleBar:(long long)arg1;
- (void)longPressToDo:(id)arg1;
- (void)createTableView:(_Bool)arg1;
- (void)createNoDataView;
- (void)creatBackButton;
- (void)addNoti;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)getDataFromCoreData;
- (void)getHaveReadPeopleFaile:(id)arg1;
- (void)getHaveReadPeopleCount;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

