//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SouFunIMAllMemberTopViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MBProgressHUD, NSMutableArray, NSString, UILabel, UISearchBar, UISearchDisplayController, UITableView, UITextField, UIView;

@interface SouFunIMSelectAtGroupMemberViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, SouFunIMAllMemberTopViewDelegate>
{
    _Bool _isGroupManager;
    _Bool _deleteBtnPressed;
    _Bool _isRefresh;
    _Bool _isGroupAdministrator;
    id <SelectAtGroupMemberDelegate> _delegate;
    UITableView *_mainTableView;
    NSMutableArray *_personCountArray;
    NSString *_groupName;
    NSString *_groupID;
    NSString *_messageId;
    NSString *_groupManager;
    NSMutableArray *_groupMemberArr;
    MBProgressHUD *_hud;
    NSString *_notifyState;
    UISearchBar *_searchBar;
    UIView *_searchBackView;
    UISearchDisplayController *_searchController;
    UITableView *_searchTableView;
    NSMutableArray *_searchResultArray;
    unsigned long long _page;
    unsigned long long _searchPage;
    NSString *_groupCount;
    NSString *_searchText;
    unsigned long long _searchTotal;
    long long _totalCount;
    UIView *_heightView;
    UILabel *_totalCountLabel;
    UITextField *_searchField;
    NSString *_groupType;
    NSMutableArray *_groupAdministrators;
    NSMutableArray *_indexResult;
    NSMutableArray *_sortedArray;
    NSMutableArray *_resultArray;
    NSMutableArray *_sectionArr;
    NSMutableArray *_LetterResultArr;
}

@property(retain, nonatomic) NSMutableArray *LetterResultArr; // @synthesize LetterResultArr=_LetterResultArr;
@property(retain, nonatomic) NSMutableArray *sectionArr; // @synthesize sectionArr=_sectionArr;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) NSMutableArray *sortedArray; // @synthesize sortedArray=_sortedArray;
@property(retain, nonatomic) NSMutableArray *indexResult; // @synthesize indexResult=_indexResult;
@property(nonatomic) _Bool isGroupAdministrator; // @synthesize isGroupAdministrator=_isGroupAdministrator;
@property(retain, nonatomic) NSMutableArray *groupAdministrators; // @synthesize groupAdministrators=_groupAdministrators;
@property(copy, nonatomic) NSString *groupType; // @synthesize groupType=_groupType;
@property(retain, nonatomic) UITextField *searchField; // @synthesize searchField=_searchField;
@property(retain, nonatomic) UILabel *totalCountLabel; // @synthesize totalCountLabel=_totalCountLabel;
@property(retain, nonatomic) UIView *heightView; // @synthesize heightView=_heightView;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) unsigned long long searchTotal; // @synthesize searchTotal=_searchTotal;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(copy, nonatomic) NSString *groupCount; // @synthesize groupCount=_groupCount;
@property(nonatomic) unsigned long long searchPage; // @synthesize searchPage=_searchPage;
@property(nonatomic) unsigned long long page; // @synthesize page=_page;
@property(retain, nonatomic) NSMutableArray *searchResultArray; // @synthesize searchResultArray=_searchResultArray;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) UISearchDisplayController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UIView *searchBackView; // @synthesize searchBackView=_searchBackView;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) NSString *notifyState; // @synthesize notifyState=_notifyState;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
@property(retain, nonatomic) NSMutableArray *groupMemberArr; // @synthesize groupMemberArr=_groupMemberArr;
@property(retain, nonatomic) NSString *groupManager; // @synthesize groupManager=_groupManager;
@property(nonatomic) __weak NSString *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(nonatomic) _Bool deleteBtnPressed; // @synthesize deleteBtnPressed=_deleteBtnPressed;
@property(nonatomic) _Bool isGroupManager; // @synthesize isGroupManager=_isGroupManager;
@property(retain, nonatomic) NSMutableArray *personCountArray; // @synthesize personCountArray=_personCountArray;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(nonatomic) id <SelectAtGroupMemberDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getSortArray;
- (void)searchRefreshData;
- (void)searchPagingGetGroupUserListUnsuccessfully:(id)arg1;
- (void)searchPagingGetGroupUserListSuccessfully:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarResignAndChangeUI;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)topViewAtMemberAtIndexPath:(id)arg1;
- (void)topViewAtAllMembers;
- (id)topView;
- (id)LetterResultArrWithArray:(id)arg1;
- (id)indexResultWithArray:(id)arg1;
- (id)sortedArrayWithArray:(id)arg1;
- (void)getGroupInfoUnSuccessfully:(id)arg1;
- (void)getGroupInfoFromCoreData;
- (void)getGroupInfoSuccessfully:(id)arg1;
- (void)refreshData;
- (void)pagingGetGroupUserListUnsuccessfully:(id)arg1;
- (void)pagingGetGroupUserListSuccessfully:(id)arg1;
- (void)loadGroupMembersData;
- (void)ItemBtnPress:(id)arg1;
- (void)createNavItemBtn;
- (void)createSearchBar;
- (void)atAllPeople;
- (id)createHeadrviewOnlyWithCount;
- (id)createHeadrview;
- (void)creatUI;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

