//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AsyncImageView, UIButton, UILabel;

@interface SouFunIMGroupAllMembersViewCell : UITableViewCell
{
    AsyncImageView *_portrait;
    UILabel *_nameLabel;
    UIButton *_selectedButton;
    UILabel *_identityLabel;
}

@property(retain, nonatomic) UILabel *identityLabel; // @synthesize identityLabel=_identityLabel;
@property(retain, nonatomic) UIButton *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) AsyncImageView *portrait; // @synthesize portrait=_portrait;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

