//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SouFunIMTongZhiAgentModel : NSObject
{
    NSString *checked;
    NSString *type;
    long long _agentType;
    NSString *_agentName;
}

@property(copy, nonatomic) NSString *agentName; // @synthesize agentName=_agentName;
@property(nonatomic) long long agentType; // @synthesize agentType=_agentType;
- (void).cxx_destruct;
- (id)initWithDic:(id)arg1;

@end

