//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, NSString;

@interface SouFun_ChatRecord : NSManagedObject
{
}

+ (void)deleteAllTheDataBaseInManagedObjectContext:(id)arg1;
+ (id)getChatPicture:(id)arg1 withMessageID:(id)arg2 inManagedObjectContext:(id)arg3;
+ (void)updateChatImageInfo:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)updateChatTimeAndStateByKey:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)updateChatTimeAndState:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)updateChatMessageForError:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)updateChatMessageVoiceHaveReadStatusWithMessageKey:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)updateChatMessageHaveReadStatusWithMessageID:(id)arg1 withStartMessageKey:(id)arg2 withEndMessageKey:(id)arg3 inManagedObjectContext:(id)arg4;
+ (void)deleteChatMessageFromMessageBox:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)deleteChatMessage:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)selectChatWithResultArray:(id)arg1 WithMessageId:(id)arg2 WithMessageType:(id)arg3 inManagedObjectContext:(id)arg4;
+ (long long)selectChatRecordCountBetweenTwoMessageKeyWithMessageId:(id)arg1 withStartMessageKey:(id)arg2 withEndMessageKey:(id)arg3 inManagedObjectContext:(id)arg4;
+ (id)selectFirstNoReadChatMessageKeyWithMessageId:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)selectChatMessageList:(id)arg1 contenttype:(id)arg2 withOffset:(long long)arg3 withFetchLimit:(long long)arg4 inManagedObjectContext:(id)arg5;
+ (long long)selectMessageCount:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)selectChatFileMessageList:(id)arg1 withOffset:(long long)arg2 withFetchLimit:(long long)arg3 inManagedObjectContext:(id)arg4;
+ (void)selectChatMessageList:(id)arg1 withMessageId:(id)arg2 withSearchStr:(id)arg3 inManagedObjectContext:(id)arg4;
+ (void)selectChatMessageList:(id)arg1 withMessageId:(id)arg2 withOffset:(long long)arg3 withFetchLimit:(long long)arg4 inManagedObjectContext:(id)arg5;
+ (void)selectChatMessageList:(id)arg1 WithMessageId:(id)arg2 WithMessageType:(id)arg3 withFlag:(_Bool)arg4 inManagedObjectContext:(id)arg5;
+ (id)selectWithMessageKey:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)insertChatMessage:(id)arg1 inManagedObjectContext:(id)arg2;

// Remaining properties
@property(retain, nonatomic) NSString *contenttype; // @dynamic contenttype;
@property(retain, nonatomic) NSString *haveRead; // @dynamic haveRead;
@property(retain, nonatomic) NSString *height; // @dynamic height;
@property(retain, nonatomic) NSString *housetype; // @dynamic housetype;
@property(retain, nonatomic) NSString *message; // @dynamic message;
@property(retain, nonatomic) NSString *messageid; // @dynamic messageid;
@property(retain, nonatomic) NSString *messagekey; // @dynamic messagekey;
@property(retain, nonatomic) NSString *messagetitle; // @dynamic messagetitle;
@property(retain, nonatomic) NSString *myID; // @dynamic myID;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSString *otheruser; // @dynamic otheruser;
@property(retain, nonatomic) NSString *purpose; // @dynamic purpose;
@property(retain, nonatomic) NSString *receivetime; // @dynamic receivetime;
@property(retain, nonatomic) NSString *selfuser; // @dynamic selfuser;
@property(retain, nonatomic) NSString *sendtime; // @dynamic sendtime;
@property(retain, nonatomic) NSString *senduser; // @dynamic senduser;
@property(retain, nonatomic) NSString *status; // @dynamic status;
@property(retain, nonatomic) NSNumber *timeAndState; // @dynamic timeAndState;
@property(retain, nonatomic) NSString *voiceread; // @dynamic voiceread;
@property(retain, nonatomic) NSString *width; // @dynamic width;

@end

