//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ChatVoiceRecorderVC, NSString, SouFunIMPlayVoiceAnimationView, UIImageView, UIViewController;

@interface SouFunIMChatVoiceView : UIView
{
    NSString *_voiceTime;
    NSString *_fileSize;
    NSString *_saveType;
    NSString *_localURL;
    NSString *_netURL;
    UIView *_personView;
    UIViewController *_parChatViewController;
    ChatVoiceRecorderVC *_recorderVC;
    SouFunIMPlayVoiceAnimationView *_voiceAnimationView;
    NSString *_coordX;
    NSString *_coordY;
    NSString *_locationAdress;
    NSString *chatMessageInfo;
    NSString *localMessageKey;
    NSString *status;
    NSString *_businessID;
    NSString *_playID;
    NSString *_voiceHaveRead;
    NSString *_messageKey;
    UIImageView *_changeReadView;
}

@property(retain, nonatomic) UIImageView *changeReadView; // @synthesize changeReadView=_changeReadView;
@property(retain, nonatomic) NSString *messageKey; // @synthesize messageKey=_messageKey;
@property(retain, nonatomic) NSString *voiceHaveRead; // @synthesize voiceHaveRead=_voiceHaveRead;
@property(retain, nonatomic) NSString *playID; // @synthesize playID=_playID;
@property(retain, nonatomic) NSString *businessID; // @synthesize businessID=_businessID;
@property(retain, nonatomic) NSString *status; // @synthesize status;
@property(retain, nonatomic) NSString *localMessageKey; // @synthesize localMessageKey;
@property(retain, nonatomic) NSString *chatMessageInfo; // @synthesize chatMessageInfo;
@property(retain, nonatomic) NSString *locationAdress; // @synthesize locationAdress=_locationAdress;
@property(retain, nonatomic) NSString *coordY; // @synthesize coordY=_coordY;
@property(retain, nonatomic) NSString *coordX; // @synthesize coordX=_coordX;
@property(nonatomic) __weak UIViewController *parChatViewController; // @synthesize parChatViewController=_parChatViewController;
@property(retain, nonatomic) SouFunIMPlayVoiceAnimationView *voiceAnimationView; // @synthesize voiceAnimationView=_voiceAnimationView;
@property(retain, nonatomic) ChatVoiceRecorderVC *recorderVC; // @synthesize recorderVC=_recorderVC;
@property(nonatomic) __weak UIView *personView; // @synthesize personView=_personView;
@property(retain, nonatomic) NSString *netURL; // @synthesize netURL=_netURL;
@property(retain, nonatomic) NSString *localURL; // @synthesize localURL=_localURL;
@property(retain, nonatomic) NSString *saveType; // @synthesize saveType=_saveType;
@property(retain, nonatomic) NSString *filesize; // @synthesize filesize=_fileSize;
@property(retain, nonatomic) NSString *voiceTime; // @synthesize voiceTime=_voiceTime;
- (void).cxx_destruct;
- (void)cheackReceiveVoiceIsExitInCaches;
- (void)getVoiceData:(id)arg1 andResponse:(id)arg2 andError:(id)arg3;
- (void)requestVoiceData;
- (void)playVoice:(id)arg1;
- (void)playTheVoiceMessage:(id)arg1;
- (void)funUploadNotifictionwithUrlString:(id)arg1 response:(id)arg2 Error:(id)arg3;
- (void)deleteLastMessageInApplog:(id)arg1;
- (void)setInsertDatabase:(id)arg1 messageKey:(id)arg2;
- (void)setUploadFileRequest;
- (void)chongFa:(id)arg1;
- (void)longPressVoiceView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withText:(id)arg2 fromSelf:(_Bool)arg3 saveType:(id)arg4 onpersonView:(id)arg5 andVoiceRead:(id)arg6 andMeaageKey:(id)arg7;
- (id)initWithFrame:(struct CGRect)arg1;

@end

