//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, NSTimer, UILabel, UIProgressView;

@interface SouFunIMFileQipaoView : UIView
{
    NSTimer *_timer;
    NSString *_message;
    UIView *_cardView;
    UILabel *_downloadLabel;
    UIProgressView *_progressView;
}

@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *downloadLabel; // @synthesize downloadLabel=_downloadLabel;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
- (void).cxx_destruct;
- (void)addLabel:(id *)arg1 superView:(id)arg2 frame:(struct CGRect)arg3 text:(id)arg4 font:(double)arg5 textColor:(id)arg6 tag:(long long)arg7;
- (void)refreshProgress:(id)arg1;
- (void)refreshFileSendStatus:(id)arg1;
- (void)refreshFileDownLoadStatus;
- (id)initWithFrame:(struct CGRect)arg1 withMessage:(id)arg2 from:(_Bool)arg3 fileErrorStatus:(id)arg4;

@end

