//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SouFunChatFilesCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, SouFunIMShowXiangceView, UITableView, UIView;

@interface SouFunIMChatFilesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, SouFunChatFilesCellDelegate>
{
    NSString *_videoURL;
    NSString *_filedSize;
    NSString *_videoTime;
    NSString *_coordY;
    NSString *_coordX;
    NSString *_locationAdress;
    _Bool _isModal;
    NSMutableArray *_dataArr;
    UITableView *_mainTableView;
    UIView *_nullView;
    NSMutableArray *_sectionArr;
    NSMutableDictionary *_tableViewDict;
    SouFunIMShowXiangceView *_showXiangce;
}

@property(retain, nonatomic) SouFunIMShowXiangceView *showXiangce; // @synthesize showXiangce=_showXiangce;
@property(retain, nonatomic) NSMutableDictionary *tableViewDict; // @synthesize tableViewDict=_tableViewDict;
@property(retain, nonatomic) NSMutableArray *sectionArr; // @synthesize sectionArr=_sectionArr;
@property(retain, nonatomic) UIView *nullView; // @synthesize nullView=_nullView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(nonatomic) _Bool isModal; // @synthesize isModal=_isModal;
- (void).cxx_destruct;
- (id)dealWithStringToTime:(id)arg1 isMillisecond:(_Bool)arg2;
- (id)handleTime:(id)arg1 isMillisecond:(_Bool)arg2;
- (void)handleVideoData:(id)arg1;
- (void)TapChatFilesCellDelegate:(id)arg1 isVideo:(_Bool)arg2 withView:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)loadData;
- (void)back;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

