//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SFUtilityHelper;

@interface SouFunIMDebugHandlerDelegate : NSObject
{
    SFUtilityHelper *_uploadTool;
}

+ (void)writeIMChatLog:(id)arg1 withFlagStr:(id)arg2;
+ (void)upLogZipPathWithUrlStr:(id)arg1;
+ (void)debugAlertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
+ (void)showDebugAlertInVC:(id)arg1;
+ (_Bool)isDebugCommandWithStr:(id)arg1;
@property(retain, nonatomic) SFUtilityHelper *uploadTool; // @synthesize uploadTool=_uploadTool;
- (void).cxx_destruct;

@end

