//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SouFunIMTongZhiGroupModel : NSObject
{
    NSString *checked;
    NSString *type;
    long long _ID;
    NSString *_groupName;
}

@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (id)initWithDic:(id)arg1;

@end

