//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath;

@protocol SouFunIMAllMemberTopViewDelegate <NSObject>

@optional
- (void)topViewAtMemberAtIndexPath:(NSIndexPath *)arg1;
- (void)topViewAtAllMembers;
- (void)topViewCancelManagerAtIndexPath:(NSIndexPath *)arg1;
- (void)topViewDeleteMemberAtIndexPath:(NSIndexPath *)arg1;
- (void)topViewDidSelectRowAtIndexPath:(NSIndexPath *)arg1;
@end

