//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MBProgressHUD, NSMutableArray, NSString, UIBarButtonItem, UIButton, UICollectionView, UILabel, UISearchBar, UISearchDisplayController, UITableView, UIView;

@interface SouFunIMSelectFriendsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UISearchDisplayDelegate, UISearchBarDelegate>
{
    _Bool _isCreateGroup;
    _Bool _isSelectNotContacts;
    _Bool _isColleague;
    NSString *_chatGroupName;
    NSString *_groupID;
    NSMutableArray *_hasBeenContactsArr;
    MBProgressHUD *_hud;
    NSString *_creatGroupID;
    NSString *_userNameForOne;
    NSString *_singleChatUsername;
    UITableView *_mainTableView;
    UITableView *_leaderOrColleagueTableView;
    NSMutableArray *_colleagueArr;
    NSMutableArray *_LetterResultArr;
    NSMutableArray *_resultArray;
    NSMutableArray *_sortedArray;
    NSMutableArray *_indexResult;
    NSMutableArray *_willChatArray;
    UICollectionView *_topCollectionView;
    UIButton *_rightButton;
    UISearchBar *_mySearchBar;
    UIView *_searchBackView;
    UISearchDisplayController *_mySearchDisplayController;
    UIBarButtonItem *_shareButton;
    NSMutableArray *_contactsArray;
    UITableView *_searchTableView;
    NSMutableArray *_searchColleagueArr;
    NSMutableArray *_searchAllEmployeeArr;
    NSMutableArray *_searchLeaderArr;
    NSMutableArray *_searchArr;
    NSMutableArray *_dataArr;
    NSString *_keyword;
    long long _start;
    UIView *_noDataView;
    UIView *_labelBackgroundView;
    UILabel *_noDataViewLabel;
}

@property(retain, nonatomic) UILabel *noDataViewLabel; // @synthesize noDataViewLabel=_noDataViewLabel;
@property(retain, nonatomic) UIView *labelBackgroundView; // @synthesize labelBackgroundView=_labelBackgroundView;
@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(nonatomic) long long start; // @synthesize start=_start;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) NSMutableArray *searchArr; // @synthesize searchArr=_searchArr;
@property(retain, nonatomic) NSMutableArray *searchLeaderArr; // @synthesize searchLeaderArr=_searchLeaderArr;
@property(retain, nonatomic) NSMutableArray *searchAllEmployeeArr; // @synthesize searchAllEmployeeArr=_searchAllEmployeeArr;
@property(retain, nonatomic) NSMutableArray *searchColleagueArr; // @synthesize searchColleagueArr=_searchColleagueArr;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) NSMutableArray *contactsArray; // @synthesize contactsArray=_contactsArray;
@property(retain, nonatomic) UIBarButtonItem *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UISearchDisplayController *mySearchDisplayController; // @synthesize mySearchDisplayController=_mySearchDisplayController;
@property(retain, nonatomic) UIView *searchBackView; // @synthesize searchBackView=_searchBackView;
@property(retain, nonatomic) UISearchBar *mySearchBar; // @synthesize mySearchBar=_mySearchBar;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UICollectionView *topCollectionView; // @synthesize topCollectionView=_topCollectionView;
@property(retain, nonatomic) NSMutableArray *willChatArray; // @synthesize willChatArray=_willChatArray;
@property(retain, nonatomic) NSMutableArray *indexResult; // @synthesize indexResult=_indexResult;
@property(retain, nonatomic) NSMutableArray *sortedArray; // @synthesize sortedArray=_sortedArray;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) NSMutableArray *LetterResultArr; // @synthesize LetterResultArr=_LetterResultArr;
@property(nonatomic) _Bool isColleague; // @synthesize isColleague=_isColleague;
@property(nonatomic) _Bool isSelectNotContacts; // @synthesize isSelectNotContacts=_isSelectNotContacts;
@property(retain, nonatomic) NSMutableArray *colleagueArr; // @synthesize colleagueArr=_colleagueArr;
@property(retain, nonatomic) UITableView *leaderOrColleagueTableView; // @synthesize leaderOrColleagueTableView=_leaderOrColleagueTableView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(copy, nonatomic) NSString *singleChatUsername; // @synthesize singleChatUsername=_singleChatUsername;
@property(retain, nonatomic) NSString *userNameForOne; // @synthesize userNameForOne=_userNameForOne;
@property(retain, nonatomic) NSString *creatGroupID; // @synthesize creatGroupID=_creatGroupID;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
@property(retain, nonatomic) NSMutableArray *hasBeenContactsArr; // @synthesize hasBeenContactsArr=_hasBeenContactsArr;
@property(nonatomic) _Bool isCreateGroup; // @synthesize isCreateGroup=_isCreateGroup;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(copy, nonatomic) NSString *chatGroupName; // @synthesize chatGroupName=_chatGroupName;
- (void).cxx_destruct;
- (void)loadLeaderData;
- (void)loadColleagueData;
- (void)loadData:(_Bool)arg1;
- (void)selectColleagueListACT:(id)arg1;
- (void)selectLeaderListACT:(id)arg1;
- (void)tap:(id)arg1;
- (id)topView;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)topCollectionViewReloadData;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)judgeState:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)selectFriendsTableViewCell:(id)arg1 withModel:(id)arg2 withIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)refreshPage;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (id)searchModelInArray:(id)arg1 andText:(id)arg2;
- (void)searchBarResignAndChangeUI;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)handleWillChatArray;
- (void)checkButtonTapped:(id)arg1 event:(id)arg2;
- (void)enterChatViewController;
- (id)getMessageNameWithGroupID:(id)arg1;
- (id)getChatKeyWith:(id)arg1 withHouseId:(id)arg2;
- (void)inviteContacts:(id)arg1;
- (void)backToTop;
- (id)getGroupNameWith:(id)arg1;
- (void)chatAction:(id)arg1;
- (void)popToLastPage;
- (void)backBarButtonItem;
- (void)searchFriend:(id)arg1;
- (void)createRightButtonItems;
- (void)createSearchTableview;
- (void)createSearchBar;
- (void)createNoDataView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

