//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIColor, UIScrollView;

@interface SouFunIMSelectFileMenu : UIView
{
    _Bool _flagAtTop;
    NSMutableArray *_items;
    unsigned long long _numberOfItems;
    UIScrollView *_scrollView;
    id <IMMenuDelegate> _delegate;
    UIView *_flagView;
    UIColor *_flagViewColor;
    double _flagViewHeight;
}

@property(nonatomic) _Bool flagAtTop; // @synthesize flagAtTop=_flagAtTop;
@property(nonatomic) double flagViewHeight; // @synthesize flagViewHeight=_flagViewHeight;
@property(retain, nonatomic) UIColor *flagViewColor; // @synthesize flagViewColor=_flagViewColor;
@property(retain, nonatomic) UIView *flagView; // @synthesize flagView=_flagView;
@property(nonatomic) id <IMMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) unsigned long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)clickItem:(id)arg1;
- (void)layoutSubviews;
- (void)selectedItemAtIndex:(long long)arg1;
- (void)addMenuItem:(id)arg1;
- (void)createFlagView;
- (void)createScrollView;
- (void)setUp;
- (id)initWithFrame:(struct CGRect)arg1 withItems:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

