//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SouFun_NoticeReply_Model : NSObject
{
    NSString *_messagekey;
    NSString *_myID;
    NSString *_form;
    NSString *_nickname;
    NSString *_messagetime;
    NSString *_sendto;
    NSString *_from;
    NSString *_projname;
    NSString *_agentname;
    NSString *_projinfo;
    NSString *_message;
    NSString *_customerId;
    NSString *_messageid;
    NSString *_sendtime;
}

@property(retain, nonatomic) NSString *sendtime; // @synthesize sendtime=_sendtime;
@property(retain, nonatomic) NSString *messageid; // @synthesize messageid=_messageid;
@property(retain, nonatomic) NSString *customerId; // @synthesize customerId=_customerId;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *projinfo; // @synthesize projinfo=_projinfo;
@property(retain, nonatomic) NSString *agentname; // @synthesize agentname=_agentname;
@property(retain, nonatomic) NSString *projname; // @synthesize projname=_projname;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *sendto; // @synthesize sendto=_sendto;
@property(retain, nonatomic) NSString *messagetime; // @synthesize messagetime=_messagetime;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *form; // @synthesize form=_form;
@property(retain, nonatomic) NSString *myID; // @synthesize myID=_myID;
@property(retain, nonatomic) NSString *messagekey; // @synthesize messagekey=_messagekey;
- (void).cxx_destruct;
- (id)initWithModel:(id)arg1;

@end

