//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSString;

@interface SouFun_NoticeReply : NSManagedObject
{
}

+ (void)selectNoticeReplyList:(id)arg1 withNoticeID:(id)arg2 withOffset:(long long)arg3 withFetchLimit:(long long)arg4 inManagedObjectContext:(id)arg5;
+ (void)insertNewNoticeReply:(id)arg1 inManagedObjectContext:(id)arg2;

// Remaining properties
@property(retain, nonatomic) NSString *agentname; // @dynamic agentname;
@property(retain, nonatomic) NSString *customerId; // @dynamic customerId;
@property(retain, nonatomic) NSString *form; // @dynamic form;
@property(retain, nonatomic) NSString *from; // @dynamic from;
@property(retain, nonatomic) NSString *message; // @dynamic message;
@property(retain, nonatomic) NSString *messageid; // @dynamic messageid;
@property(retain, nonatomic) NSString *messagekey; // @dynamic messagekey;
@property(retain, nonatomic) NSString *messagetime; // @dynamic messagetime;
@property(retain, nonatomic) NSString *myID; // @dynamic myID;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSString *projinfo; // @dynamic projinfo;
@property(retain, nonatomic) NSString *projname; // @dynamic projname;
@property(retain, nonatomic) NSString *sendtime; // @dynamic sendtime;
@property(retain, nonatomic) NSString *sendto; // @dynamic sendto;

@end

