//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKLocationServiceDelegate.h"
#import "BMKMapViewDelegate.h"
#import "BMKRouteSearchDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"

@class BMKLocationService, BMKMapView, BMKRouteSearch, MBProgressHUD, NSString, UIAlertView;

@interface SouFunIMMapPositionDetailViewController : UIViewController <UIActionSheetDelegate, UIAlertViewDelegate, BMKMapViewDelegate, BMKLocationServiceDelegate, BMKRouteSearchDelegate, BMKGeoCodeSearchDelegate>
{
    BMKMapView *_mapView;
    BMKLocationService *_locService;
    BMKRouteSearch *_routesearch;
    struct CLLocationCoordinate2D _currentPosition;
    _Bool _routeIsShowFlag;
    MBProgressHUD *_hud;
    UIAlertView *_alertView;
    NSString *_positionName;
    NSString *_positionAddress;
    NSString *_messageID;
    NSString *_messageKey;
    NSString *_message;
    struct CLLocationCoordinate2D _coordinate;
}

@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *messageKey; // @synthesize messageKey=_messageKey;
@property(retain, nonatomic) NSString *messageID; // @synthesize messageID=_messageID;
@property(retain, nonatomic) NSString *positionAddress; // @synthesize positionAddress=_positionAddress;
@property(retain, nonatomic) NSString *positionName; // @synthesize positionName=_positionName;
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)authorizationStatus;
- (void)resendPosition;
- (void)backForward;
- (void)createNav;
- (void)createUI;
- (void)gotoPositionWithCoordinate2D:(struct CLLocationCoordinate2D)arg1;
- (void)gotoCurrentPosition;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheet:(id)arg1;
- (void)didFailToLocateUserWithError:(id)arg1;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)didUpdateUserHeading:(id)arg1;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (void)onGetDrivingRouteResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)routeSearch;
- (void)initMap;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)enterBackground;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

