//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILongPressGestureRecognizer.h"

@class NSString;

@interface SouFunIMLongPressGestureRecognizer : UILongPressGestureRecognizer
{
    NSString *_message;
}

@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;

@end

