//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SouFunIMUploadImageHandle : NSObject
{
}

+ (void)funUploadNotifictionWithURLString:(id)arg1 response:(id)arg2 andWidth:(id)arg3 andHeight:(id)arg4 withUUID:(id)arg5 error:(id)arg6;
+ (void)uploadImage:(id)arg1;

@end

