//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString;

@interface SouFunIMContactsListTableView : UITableView <UITableViewDelegate, UITableViewDataSource>
{
    NSMutableArray *myFriends;
    NSMutableArray *itemsOnBottomScrollArray;
    _Bool _rowSelected;
    NSMutableArray *titleArr;
    long long _section;
}

@property(nonatomic) _Bool rowSelected; // @synthesize rowSelected=_rowSelected;
@property(nonatomic) long long section; // @synthesize section=_section;
@property(retain, nonatomic) NSMutableArray *itemsOnBottomScrollArray; // @synthesize itemsOnBottomScrollArray;
@property(retain, nonatomic) NSMutableArray *titleArr; // @synthesize titleArr;
@property(retain, nonatomic) NSMutableArray *myFriends; // @synthesize myFriends;
- (void).cxx_destruct;
- (void)changeSelectedStatus:(id)arg1 event:(id)arg2;
- (void)doTap:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)informationOnCell:(id)arg1 array:(id)arg2 indexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)createGroup;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

