//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SouFunShareMediaModel.h"

@class NSString;

@interface SouFunShareVideoModel : SouFunShareMediaModel
{
    NSString *_videoUrl;
    NSString *_videoLowBandUrl;
}

@property(retain, nonatomic) NSString *videoLowBandUrl; // @synthesize videoLowBandUrl=_videoLowBandUrl;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
- (void).cxx_destruct;

@end

