//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MBProgressHUD, NSMutableArray, NSString, UIButton, UICollectionView, UISearchBar, UISearchDisplayController, UITableView;

@interface SouFunIMSelectTongZhiGroupViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UISearchBarDelegate>
{
    MBProgressHUD *_hud;
    id <backHeadWithArray> _delegate;
    UISearchDisplayController *_mySearchDisplayController;
    UITableView *_mainTableView;
    UITableView *_searchTableView;
    NSMutableArray *_resultArray;
    NSMutableArray *_willChatArray;
    UICollectionView *_topCollectionView;
    UIButton *_rightButton;
    UISearchBar *_mainSearchBar;
    NSMutableArray *_searchArray;
    NSMutableArray *_dataArray;
    long long _page;
    long long _searchPage;
}

@property(nonatomic) long long searchPage; // @synthesize searchPage=_searchPage;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSMutableArray *searchArray; // @synthesize searchArray=_searchArray;
@property(retain, nonatomic) UISearchBar *mainSearchBar; // @synthesize mainSearchBar=_mainSearchBar;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UICollectionView *topCollectionView; // @synthesize topCollectionView=_topCollectionView;
@property(retain, nonatomic) NSMutableArray *willChatArray; // @synthesize willChatArray=_willChatArray;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain, nonatomic) UISearchDisplayController *mySearchDisplayController; // @synthesize mySearchDisplayController=_mySearchDisplayController;
@property(nonatomic) __weak id <backHeadWithArray> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
- (void).cxx_destruct;
- (struct CGSize)calculateHeightAndWidth:(id)arg1 fontNumber:(float)arg2 maxHeight:(float)arg3 maxWidth:(float)arg4;
- (void)addKickState:(long long)arg1;
- (void)addKickSearchState:(long long)arg1;
- (void)enterHeadArray:(id)arg1;
- (void)cleanKickState:(long long)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchTableViewRefreshing;
- (void)mainTableViewRefreshing;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)checkButtonTapped:(id)arg1 event:(id)arg2;
- (void)chatAction:(id)arg1;
- (void)backForward;
- (void)creatBackButton;
- (void)didReceiveMemoryWarning;
- (void)createMainTableView;
- (void)createBottomView;
- (void)createSearchBar;
- (void)requestData:(id)arg1 withState:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

