//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AsyncImageView, NSMutableArray;

@protocol SouFunIMNoticeDetailPhotosViewDelegate <NSObject>
- (void)noticeDetailPhotosViewDidSelectAtIndex:(long long)arg1 asyImageView:(AsyncImageView *)arg2 pohtoUrls:(NSMutableArray *)arg3;
@end

