//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SouFunIMShowXiangceView : UIView
{
    long long _startIndex;
    NSString *_notificationName;
    struct CGRect _startRect;
}

+ (id)addImgViewWithRect:(struct CGRect)arg1 andImgURLString:(id)arg2 andTag:(long long)arg3 SuperView:(id)arg4 DefaultImage:(id)arg5 FailLoadImage:(id)arg6;
+ (id)addImgViewWithRect:(struct CGRect)arg1 andImgURLString:(id)arg2 andTag:(long long)arg3 SuperView:(id)arg4 DefaultImageName:(id)arg5 FailLoadImageName:(id)arg6;
+ (id)addImgViewWithRect:(struct CGRect)arg1 andImgURLString:(id)arg2 andTag:(long long)arg3 SuperView:(id)arg4;
@property(retain, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(nonatomic) struct CGRect startRect; // @synthesize startRect=_startRect;
@property(nonatomic) long long startIndex; // @synthesize startIndex=_startIndex;
- (void).cxx_destruct;
- (void)quitXiangce:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 currentImage:(id)arg2 currentImageUrl:(id)arg3 currentImageViewRect:(struct CGRect)arg4 controller:(id)arg5 imageUrlArr:(id)arg6 index:(long long)arg7 messageKeyArr:(id)arg8 imageSendStatusArr:(id)arg9 notificationName:(id)arg10 isHiddenXiangceFilesBtn:(_Bool)arg11;
- (void)dealloc;
- (id)init;

@end

