//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "SouFunIMContactsTopViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UILabel;

@interface SouFunIMContactsTableView : UITableView <SouFunIMContactsTopViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSMutableArray *myFriends;
    NSMutableArray *tempGuests;
    NSMutableArray *onlineContactArr;
    NSMutableArray *blacklists;
    _Bool _rowSelected;
    NSMutableArray *titleArr;
    long long _section;
    NSMutableArray *_LetterResultArr;
    NSMutableArray *_resultArray;
    NSMutableArray *_sortedArray;
    NSMutableArray *_indexResult;
    UILabel *_countLabel;
}

@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) NSMutableArray *indexResult; // @synthesize indexResult=_indexResult;
@property(retain, nonatomic) NSMutableArray *sortedArray; // @synthesize sortedArray=_sortedArray;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) NSMutableArray *LetterResultArr; // @synthesize LetterResultArr=_LetterResultArr;
@property(nonatomic) _Bool rowSelected; // @synthesize rowSelected=_rowSelected;
@property(nonatomic) long long section; // @synthesize section=_section;
@property(retain, nonatomic) NSMutableArray *blacklists; // @synthesize blacklists;
@property(retain, nonatomic) NSMutableArray *onlineContactArr; // @synthesize onlineContactArr;
@property(retain, nonatomic) NSMutableArray *tempGuests; // @synthesize tempGuests;
@property(retain, nonatomic) NSMutableArray *titleArr; // @synthesize titleArr;
@property(retain, nonatomic) NSMutableArray *myFriends; // @synthesize myFriends;
- (void).cxx_destruct;
- (void)enterSpecialAttention:(id)arg1;
- (void)managers:(id)arg1;
- (void)colleague:(id)arg1;
- (void)enterGroupListVC:(id)arg1;
- (void)doTap:(id)arg1;
- (void)informationOnCell:(id)arg1 array:(id)arg2 indexPath:(id)arg3;
- (void)createGroupsList;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (id)getLetterResultArray;
- (id)getIndexResultArray;
- (id)getSortArray;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)getGroupCount;
- (void)topViewDidSelectRowAtIndexPath:(id)arg1;
- (id)topView;
- (void)reloadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

