//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AsyncImageView, SouFunIMGroupChatDetailInfoViewController, UILabel, UISwitch;

@interface SouFunIMGroupDetailInfoCell : UITableViewCell
{
    UILabel *_groupNameLabel;
    AsyncImageView *_groupImage;
    UILabel *_groupAnnouncemenLabel;
    SouFunIMGroupChatDetailInfoViewController *_myCtr;
    UISwitch *_pushSwitch;
}

+ (struct CGSize)fitSizeWithText:(id)arg1;
@property(retain, nonatomic) UISwitch *pushSwitch; // @synthesize pushSwitch=_pushSwitch;
@property(nonatomic) __weak SouFunIMGroupChatDetailInfoViewController *myCtr; // @synthesize myCtr=_myCtr;
@property(retain, nonatomic) UILabel *groupAnnouncemenLabel; // @synthesize groupAnnouncemenLabel=_groupAnnouncemenLabel;
@property(retain, nonatomic) AsyncImageView *groupImage; // @synthesize groupImage=_groupImage;
@property(retain, nonatomic) UILabel *groupNameLabel; // @synthesize groupNameLabel=_groupNameLabel;
- (void).cxx_destruct;
- (void)publicGroupAction:(id)arg1;
- (void)switchChange:(id)arg1;
- (void)topMessageAction:(id)arg1;
- (void)addCellLineWithFrame:(struct CGRect)arg1;
- (void)addLabelWithTitle:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)drawCustomCellWithGroupCtr:(id)arg1 andIndexPath:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

