//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SouFunIMChatServiceDelegate : NSObject
{
}

+ (void)saveTongzhiAndOtherActWithMessage:(id)arg1;
+ (void)refreshMessageBox:(id)arg1;
+ (void)saveTongzhiReceiverInfoWithMessage:(id)arg1;
+ (void)didReceiveCustomMessage:(id)arg1;

@end

