//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AsyncImageView, NSString, UIImageView, UILabel;

@interface SouFunIMGroupsListCell : UITableViewCell
{
    AsyncImageView *headImg;
    UILabel *groupNameLabel;
    NSString *groupID;
    NSString *nickName;
    NSString *userName;
    NSString *cardMessage;
    NSString *groupName;
    UIImageView *_closeRingImg;
}

@property(retain, nonatomic) UIImageView *closeRingImg; // @synthesize closeRingImg=_closeRingImg;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName;
@property(retain, nonatomic) NSString *cardMessage; // @synthesize cardMessage;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID;
@property(retain, nonatomic) AsyncImageView *headImg; // @synthesize headImg;
@property(retain, nonatomic) UILabel *groupNameLabel; // @synthesize groupNameLabel;
- (void).cxx_destruct;
- (void)refreshDataByHasbeenCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)drawCustomCellWithGroups:(id)arg1 andIndexPath:(id)arg2;
- (void)addLabelOfGroupWithString:(id)arg1 andGrame:(struct CGRect)arg2 andColer:(id)arg3 andSize:(double)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

