//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSString;

@interface TILCallNotification : NSObject
{
    long long _notifId;
    NSString *_notifDesc;
    NSString *_sender;
    NSArray *_targets;
    NSDate *_date;
    NSString *_custom;
}

+ (id)parseCallCmd:(id)arg1;
@property(retain, nonatomic) NSString *custom; // @synthesize custom=_custom;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSArray *targets; // @synthesize targets=_targets;
@property(retain, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(retain, nonatomic) NSString *notifDesc; // @synthesize notifDesc=_notifDesc;
@property(nonatomic) long long notifId; // @synthesize notifId=_notifId;
- (void).cxx_destruct;
- (id)init;

@end

