//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TILC2CSponsorConfig : NSObject
{
    _Bool _onlineInvite;
    int _callId;
    unsigned int _waitLimit;
}

@property(nonatomic) _Bool onlineInvite; // @synthesize onlineInvite=_onlineInvite;
@property(nonatomic) unsigned int waitLimit; // @synthesize waitLimit=_waitLimit;
@property(nonatomic) int callId; // @synthesize callId=_callId;

@end

