//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TIMAVSerialization.h"

@class NSData, NSString, TIMAV_LongConnUdtDataHeadV2;

@interface TIMAV_ClientToInterfaceTestSpeedReq : NSObject <TIMAVSerialization>
{
    unsigned int _dwTestDataLen;
    TIMAV_LongConnUdtDataHeadV2 *_datahead;
    NSData *_bufferData;
}

@property(retain, nonatomic) NSData *bufferData; // @synthesize bufferData=_bufferData;
@property(nonatomic) unsigned int dwTestDataLen; // @synthesize dwTestDataLen=_dwTestDataLen;
@property(retain, nonatomic) TIMAV_LongConnUdtDataHeadV2 *datahead; // @synthesize datahead=_datahead;
- (void).cxx_destruct;
- (id)toSerializedBytes;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

