//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TIMBuglyWapper : NSObject
{
}

+ (void)setUserIdentifier:(id)arg1;
+ (void)startWithAppId:(id)arg1;
+ (void)logBugly:(long long)arg1 tag:(id)arg2 log:(id)arg3;
+ (void)setComponentIdentifier:(id)arg1 version:(id)arg2;
+ (void)setSdkConfig:(id)arg1 forKey:(id)arg2;

@end

