//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TIMFriendshipSetting : NSObject
{
    unsigned long long friendFlags;
    NSArray *friendCustom;
    NSArray *userCustom;
}

@property(retain, nonatomic) NSArray *userCustom; // @synthesize userCustom;
@property(retain, nonatomic) NSArray *friendCustom; // @synthesize friendCustom;
@property(nonatomic) unsigned long long friendFlags; // @synthesize friendFlags;
- (void).cxx_destruct;

@end

