//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TIMCodingModel.h"

@class NSArray, NSString;

@interface TIMFriendGroup : TIMCodingModel
{
    NSString *name;
    unsigned long long userCnt;
    NSArray *friends;
}

@property(retain, nonatomic) NSArray *friends; // @synthesize friends;
@property(nonatomic) unsigned long long userCnt; // @synthesize userCnt;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;

@end

