//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TIMElem.h"

@class NSString;

@interface TIMLocationElem : TIMElem
{
    NSString *desc;
    double latitude;
    double longitude;
}

@property(nonatomic) double longitude; // @synthesize longitude;
@property(nonatomic) double latitude; // @synthesize latitude;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
- (void).cxx_destruct;
- (id)description;

@end

