//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TIMConversation;

@interface TIMMessageReceipt : NSObject
{
    TIMConversation *conversation;
    long long timestamp;
}

@property(nonatomic) long long timestamp; // @synthesize timestamp;
@property(retain, nonatomic) TIMConversation *conversation; // @synthesize conversation;
- (void).cxx_destruct;

@end

