//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TIMAndroidOfflinePushConfig;

@interface TIMOfflinePushInfo : NSObject
{
    NSString *desc;
    NSString *ext;
    NSString *sound;
    long long pushFlag;
    TIMAndroidOfflinePushConfig *androidConfig;
}

@property(retain, nonatomic) TIMAndroidOfflinePushConfig *androidConfig; // @synthesize androidConfig;
@property(nonatomic) long long pushFlag; // @synthesize pushFlag;
@property(retain, nonatomic) NSString *sound; // @synthesize sound;
@property(retain, nonatomic) NSString *ext; // @synthesize ext;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
- (void).cxx_destruct;

@end

