//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TIMRelay : NSObject
{
}

+ (id)sharedInstance;
- (int)SendDataWithoutEncryption:(id)arg1 timeout:(int)arg2 succ:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;
- (int)SendDataWithoutEncryption:(id)arg1 succ:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (int)SendDataWithEncryption:(id)arg1 timeout:(int)arg2 succ:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;
- (int)SendDataWithEncryption:(id)arg1 succ:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;

@end

