//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TIMSnapshot : NSObject
{
    int size;
    int width;
    int height;
    NSString *uuid;
    NSString *type;
    NSString *selfIdentifier;
}

@property(retain, nonatomic) NSString *selfIdentifier; // @synthesize selfIdentifier;
@property(nonatomic) int height; // @synthesize height;
@property(nonatomic) int width; // @synthesize width;
@property(nonatomic) int size; // @synthesize size;
@property(retain, nonatomic) NSString *type; // @synthesize type;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
- (void).cxx_destruct;
- (void)getImage:(id)arg1 succ:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (id)description;

@end

