//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TIMElem.h"

@class NSData, NSString;

@interface TIMSoundElem : TIMElem
{
    unsigned int taskId;
    int dataSize;
    int second;
    NSString *path;
    NSData *data;
    NSString *uuid;
    NSString *selfIdentifier;
}

@property(retain, nonatomic) NSString *selfIdentifier; // @synthesize selfIdentifier;
@property(nonatomic) int second; // @synthesize second;
@property(nonatomic) int dataSize; // @synthesize dataSize;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
@property(retain, nonatomic) NSData *data; // @synthesize data;
@property(retain, nonatomic) NSString *path; // @synthesize path;
@property(nonatomic) unsigned int taskId; // @synthesize taskId;
- (void).cxx_destruct;
- (unsigned int)getUploadingProgress;
- (id)description;
- (void)getSound:(id)arg1;
- (void)getSound:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)getSoundToFile:(id)arg1 cb:(id)arg2;
- (void)getSoundToFile:(id)arg1 succ:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;

@end

