//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TIMUserDefinedStatus : NSObject
{
    NSString *identifier;
    NSArray *uints;
}

@property(retain, nonatomic) NSArray *uints; // @synthesize uints;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier;
- (void).cxx_destruct;

@end

