//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TLSErrInfo : NSObject
{
    int dwErrorCode;
    NSString *sErrorTitle;
    NSString *sErrorMsg;
    NSString *sExtraMsg;
}

@property(copy) NSString *sExtraMsg; // @synthesize sExtraMsg;
@property(copy) NSString *sErrorMsg; // @synthesize sErrorMsg;
@property(copy) NSString *sErrorTitle; // @synthesize sErrorTitle;
@property int dwErrorCode; // @synthesize dwErrorCode;
- (void).cxx_destruct;
- (id)description;

@end

