//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, TLSErrInfo, TLSUserInfo;

@protocol TLSPwdLoginListener <NSObject>
- (void)OnPwdLoginTimeout:(TLSErrInfo *)arg1;
- (void)OnPwdLoginFail:(TLSErrInfo *)arg1;
- (void)OnPwdLoginSuccess:(TLSUserInfo *)arg1;
- (void)OnPwdLoginReaskImgcodeSuccess:(NSData *)arg1;
- (void)OnPwdLoginNeedImgcode:(NSData *)arg1 andErrInfo:(TLSErrInfo *)arg2;
@end

