//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OTPAuthURL.h"

@interface TOTPAuthURL : OTPAuthURL
{
    double generationAdvanceWarning_;
    double lastProgress_;
    _Bool warningSent_;
}

+ (void)totpTimer:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool warningSent; // @synthesize warningSent=warningSent_;
@property(nonatomic) double lastProgress; // @synthesize lastProgress=lastProgress_;
@property(nonatomic) double generationAdvanceWarning; // @synthesize generationAdvanceWarning=generationAdvanceWarning_;
- (id)url;
- (void)totpTimer:(id)arg1;
- (id)otpCodeForDate:(id)arg1;
- (id)otpCode;
- (void)dealloc;
- (id)initWithName:(id)arg1 secret:(id)arg2 algorithm:(id)arg3 digits:(unsigned long long)arg4 query:(id)arg5;
- (id)initWithTOTPURL:(id)arg1;
- (id)initWithSecret:(id)arg1 name:(id)arg2;
- (id)initWithOTPGenerator:(id)arg1 name:(id)arg2;

@end

