//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TZAlbumModel, UIButton, UIImageView, UILabel;

@interface TZAlbumCell : UITableViewCell
{
    TZAlbumModel *_model;
    UIButton *_selectedCountButton;
    UIImageView *_posterImageView;
    UILabel *_titleLable;
    UIImageView *_arrowImageView;
}

@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(nonatomic) __weak UIImageView *posterImageView; // @synthesize posterImageView=_posterImageView;
@property(nonatomic) __weak UIButton *selectedCountButton; // @synthesize selectedCountButton=_selectedCountButton;
@property(retain, nonatomic) TZAlbumModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)layoutSubviews;

@end

