//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (GMOMobileColors)
+ (id)googleAdYellowBackgroundColor;
+ (id)googleGreenURLTextColor;
+ (id)googleBlueTextColor;
+ (id)googleTableViewSeparatorColor;
+ (id)googleReadItemBackgroundColor;
+ (id)googleBlueBackgroundColor;
+ (id)googleBlueBarColor;
@end

