//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (scale)
+ (id)getRectImageFromImage:(id)arg1 withRect:(struct CGRect)arg2;
+ (id)createRoundedRectImage:(id)arg1 size:(struct CGSize)arg2;
+ (id)scaleImage:(id)arg1 toSize:(struct CGSize)arg2;
@end

