//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "UMTBase.h"

@class NSString;

@interface UMTPropertyValue : NSObject <UMTBase, NSCoding>
{
    NSString *__string_value;
    long long __long_value;
    _Bool __string_value_isset;
    _Bool __long_value_isset;
}

@property(readonly, copy) NSString *description;
- (void)validate;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetLong_value;
- (_Bool)long_valueIsSet;
@property(nonatomic, getter=long_value, setter=setLong_value:) long long long_value;
- (void)unsetString_value;
- (_Bool)string_valueIsSet;
@property(retain, nonatomic, getter=string_value, setter=setString_value:) NSString *string_value;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithString_value:(id)arg1 long_value:(long long)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

