//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface VC_ElementManager : NSObject
{
    NSArray *_mainVCItemsArr;
    NSArray *_seniorVCItemsArr;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *seniorVCItemsArr; // @synthesize seniorVCItemsArr=_seniorVCItemsArr;
@property(retain, nonatomic) NSArray *mainVCItemsArr; // @synthesize mainVCItemsArr=_mainVCItemsArr;
- (void).cxx_destruct;
- (id)init;

@end

