//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VideoAWSSignature : NSObject
{
}

+ (id)timestampLocale;
+ (id)convertDateToString:(id)arg1 usingFormat:(id)arg2;
+ (id)GMTtimeStr;
- (id)formatString:(id)arg1;
- (id)canonicalizedResourceWithurlPath:(id)arg1;
- (id)canonicalizedHeadersWithhttp:(id)arg1;
- (id)HMACSign:(id)arg1 withKey:(id)arg2 usingAlgorithm:(unsigned int)arg3;
- (id)stringToSignWithRequest:(id)arg1 Withpath:(id)arg2;
- (void)signRequestWithRequest:(id)arg1 resourcepath:(id)arg2 accessid:(id)arg3 accesskey:(id)arg4;

@end

