//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString;

@interface VoiceRecorderBaseVC : UIViewController
{
    long long maxRecordTime;
    NSString *recordFileName;
    NSString *recordFilePath;
}

+ (id)getAudioRecorderSettingDict;
+ (id)getPathByFileName:(id)arg1;
+ (id)getPathByFileDirectory;
+ (id)getPathByFileName:(id)arg1 ofType:(id)arg2;
+ (_Bool)deleteFileAtPath:(id)arg1;
+ (_Bool)fileExistsAtPath:(id)arg1;
+ (id)getCacheDirectory;
+ (id)getCurrentTimeString;
@property(retain, nonatomic) NSString *recordFilePath; // @synthesize recordFilePath;
@property(retain, nonatomic) NSString *recordFileName; // @synthesize recordFileName;
@property(nonatomic) long long maxRecordTime; // @synthesize maxRecordTime;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

