//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Wtlogin64_RegTlv.h"

@interface Wtlogin64_RegTlv_0x2 : Wtlogin64_RegTlv
{
    unsigned int accountType_;
}

@property unsigned int accountType; // @synthesize accountType=accountType_;
- (int)encode:(id)arg1;
- (id)init;

@end

