//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@protocol Wtlogin64_WloginProtocolBuff <NSObject>

@optional
- (int)encode:(NSMutableData *)arg1;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;
@end

