//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Wtlogin64_WloginTlv_Buff.h"

@class NSData;

@interface Wtlogin64_WloginTlv_0x125 : Wtlogin64_WloginTlv_Buff
{
    NSData *openId;
}

@property(copy) NSData *openId; // @synthesize openId;
- (void).cxx_destruct;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

