//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QalReqCallbackProtocol.h"
#import "TLSSimpleSocketDelegate.h"

@class NSMutableArray, NSMutableData, NSObject<OS_dispatch_queue>, NSString, TLSSimpleSocket;

@interface Wtlogin64_SocketNetworkAdapter : NSObject <TLSSimpleSocketDelegate, QalReqCallbackProtocol>
{
    NSObject<OS_dispatch_queue> *loginQueue;
    id <Wtlogin64_SocketNetworkAdapterProtocol> adapterDelegate;
    NSMutableData *rspData;
    NSMutableArray *rspReadArray;
    TLSSimpleSocket *simpleSocket;
    int type;
}

- (void).cxx_destruct;
- (void)onSocketError:(id)arg1;
- (void)onSocketRecive:(id)arg1 tag:(long long)arg2;
- (void)readDataToLength:(unsigned long long)arg1 withTimeout:(double)arg2 tag:(long long)arg3;
- (void)writeData:(id)arg1 withTimeout:(double)arg2 param:(id)arg3 tag:(long long)arg4;
- (void)onReqSucc:(id)arg1;
- (void)onReqFail:(int)arg1;
- (_Bool)isConnected;
- (void)disconnect;
- (void)setSocketDispatchQueue:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

