//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Wtlogin64_WloginTlv.h"

@interface Wtlogin64_WloginTlv_0x17a : Wtlogin64_WloginTlv
{
    unsigned int dwSmsAppId;
}

@property unsigned int dwSmsAppId; // @synthesize dwSmsAppId;
- (int)encode:(id)arg1;

@end

