//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Wtlogin64_WloginTlv.h"

@class NSString;

@interface Wtlogin64_WloginTlv_0x167 : Wtlogin64_WloginTlv
{
    unsigned char cImgType;
    unsigned char cImgFormat;
    NSString *sImgUrl;
}

@property(copy) NSString *sImgUrl; // @synthesize sImgUrl;
@property unsigned char cImgFormat; // @synthesize cImgFormat;
@property unsigned char cImgType; // @synthesize cImgType;
- (void).cxx_destruct;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;

@end

