//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Wtlogin64_WloginTlv.h"

@class NSData;

@interface Wtlogin64_WloginTlv_0x184 : Wtlogin64_WloginTlv
{
    NSData *sMS2;
}

@property(copy) NSData *sMS2; // @synthesize sMS2;
- (void).cxx_destruct;
- (int)encode:(id)arg1;

@end

