//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface Wtlogin64_WloginWording : NSObject
{
    NSMutableDictionary *_dict;
}

+ (id)singleton;
@property(retain, nonatomic) NSMutableDictionary *dict; // @synthesize dict=_dict;
- (void).cxx_destruct;
- (id)_langDesc;
- (void)_initDict;
- (id)wording:(id)arg1;
- (id)init;

@end

